# PANDAS Y DATAFRAMES

In [112]:
# Lee archivos Stata, SPSS y SAS
!pip -q install pyreadstat

- <a href='#1.'>I. `Pandas`</a>  
     - <a href='#1.1.'>1.1. Definición y Características</a>
     - <a href='#1.2.'>1.2. Generación de `Series`</a>
     - <a href='#1.3.'>1.3. `Series` vs `NumPy`</a>
     - <a href='#1.4.'>1.4. Indexar</a></a>
- <a href='#2.'>II. `DataFrames`</a>
     - <a href='#2.1.'>2.1. Generación de `DataFrames`</a>
     - <a href='#2.2.'>2.2. Indexing</a>
     - <a href='#2.3.'>2.3. Métodos Generales</a>
     - <a href='#2.4.'>2.4. Data GitHub: Programadores en el mundo</a>
     - <a href='#2.5.'>2.5. Data ENAPRES</a>

# <a id='1.'>I. `Pandas`</a>

## <a id='1.1.'>1.1. Definición y Características</a>

**DEFINICIÓN:**

* `Pandas` es una biblioteca de Python utilizada para trabajar con conjuntos de datos: vamos a llamarla cada vez que trabajamos con DataFrames.
* Es la librería más importante de aprender para limpiar, transforar y agregar datos.
* Como es externa, necesitamos importarla para trabajar en nuestro quehacer diario mediante la palabra clave `import`.

In [113]:
import pandas as pd
import numpy as np

* Ahora, el paquete de `Pandas` está referido como `pd` en lugar de Pandas.

**CARACTERÍSTICAS:**

* La primera estructura de datos de `Pandas` es una Serie, que es un arreglo unidimensional que puede contener cualquier tipo de datos, de manera similar a un ndarray.
* Tiene un índice (index) que le asigna una etiqueta a cada entrada. Por lo general, el índice se utiliza para etiquetar los datos.
* Contiene información sobre una sola característica (feature) de los datos.
* Un `Pandas Dataframe` son muchas Series.

## <a id='1.2.'>1.2. Generación de `Series`<a>

### De `lists` a `Series`:

In [114]:
# Recordemos una lista de Python, vista la clase pasada:
list1 = [0.25, 0.5, 0.75, 1.0]
list1

[0.25, 0.5, 0.75, 1.0]

In [115]:
# Se puede decir que una Serie es una columna:
pd.Series([1, 5, 8, 9, 10])

0     1
1     5
2     8
3     9
4    10
dtype: int64

In [116]:
list2 =  [1, 1.5, 2, 2.5, 3]
list2

[1, 1.5, 2, 2.5, 3]

In [117]:
# Convertimos la lista en una Serie de Pandas:
data = pd.Series(list2)
data

0    1.0
1    1.5
2    2.0
3    2.5
4    3.0
dtype: float64

In [118]:
# Ya tenemos nuestros datos convertidos a Series
print(data)

0    1.0
1    1.5
2    2.0
3    2.5
4    3.0
dtype: float64

* **Una base de datos es un conjunto de Series.**
* Podemos convertir un Numpy y diccionarios a Series también.

### De `NumPy array` a `Series`:

In [119]:
# Veamos un ejemplo de un vector de Numpy, que es otra estructura de datos muy utilizada en Python
# La clase pasada vimos que un vector es una lista de números:
vector1 = np.array([10, 20, 1, 2, 
                    3, 4, 5, 6, 7, 10])
vector1

array([10, 20,  1,  2,  3,  4,  5,  6,  7, 10])

In [120]:
# Ahora convertimos el vector de Numpy a una Serie de Pandas:
series1 = pd.Series( vector1 )
series1

0    10
1    20
2     1
3     2
4     3
5     4
6     5
7     6
8     7
9    10
dtype: int32

In [121]:
# Las Series de Pandas son más complejas que los vectores de Numpy, ya que permiten almacenar información adicional como el índice y el nombre de la Serie.
print(type(vector1))
print(type(series1))

<class 'numpy.ndarray'>
<class 'pandas.core.series.Series'>

### De `Dictionary` a `Series`:

In [122]:
population_dict= { 'California' : 38332521,
                    'Texas'      : 26448193,
                    'New York'   : 19651127,
                    'Florida'    : 19552860,
                    'Illinois'   : 12882135 }

In [123]:
# Vemos las llaves:
population_dict.keys()

dict_keys(['California', 'Texas', 'New York', 'Florida', 'Illinois'])

In [124]:
# Al convertirlo en Series, la indexación absorde las llaves.
# Por tanto, la indexación también puede tener texto. Sin embargo, no es lo ideal. Se recomienda números partiendo desde 0.
population = pd.Series( population_dict )
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

## <a id='1.3.'>1.3. `Series` vs `NumPy`</a>

* La diferencia esencial es la presencia del índice: mientras que el `Numpy Array` tiene un índice entero definido de forma implícita que se utiliza para acceder a los valores, los `Pandas Series` tienen un índice explícito asociado a los valores.

* El `index` (índice) no necesita ser un entero. Podemos usar `strings` (cadenas de texto).

In [125]:
# Creamos un vector de Numpy con valores del 5 al 20, con un paso de 2:
claudia = np.arange(5, 21, 2)
claudia

array([ 5,  7,  9, 11, 13, 15, 17, 19])

In [126]:
# Convertimos el vector de Numpy a una Serie de Pandas, con un índice personalizado:
# Ahora la serie es de 3 en 3, y el índice es un nombre de persona.
math = pd.Series( np.arange(5.,21.,3.) , ['joyce','jeremy','ivan','marcy','daniel','franclin'])
math

joyce        5.0
jeremy       8.0
ivan        11.0
marcy       14.0
daniel      17.0
franclin    20.0
dtype: float64

In [127]:
# Creamos una serie del 5 al 15, de 3 en 3, con un índice personalizado:
info = np.arange(5 , 15 ,3.)
index_info =  ['joyce','jeremy','ivan','marcy']

In [128]:
# De los objetos creados anteriormente, podemos crear una Serie de Pandas con un índice personalizado y un nombre para la Serie:
# Students sería el nombre de la Serie, y el índice es el nombre de cada estudiante.
math_2 = pd.Series(  info , index_info,  name = "Students")
math_2

joyce      5.0
jeremy     8.0
ivan      11.0
marcy     14.0
Name: Students, dtype: float64

## <a id='1.4.'>1.4. Indexar</a>

* Indexar (o la indexación) en `Pandas` significa simplemente seleccionar filas y columnas particulares de datos de un DataFrame.
* También puede conocerse como Selección de Subconjuntos.

In [129]:
# Veamos a data y population:
print(data)
print(population)

0    1.0
1    1.5
2    2.0
3    2.5
4    3.0
dtype: float64
California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [130]:
data[1]

1.5

In [131]:
# En número, si quiero ir hasta un índice particular, tengo que hacer lo siguiente:
# Si quiero del 0 al 2, la indexación va hasta el 3.
# Siempre uno menos si estoy en números.
print( data[0:3] )

0    1.0
1    1.5
2    2.0
dtype: float64

In [132]:
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

* `dtype` es el tipo de data, no el tipo de objeto.
* Puede haber `int16`, `int32`, `int64` o `float64`. Eso importará cuando hagamos Deep Learning, cuando involucremos al decimal 20.

In [133]:
# Cuando es texto, la indexación sí incluye el último elemento
print( population['Texas':'Florida'] )

Texas       26448193
New York    19651127
Florida     19552860
dtype: int64

| Método 	| Definición 	|
| --- 	| --- 	|
| loc() 	|Obtiene filas (y/o columnas) con etiquetas (labels) particulares.<br> Acepta valores booleanos (`bool`) para el indexado. |
| iloc() 	| Obtiene filas (y/o columnas) en posiciones de enteros (integer locations). <br> No acepta valores booleanos (`bool`) para el indexado.|

* Obtener el valor de Nueva York:

In [134]:
# loc(): Con una etiqueta particular, obtenemos el valor de la Serie. En este caso, la población de New York.
population.loc[ "New York" ]

19651127

In [135]:
# iloc(): Con valores de indexación, obtenemos el valor de la Serie. En este caso, la población desde Texas hasta Illinois.
# Excluimos California por ser el primer elemento.
population.iloc[ 1:6 ]

Texas       26448193
New York    19651127
Florida     19552860
Illinois    12882135
dtype: int64

Replicate this excersice for `data` Series.

# <a id='2.'>II. `DataFrames`</a>

* Un `DataFrame` es una colección de múltiples Series. Puede pensarse como un arreglo bidimensional (2D), donde cada fila es un punto de datos (datapoint) independiente y cada columna es una característica (feature) de los datos. Las filas están etiquetadas con un índice (al igual que en una Series) y las columnas están etiquetadas en el atributo columns.

* Existen muchas formas diferentes de crear `DataFrames`: a partir de listas, diccionarios, etc.

* Usaremos `Pandas` para trabajar con `DataFrames`.

## <a id='2.1.'>2.1. Generación de `DataFrames`</a>
### De `lists` y `dict` a `DataFrame`:

In [136]:
# Notas de estudiantes (lista)
students = [ "Alejandro", "Pedro", "Ramiro", "Axel", "Juan" ]
math     = [ 15, 16, 10, 12, 13 ]
english  = [ 13, 9, 16, 14, 17 ]
art      = [ 12, 16, 15, 19, 10 ]

# Diccionario:
# A cada llave le asignamos una lista 
gradesA = {'Students':students, 'Math':math, 'English':english, 'Art':art}

In [137]:
gradesA

{'Students': ['Alejandro', 'Pedro', 'Ramiro', 'Axel', 'Juan'],
 'Math': [15, 16, 10, 12, 13],
 'English': [13, 9, 16, 14, 17],
 'Art': [12, 16, 15, 19, 10]}

In [138]:
# Convertimos el diccionario en un DataFrame de Pandas:
gradesA1 = pd.DataFrame(gradesA)
gradesA1

    Students  Math  English  Art
0  Alejandro    15       13   12
1      Pedro    16        9   16
2     Ramiro    10       16   15
3       Axel    12       14   19
4       Juan    13       17   10

## <a id='2.2.'>2.2. Indexing</a>

* Podemos utilizar los mismos métodos que en las `Series`: `iloc` y `loc`, seleccionando tanto columnas como filas.

In [139]:
# Otras notas de estudiantes (lista)
students = [ "Gissela", "Daniel", "Andres", "Sandra", "Rosalyn" ]
math     = [ 16, 14, 17, 17, 17 ]
english  = [ 16, 17, 19, 18, 15 ]
art      = [ 11, 17, 13, 14, 17 ]

# Diccionario
diplomado = {'Students':students, 'Math':math, 'English':english, 'Art':art}

# DataFrame:
gradesA1 = pd.DataFrame( diplomado )
gradesA1

  Students  Math  English  Art
0  Gissela    16       16   11
1   Daniel    14       17   17
2   Andres    17       19   13
3   Sandra    17       18   14
4  Rosalyn    17       15   17

In [140]:
# MÉTODO loc(): Con valores de indexación, obtenemos el valor de la Serie.
# En este caso, seleccionamos las filas que van desde el 0 hasta el 3 y las columnas de "Art" y "Students"
# Recordar que loc es un método porque está al costado del objeto y no al costado del alias de la librería (pd como Pandas, por ejemplo).
gradesA1.loc[ 0:3 ,  ["Art", "Students"] ]

   Art Students
0   11  Gissela
1   17   Daniel
2   13   Andres
3   14   Sandra

In [141]:
# Ahora seleccionamos todas las filas (:) y las columnas "Students", "English" y "Art".
gradesA1.loc[ :, ["Students", "English", "Art"] ]

  Students  English  Art
0  Gissela       16   11
1   Daniel       17   17
2   Andres       19   13
3   Sandra       18   14
4  Rosalyn       15   17

## <a id='2.3.'>2.3. Métodos Generales</a>

|Métodos|Descripción|
|------|-----------|
|columns()|Obtiene el nombre de las columnas.|
|sort_values()|Ordena según los valores a lo largo de cualquiera de los ejes.|
|sort_index()|Ordena según el índice.|
|head()|Muestra las primeras N observaciones.|
|drop( )| Elimina las entradas con la etiqueta o etiquetas especificadas.|
|append( )| Concatena dos o más Series.|
|drop_duplicates( )| Elimina los valores duplicados.|
|dropna( ) |Elimina las entradas nulas.|
|fillna( ) |Reemplaza las entradas nulas con un valor o estrategia especificada.|
|reset_index( )| Convierte el índice en una columna.|
|sample( ) |Extrae una entrada aleatoria.|
|shift( ) |Desplaza el índice.|
|unique( ) |Devuelve los valores únicos.|

In [142]:
# Veamos otro ejemplo, ahora con diccionarios:
deps = {
        'dep' : ['Lima', 'Piura', 'Tumbes', 'Cuzco', 'Ica', 'Puno'],
        'year': [ 2000, 2001, 2002, 2001, 2002, 2003 ],
        'pop' : [ 1.5, 1.7, 3.6, 2.4, 2.9, 3.2 ] 
        }
dep1 = pd.DataFrame( deps )
dep1

      dep  year  pop
0    Lima  2000  1.5
1   Piura  2001  1.7
2  Tumbes  2002  3.6
3   Cuzco  2001  2.4
4     Ica  2002  2.9
5    Puno  2003  3.2

* El método `sort_values` tiene muchos argumentos: `inlpace` es uno de ellos y por default es `False`.
* Por ello es importante explicitar cuando lo queremos `True`, para que los cambios tengan efecto en la data ahí mismo. 
* `inplace` = `True` quiere decir que haga efectivo los cambios ahí mismo y que chanques la data. Es razonable para no crear más objetos.

In [143]:
# Quiero ordenarlo según la variable "dep" (departamento): usamos el método sort_values para ordenar.
# Se ordena alfabéticamente porque dep es chr, si fuera variable int se ordena de menor a mayor.
dep1.sort_values( ["dep"] , inplace=True, )
dep1

      dep  year  pop
3   Cuzco  2001  2.4
4     Ica  2002  2.9
0    Lima  2000  1.5
1   Piura  2001  1.7
5    Puno  2003  3.2
2  Tumbes  2002  3.6

In [144]:
# ascending=False: ordena de mayor a menor, y en letras, de la Z a la A.
dep1.sort_values( ["dep"], inplace= True, ignore_index=True, ascending=False)
dep1

      dep  year  pop
0  Tumbes  2002  3.6
1    Puno  2003  3.2
2   Piura  2001  1.7
3    Lima  2000  1.5
4     Ica  2002  2.9
5   Cuzco  2001  2.4

In [145]:
# Recordemos el DataFrame de notas de estudiantes:
gradesA1

  Students  Math  English  Art
0  Gissela    16       16   11
1   Daniel    14       17   17
2   Andres    17       19   13
3   Sandra    17       18   14
4  Rosalyn    17       15   17

* Operaciones con DataFrames: Veamos los métodos en acción.

In [146]:
# Suma de las columnas "Math" y "English" del DataFrame gradesA1:
gradesA1["Math"] + gradesA1["English"]

0    32
1    31
2    36
3    35
4    32
dtype: int64

In [147]:
# Nueva columna
gradesA1['promedio'] = ( gradesA1['Math'] + gradesA1['English'] + gradesA1['Art'] ) / 3
gradesA1

  Students  Math  English  Art   promedio
0  Gissela    16       16   11  14.333333
1   Daniel    14       17   17  16.000000
2   Andres    17       19   13  16.333333
3   Sandra    17       18   14  16.333333
4  Rosalyn    17       15   17  16.333333

In [148]:
# drop: Eliminar columnas o filas de un DataFrame 
# El parámetro axis=1 indica que buscamos una columna (axis=0 sería para filas).
# inplace = True significa que los cambios se aplican directamente al DataFrame original, sin necesidad de crear una copia.
gradesA1.drop("promedio", axis=1, inplace=True)
gradesA1

  Students  Math  English  Art
0  Gissela    16       16   11
1   Daniel    14       17   17
2   Andres    17       19   13
3   Sandra    17       18   14
4  Rosalyn    17       15   17

In [149]:
# rename: Cambiar el nombre de una columna en un DataFrame
gradesA1.rename(columns={"Students": "Estudiantes"}, inplace=True)
gradesA1

  Estudiantes  Math  English  Art
0     Gissela    16       16   11
1      Daniel    14       17   17
2      Andres    17       19   13
3      Sandra    17       18   14
4     Rosalyn    17       15   17

In [150]:
# iloc(): Con valores de indexación, obtenemos el valor de la Serie. 
# En este caso, el promedio de las columnas de los cursos en las posiciones 2, 3 y 4 (Math, English y Art) para cada estudiante.
# Mean Math & English
gradesA1.iloc[:, 2:4].mean(axis=1)

0    13.5
1    17.0
2    16.0
3    16.0
4    16.0
dtype: float64

In [151]:
# head: Mostrar las primeras filas de un DataFrame. Por defecto, muestra las primeras 5 filas, pero podemos especificar cuántas queremos ver.
gradesA1.head(4)

  Estudiantes  Math  English  Art
0     Gissela    16       16   11
1      Daniel    14       17   17
2      Andres    17       19   13
3      Sandra    17       18   14

* Renombramos de nuevo la columna **Estudiantes** para no tener problemas con el código que sigue:
* Agregar nuevos datos con el método `concat()` de `Pandas`, usando las mismas columnas que el DataFrame original.

In [152]:
# MÉTODO rename
# Formato: .rename(columns={"Columna antigua": "Columna nueva"}, inplace=True)
gradesA1.rename(columns={"Estudiantes": "Students"}, inplace=True)
gradesA1

  Students  Math  English  Art
0  Gissela    16       16   11
1   Daniel    14       17   17
2   Andres    17       19   13
3   Sandra    17       18   14
4  Rosalyn    17       15   17

In [153]:
# Agregamos nueva data: gradesA2
# Nuevos estudiantes y sus notas en Math, English y Art
students = [ "Rebeca", "Xavi", "Cristiano", "Ronaldo", "Leo" ]
math     = [ 15, 18, 14, 7, 10 ]
english  = [ 18, 9, 11, 12, 20 ]
art      = [ 10, 16, 20, 19, 5 ]

# Dictionary
grades_A2 = {'Students':students, 'Math':math, 'English':english, 'Art':art}

# Convertimos el diccionario en un DataFrame de Pandas:
gradesA2 = pd.DataFrame( grades_A2 )
print( gradesA2 , "\n")

    Students  Math  English  Art
0     Rebeca    15       18   10
1       Xavi    18        9   16
2  Cristiano    14       11   20
3    Ronaldo     7       12   19
4        Leo    10       20    5

In [154]:
gradesA1

  Students  Math  English  Art
0  Gissela    16       16   11
1   Daniel    14       17   17
2   Andres    17       19   13
3   Sandra    17       18   14
4  Rosalyn    17       15   17

In [155]:
gradesA2

    Students  Math  English  Art
0     Rebeca    15       18   10
1       Xavi    18        9   16
2  Cristiano    14       11   20
3    Ronaldo     7       12   19
4        Leo    10       20    5

* Unimos ambos datos:

In [156]:
pd.concat( [gradesA1, gradesA2] , ignore_index=True)

    Students  Math  English  Art
0    Gissela    16       16   11
1     Daniel    14       17   17
2     Andres    17       19   13
3     Sandra    17       18   14
4    Rosalyn    17       15   17
5     Rebeca    15       18   10
6       Xavi    18        9   16
7  Cristiano    14       11   20
8    Ronaldo     7       12   19
9        Leo    10       20    5

In [157]:
# Aquí vemos qué sucede si no colocamos ignore_index=True. 
# El índice se mantiene, y se repiten los índices de 0 a 4.
grades_total = pd.concat([gradesA1, gradesA2])
grades_total

    Students  Math  English  Art
0    Gissela    16       16   11
1     Daniel    14       17   17
2     Andres    17       19   13
3     Sandra    17       18   14
4    Rosalyn    17       15   17
0     Rebeca    15       18   10
1       Xavi    18        9   16
2  Cristiano    14       11   20
3    Ronaldo     7       12   19
4        Leo    10       20    5

In [158]:
# Ahora sí, con ignore_index=True, el índice se reinicia y se asigna un nuevo índice a cada fila del DataFrame resultante.
# copy() es para crear una copia del DataFrame resultante y evitar advertencias de Pandas sobre la modificación de un DataFrame que podría estar vinculado a otro.
grades_total = pd.concat([gradesA1, gradesA2], ignore_index=True).copy()
grades_total

    Students  Math  English  Art
0    Gissela    16       16   11
1     Daniel    14       17   17
2     Andres    17       19   13
3     Sandra    17       18   14
4    Rosalyn    17       15   17
5     Rebeca    15       18   10
6       Xavi    18        9   16
7  Cristiano    14       11   20
8    Ronaldo     7       12   19
9        Leo    10       20    5

* Si hay una columna con datos parciales en una columna, aparecerá "NaN" en los valores faltantes.

In [159]:
# Veamos otro ejemplo de DataFrame, ahora con información de autos:
cars = pd.DataFrame({
            'brands'    : [ 'hyundai', 'hyundai', 'kia', 'kia', 'kia' ] ,
            'model'     : [ 'sedan', 'sedan', 'sedan', 'truck', 'truck' ] ,
            'passengers': [ 4, 4, 5, 6, 8 ]
            })
cars

    brands  model  passengers
0  hyundai  sedan           4
1  hyundai  sedan           4
2      kia  sedan           5
3      kia  truck           6
4      kia  truck           8

In [160]:
# Eliminamos duplicados de las columnas "brands" y "model" del DataFrame cars, dejando solo la primera ocurrencia de cada combinación única de estas columnas.
# Se quedan las combinaciones únicas de "brands" y "model": 
# * 0 hyuandai sedan
# * 2 kia sedan
# * 3 kia truck
cars.drop_duplicates(subset = [ "brands", "model"])

    brands  model  passengers
0  hyundai  sedan           4
2      kia  sedan           5
3      kia  truck           6

In [161]:
# Si queremos algo más habitual, lo mejor es restringir por columna.
# Usaremos "brands", por lo que ahora solo nos debe mostrar elementos únicos de la columna "brands"
cars_subset = cars.drop_duplicates(subset = [ 'brands' ])
cars_subset

    brands  model  passengers
0  hyundai  sedan           4
2      kia  sedan           5

In [162]:
# Recordemos el DataFrame de notas de estudiantes:
grades_total

    Students  Math  English  Art
0    Gissela    16       16   11
1     Daniel    14       17   17
2     Andres    17       19   13
3     Sandra    17       18   14
4    Rosalyn    17       15   17
5     Rebeca    15       18   10
6       Xavi    18        9   16
7  Cristiano    14       11   20
8    Ronaldo     7       12   19
9        Leo    10       20    5

In [163]:
# dropna
print( grades_total )

    Students  Math  English  Art
0    Gissela    16       16   11
1     Daniel    14       17   17
2     Andres    17       19   13
3     Sandra    17       18   14
4    Rosalyn    17       15   17
5     Rebeca    15       18   10
6       Xavi    18        9   16
7  Cristiano    14       11   20
8    Ronaldo     7       12   19
9        Leo    10       20    5

In [164]:
# MÉTODO dropna(): Elimina las filas que contienen valores nulos (NaN) en el DataFrame.
# Sin embargo, no hay NAs, por lo que la columna permanece igual.
grades_total.dropna()

    Students  Math  English  Art
0    Gissela    16       16   11
1     Daniel    14       17   17
2     Andres    17       19   13
3     Sandra    17       18   14
4    Rosalyn    17       15   17
5     Rebeca    15       18   10
6       Xavi    18        9   16
7  Cristiano    14       11   20
8    Ronaldo     7       12   19
9        Leo    10       20    5

In [165]:
# MÉTODO sample(): Devuelve una muestra aleatoria de filas del DataFrame.
grades_total.sample( n=3 )

  Students  Math  English  Art
4  Rosalyn    17       15   17
0  Gissela    16       16   11
2   Andres    17       19   13

In [166]:
# Ahora una muestra de 5 filas:
print( grades_total.sample(n = 5) )

  Students  Math  English  Art
5   Rebeca    15       18   10
2   Andres    17       19   13
8  Ronaldo     7       12   19
3   Sandra    17       18   14
9      Leo    10       20    5

In [167]:
# Ahora una muestra del 20% de las filas del DataFrame, con una semilla aleatoria para reproducibilidad.
# La elección es aleatoria, por lo que cada vez que ejecutemos el código obtendremos resultados diferentes.
print( grades_total.sample( frac = 0.2, random_state=123 ), "\n")

  Students  Math  English  Art
4  Rosalyn    17       15   17
0  Gissela    16       16   11

## <a id='2.4.'>2.4. Importando datos: GitHub</a>

**INNOVATION GRAPH:**
* Contiene los repositorios por temática y país alrededor del mundo.

In [168]:
# URL del archivo CSV hospedado en GitHub (hacemos click en "Raw")
# Repositorios de Github de la página de Innovation Graph:
url = "https://raw.githubusercontent.com/github/innovationgraph/refs/heads/main/data/repositories.csv"

# Carga directa desde la URL
df = pd.read_csv(url)

# Muestra las primeras filas del DataFrame
df

      repositories iso2_code  year  quarter
0         30669781        US  2020        1
1         20179087        CN  2020        1
2         17912888        EU  2020        1
3          9254535        IN  2020        1
4          4171705        GB  2020        1
...            ...       ...   ...      ...
5630           231        AQ  2026        1
5631           219        MH  2026        1
5632           196        IO  2026        1
5633           161        PM  2026        1
5634           142        MS  2026        1

[5635 rows x 4 columns]

In [169]:
# Renombrar columnas:
df.rename(columns={"repositories": "num_repos"}, inplace=True)
df

      num_repos iso2_code  year  quarter
0      30669781        US  2020        1
1      20179087        CN  2020        1
2      17912888        EU  2020        1
3       9254535        IN  2020        1
4       4171705        GB  2020        1
...         ...       ...   ...      ...
5630        231        AQ  2026        1
5631        219        MH  2026        1
5632        196        IO  2026        1
5633        161        PM  2026        1
5634        142        MS  2026        1

[5635 rows x 4 columns]

In [170]:
# Seleccionar solo Perú:
# La idea es seleccionar la columna y colocar los valores que quiero encontrar.
# Para eso se crearon booleanos donde se seleccionarán los valores TRUE
# Traducción: En la base df, quiero los valores del df que son PE
df[df["iso2_code"] == "PE"]

      num_repos iso2_code  year  quarter
49       356948        PE  2020        1
263      391794        PE  2020        2
480      424103        PE  2020        3
698      456011        PE  2020        4
916      485312        PE  2021        1
1136     527124        PE  2021        2
1356     567869        PE  2021        3
1580     609800        PE  2021        4
1803     652580        PE  2022        1
2025     704939        PE  2022        2
2247     753704        PE  2022        3
2472     805264        PE  2022        4
2696     852209        PE  2023        1
2923     913172        PE  2023        2
3150     969559        PE  2023        3
3378    1021424        PE  2023        4
3604    1070001        PE  2024        1
3832    1138879        PE  2024        2
4058    1207493        PE  2024        3
4289    1280517        PE  2024        4
4518    1336842        PE  2025        1
4748    1439611        PE  2025        2
4979    1540677        PE  2025        3
5211    1648544        PE  2025        4
5442    1726117        PE  2026        1

In [171]:
# Si quiero dos países: Perú y Argentina
# Usamos un "o" (or) y paréntesis para cada condición
df[ (df["iso2_code"] == "PE") | (df["iso2_code"] == "AR") ]

      num_repos iso2_code  year  quarter
31       608445        AR  2020        1
49       356948        PE  2020        1
244      670189        AR  2020        2
263      391794        PE  2020        2
460      737110        AR  2020        3
480      424103        PE  2020        3
678      802976        AR  2020        4
698      456011        PE  2020        4
898      867545        AR  2021        1
916      485312        PE  2021        1
1118     965194        AR  2021        2
1136     527124        PE  2021        2
1340    1070330        AR  2021        3
1356     567869        PE  2021        3
1563    1180271        AR  2021        4
1580     609800        PE  2021        4
1785    1312481        AR  2022        1
1803     652580        PE  2022        1
2007    1514018        AR  2022        2
2025     704939        PE  2022        2
2231    1692345        AR  2022        3
2247     753704        PE  2022        3
2456    1827329        AR  2022        4
2472     805264        PE  2022        4
2681    1972535        AR  2023        1
2696     852209        PE  2023        1
2908    2158627        AR  2023        2
2923     913172        PE  2023        2
3135    2297445        AR  2023        3
3150     969559        PE  2023        3
3363    2456325        AR  2023        4
3378    1021424        PE  2023        4
3590    2557620        AR  2024        1
3604    1070001        PE  2024        1
3818    2695815        AR  2024        2
3832    1138879        PE  2024        2
4046    2816763        AR  2024        3
4058    1207493        PE  2024        3
4278    2910039        AR  2024        4
4289    1280517        PE  2024        4
4507    3003205        AR  2025        1
4518    1336842        PE  2025        1
4738    3158220        AR  2025        2
4748    1439611        PE  2025        2
4969    3309686        AR  2025        3
4979    1540677        PE  2025        3
5201    3471573        AR  2025        4
5211    1648544        PE  2025        4
5433    3598412        AR  2026        1
5442    1726117        PE  2026        1

In [172]:
# Quiero los códigos de los países de Sudamérica, que son: PE, AR, BR, CL, CO, EC, GY, PY, SR, UY y VE.
# Usamos el método isin() para seleccionar los valores que están en la lista de países sud
# Creamos lista:
south_america_codes = [
    "AR", "BO", "BR", "CL", "CO", "EC",
    "GY", "PY", "PE", "SR", "UY", "VE", "GF"
]

# Filter DataFrame
df_south_america = df[df["iso2_code"].isin(south_america_codes)]
df_south_america

      num_repos iso2_code  year  quarter
5       3602025        BR  2020        1
26       678828        CO  2020        1
31       608445        AR  2020        1
49       356948        PE  2020        1
50       353627        CL  2020        1
...         ...       ...   ...      ...
5493     309547        UY  2026        1
5508     163202        PY  2026        1
5576       9645        GY  2026        1
5582       7373        SR  2026        1
5594       4194        GF  2026        1

[325 rows x 4 columns]

In [173]:
# Queremos saber cuántas columnas y filas hay en DataFrame de países de Sudamérica:
df_south_america.shape

(325, 4)

In [174]:
# Podemos extraer columnas específicas
# Van dos corchetes porque estamos extrayendo varias columnas, y no una sola. Si fuera una sola columna, bastaría con un solo corchete.
# No chancamos la información, solo nos muestra el resultado.
# El corchete indica que es una lista.
df_south_america[["quarter", "year"]]

      quarter  year
5           1  2020
26          1  2020
31          1  2020
49          1  2020
50          1  2020
...       ...   ...
5493        1  2026
5508        1  2026
5576        1  2026
5582        1  2026
5594        1  2026

[325 rows x 2 columns]

In [175]:
# Eso implica que podemos reordenar las columnas:
# Con el siglo igual, ahora sí chanco el df
df_south_america = df_south_america[["iso2_code", "year", "quarter", "num_repos"]]
df_south_america

     iso2_code  year  quarter  num_repos
5           BR  2020        1    3602025
26          CO  2020        1     678828
31          AR  2020        1     608445
49          PE  2020        1     356948
50          CL  2020        1     353627
...        ...   ...      ...        ...
5493        UY  2026        1     309547
5508        PY  2026        1     163202
5576        GY  2026        1       9645
5582        SR  2026        1       7373
5594        GF  2026        1       4194

[325 rows x 4 columns]

In [176]:
# El index sigue siendo caótico, desordenado. Procedemos a ordenarlo y reiniciar el índice:
df_south_america.reset_index(inplace=True)
df_south_america

     index iso2_code  year  quarter  num_repos
0        5        BR  2020        1    3602025
1       26        CO  2020        1     678828
2       31        AR  2020        1     608445
3       49        PE  2020        1     356948
4       50        CL  2020        1     353627
..     ...       ...   ...      ...        ...
320   5493        UY  2026        1     309547
321   5508        PY  2026        1     163202
322   5576        GY  2026        1       9645
323   5582        SR  2026        1       7373
324   5594        GF  2026        1       4194

[325 rows x 5 columns]

In [177]:
# Podemos eliminar o mantener la nueva columna index creada
# Decidimos eliminarla porque no es necesaria y solo ocupa espacio.
df_south_america.drop(columns=["index"], inplace=True)
df_south_america

    iso2_code  year  quarter  num_repos
0          BR  2020        1    3602025
1          CO  2020        1     678828
2          AR  2020        1     608445
3          PE  2020        1     356948
4          CL  2020        1     353627
..        ...   ...      ...        ...
320        UY  2026        1     309547
321        PY  2026        1     163202
322        GY  2026        1       9645
323        SR  2026        1       7373
324        GF  2026        1       4194

[325 rows x 4 columns]

In [178]:
# Queremos ordenar el DataFrame por las columnas "iso2_code", "year" y "quarter" en orden ascendente.
# Como si fuera una serie de tiempo: primero por país, luego por año y finalmente por trimestre.
df_south_america = df_south_america.sort_values(
    by=["iso2_code", "year", "quarter"],
    ascending=[True, True, True]
)
df_south_america

    iso2_code  year  quarter  num_repos
2          AR  2020        1     608445
15         AR  2020        2     670189
28         AR  2020        3     737110
41         AR  2020        4     802976
54         AR  2021        1     867545
..        ...   ...      ...        ...
266        VE  2025        1     380857
279        VE  2025        2     403230
292        VE  2025        3     421440
305        VE  2025        4     438426
318        VE  2026        1     460235

[325 rows x 4 columns]

* Es importante tener en cuenta que la base debe estar balanceada. 
* Es decir, que todos los quearter tengan dato. Si no sucede, hablar con el encargado. Quizás sea conveniente colocar 0 o NaN.

In [179]:
# Quiero ver los valores nulos (NaN) en la columna "num_repos" del DataFrame df_south_america. 
# Esto me permitirá identificar si hay registros sin información.
df_south_america[df_south_america.num_repos.isna() ]

Empty DataFrame
Columns: [iso2_code, year, quarter, num_repos]
Index: []

In [180]:
# El índice volvió a molestarnos (porque se reordenó el DataFrame). Procedemos a ordenarlo y reiniciar el índice:
df_south_america.reset_index(inplace=True)
df_south_america

     index iso2_code  year  quarter  num_repos
0        2        AR  2020        1     608445
1       15        AR  2020        2     670189
2       28        AR  2020        3     737110
3       41        AR  2020        4     802976
4       54        AR  2021        1     867545
..     ...       ...   ...      ...        ...
320    266        VE  2025        1     380857
321    279        VE  2025        2     403230
322    292        VE  2025        3     421440
323    305        VE  2025        4     438426
324    318        VE  2026        1     460235

[325 rows x 5 columns]

In [181]:
# Eliminamos el índice anterior y el que se creó al reiniciar el índice, ya que no es necesario y solo ocupa espacio.
# Columnas level_0 e index:
df_south_america.drop(columns=["level_0", "index"], inplace=True)
df_south_america

KeyError: "['level_0'] not found in axis"

In [ ]:
# Quiero ver el tipo de datos de las columnas:
df_south_america.dtypes

iso2_code    object
year          int64
quarter       int64
num_repos     int64
dtype: object

In [ ]:
# Podemos cambiar el tipo de datos de iso2_code a string (str) para asegurarnos de que se trate como texto y no como un número. 
# Esto es útil si queremos realizar operaciones de texto o evitar problemas de interpretación de datos.
df_south_america["iso2_code"] = df_south_america["iso2_code"].astype(str)
df_south_america.dtypes

iso2_code    object
year          int64
quarter       int64
num_repos     int64
dtype: object

In [ ]:
# Exportamos a formato csv en la misma carpeta del notebook:
# Guarda el DataFrame en la carpeta 'data'
df_south_america.to_csv("data/south_america_repositorios.csv", index=False)

## <a id='2.5.'>2.5. Importando datos: ENAPRES</a>

|Método|Descripción|
|------|-----------|
|read_excel( )|Lee un archivo Excel y lo convierte en un DataFrame.|
|to_csv( )| Escribe el índice y los registros en un archivo CSV|
|read_csv( )| Lee un archivo CSV y lo convierte en un DataFrame.|
|to_json( )| Convierte el objeto en una cadena de texto JSON.|
|to_pickle( )| Serializa el objeto y lo almacena en un archivo externo.|
|to_sql( )| Escribe los datos del objeto en una base de datos SQL activa.|
|read_html( )| Lee una tabla de una página HTML y la convierte en un DataFrame.|
|read_spss( )| Lee un archivo SPSS y lo convierte en un DataFrame.|

* La Encuesta Nacional de Programas Presupuestales (ENAPRES) se lleva a cabo desde el año 2010 en las zonas urbanas y rurales de los 24 departamentos y la Provincia Constitucional del Callao, como parte de las investigaciones realizadas por el Instituto Nacional de Estadística e Informática (INEI) en coordinación con el Ministerio de Economía y Finanzas (MEF) y los diversos ministerios y organismos del sector público.

In [ ]:
import pandas as pd
import os
import pyreadstat

**DIRECCIONES RELATIVAS**

* Descargar el archivo correspondiente
* Usar **pwd** para saber su ubicación actual
* Dos puntos son un click para atrás seguido de un slash, junto con la nueva ruta que le corresponde.

In [ ]:
# 1. Descargamos el archivo SPSS desde la web del INEI
# La ruta del archivo se construye utilizando os.path.join para asegurar la compatibilidad entre sistemas operativos
ruta_spss = os.path.join("data", "CAP_100_URBANO_RURAL_3.sav")

In [ ]:
# 2. Leemos el archivo con pyreadstat. 
# Esto nos devuelve DOS objetos: los datos (enapres2020_1) y los metadatos (metadata)
enapres2020_1, metadata = pyreadstat.read_sav(ruta_spss)

# Mostramos las primeras 5 filas de los datos para verificar que cargó bien
enapres2020_1.head()

,PER,ANIO,MES,CONGLOMERADO,NSELV,TSELV,VIVREM,NUMVIVREM,AREA,CCDD,...,P189_5,P189_6,P189_7,P189_8,P189_8_O,REGIONNATU,ESTRATO,MOD_ENC,FACTOR,FACTOR_CALIBRADO
0,2.0,2020,07,04046,0046,5.0,0.0,NaN,2.0,14,...,NaN,NaN,NaN,NaN,,1,NaN,2.0,121.27014,NaN
1,2.0,2020,09,03981,0120,1.0,0.0,NaN,1.0,14,...,NaN,NaN,NaN,NaN,,1,4.0,1.0,245.10805,395.8496
2,2.0,2020,09,03981,0189,1.0,0.0,NaN,1.0,14,...,NaN,NaN,NaN,NaN,,1,4.0,1.0,245.10805,395.8496
3,2.0,2020,09,03981,0189,1.0,0.0,NaN,1.0,14,...,NaN,NaN,NaN,NaN,,1,4.0,1.0,245.10805,395.8496
4,2.0,2020,07,04046,0043,5.0,0.0,NaN,2.0,14,...,NaN,NaN,NaN,NaN,,1,NaN,2.0,121.27014,NaN

In [ ]:
# 3. Guardamos la información en los atributos (attrs) del DataFrame
enapres2020_1.attrs['value_labels'] = labels_enapres2020_1
enapres2020_1.attrs['var_labels'] = var_labels_enapres

In [ ]:
enapres2020_1.attrs[ 'value_labels' ]

{'TSELV': {1.0: 'Urbano', 4.0: 'SemiRural', 5.0: 'Rural'},
 'VIVREM': {1.0: 'Si', 2.0: 'No'},
 'AREA': {1.0: 'URBANO', 2.0: 'RURAL'},
 'RESFIN': {1.0: 'Completa', 2.0: 'Incompleta'},
 'P101': {1.0: 'Casa independiente',
  2.0: 'Departamento en edificio',
  3.0: 'Vivienda en quinta',
  4.0: 'Vivienda en casa de vecindad (callejón, solar o corralón)',
  5.0: 'Choza o cabaña',
  6.0: 'Vivienda improvisada',
  7.0: 'Local no destinado para habitación humana',
  8.0: 'Otro(Especifique)'},
 'P102A': {1.0: 'Ladrillo o bloque de cemento?',
  2.0: 'Piedra o sillar con cal o cemento?',
  3.0: 'Adobe?',
  4.0: 'Tapia?',
  5.0: 'Quincha (caña con barro)?',
  6.0: 'Piedra con barro?',
  7.0: ' Madera (pona, tornillo, etc.)?',
  8.0: 'Tripley/ Calamina/ Estera?',
  9.0: 'Otro material?'},
 'P103': {1.0: '¿Parquet o madera pulida?',
  2.0: '¿Láminas asfálticas, vinílicos o similares?',
  3.0: '¿Losetas, terrazos o similares?',
  4.0: '¿Madera (pona, tornillo, etc.)?',
  5.0: '¿Cemento?',
  6.0: '¿Tierra?',
  7.0: '¿Otro(Especifique)?'},
 'P104B': {1.0: '¿Concreto armado?',
  2.0: '¿Madera?',
  3.0: '¿Tejas?',
  4.0: '¿Planchas de calamina, fibra de cemento o similares?',
  5.0: 'Caña o estera con torta de barro o cemento?',
  6.0: 'Tripley/ estera/ carrizo?',
  7.0: 'Paja, hojas de palmera y similares.?',
  8.0: 'Otro material'},
 'P106': {1.0: '¿Alquilada?',
  2.0: '¿Propia, totalmente pagada?',
  3.0: '¿Propia, por invasión?',
  4.0: '¿Propia, comprándola a plazos?',
  5.0: '¿Cedida por otro hogar?',
  6.0: '¿Cedida por el centro de trabajo?',
  7.0: '¿Cedida por otra institución?',
  8.0: '¿Otra?(Especifique)'},
 'P106A': {1.0: 'Hasta el 2004',
  2.0: '2005',
  3.0: '2006',
  4.0: '2007',
  5.0: '2008',
  6.0: '2009',
  7.0: '2010',
  8.0: '2011',
  9.0: '2012',
  10.0: '2013',
  11.0: '2014',
  12.0: '2015',
  13.0: '2016',
  14.0: '2017',
  15.0: '2018',
  16.0: '2019',
  17.0: '2020'},
 'P107': {1.0: 'Si', 2.0: 'No', 3.0: 'NO SABE'},
 'P107A': {1.0: 'Título de Propiedad',
  2.0: 'Sentencia Judicial',
  3.0: 'Escritura Pública',
  4.0: 'Contrato de Compra-Venta',
  5.0: 'Minuta',
  6.0: 'Documento de Posesión',
  7.0: 'Otro(Especifique)'},
 'P107B': {1.0: 'COFOPRI',
  2.0: 'Municipalidad',
  3.0: 'Juez/a',
  4.0: 'Notaría',
  5.0: 'Otro(Especifique)',
  6.0: 'NINGUNO'},
 'P107C': {1.0: 'Si', 2.0: 'No'},
 'P108': {1.0: 'Si', 2.0: 'No', 3.0: 'NO SABE'},
 'P108_1': {1.0: 'Desconocía que tenía que inscribirlo en los Registros Públicos',
  2.0: 'Los costos para tramitar son elevados',
  3.0: 'El trámite es engorroso',
  4.0: 'Los impuestos son elevados',
  5.0: 'Otro(Especifique)'},
 'P108A': {1.0: 'Si', 2.0: 'No', 3.0: 'NO SABE'},
 'P108B': {1.0: 'Desconocía que tenía que inscribirlo en los Registros Públicos',
  2.0: 'Los costos para tramitar son elevados',
  3.0: 'El trámite es engorroso',
  4.0: 'Los impuestos son elevados',
  5.0: 'Otro(Especifique)'},
 'P109': {1.0: 'Si', 2.0: 'No'},
 'P110A': {1.0: 'Si', 2.0: 'No'},
 'P111A': {1.0: 'Si', 2.0: 'No'},
 'P112_1': {1.0: 'Si', 2.0: 'No'},
 'P113B_1_1': {0.0: 'Pase', 1.0: 'La Comisaria (Policia Nacional del Peru)?'},
 'P113B_1_2': {0.0: 'Pase', 1.0: 'El Ministerio Publico o Fiscalia?'},
 'P113B_1_3': {0.0: 'Pase', 1.0: 'Otro?'},
 'P117_1': {1.0: 'Si', 2.0: 'No'},
 'P118_1': {1.0: 'Comisaría (Policía Nacional del Perú)',
  2.0: 'Ministerio Público o Fiscalía',
  3.0: 'Otro(Especifique)'},
 'P119_1': {1.0: 'Está en trámite',
  2.0: 'No sucedió nada',
  3.0: 'Recuperó sus bienes y se detuvo al delincuente',
  4.0: 'Solo recuperó sus bienes',
  5.0: 'Se detuvo al delincuente',
  6.0: 'Otro(Especifique)'},
 'P121_1': {1.0: 'Por miedo a represalias del agresor/a',
  2.0: 'Es una pérdida de tiempo',
  3.0: 'Desconfía de la Policía',
  4.0: 'No se consumó el hecho',
  5.0: 'Delito de poca importancia',
  6.0: 'Desconoce al delincuente',
  7.0: 'Otro(Especifique)'},
 'P115_1': {1.0: 'Si', 2.0: 'No', 3.0: 'NO SABE'},
 'P116_1_1': {0.0: 'Pase',
  1.0: 'Armas de fuego de mano (revólver, pistola u otro)'},
 'P116_1_2': {0.0: 'Pase',
  1.0: 'Armas de fuego largo (escopeta, rifle, ametralladora)'},
 'P116_1_3': {0.0: 'Pase',
  1.0: 'Arma blanca (cuchillo,objeto punzo cortante)'},
 'P116_1_4': {0.0: 'Pase', 1.0: 'Objetos contundentes (palos, piedras, etc.)'},
 'P116_1_5': {0.0: 'Pase', 1.0: 'Otro'},
 'P121B_1': {1.0: 'Día laborable de lunes a viernes?',
  2.0: 'Fin de semana?',
  3.0: 'Día feriado?',
  4.0: 'NO RECUERDA',
  5.0: 'NO SABE'},
 'P121C_1': {1.0: 'Si', 2.0: 'No', 3.0: 'No recuerda', 4.0: 'NO SABE'},
 'P121D_1_1': {1.0: 'Pase', 2.0: 'Auto/camioneta'},
 'P121D_1_2': {1.0: 'Pase', 2.0: 'Motocicleta'},
 'P121D_1_3': {1.0: 'Pase', 2.0: 'Mototaxi/Mototriciclo'},
 'P121D_1_4': {1.0: 'Pase', 2.0: 'Bicicleta'},
 'P121D_1_5': {1.0: 'Pase', 2.0: 'Otro'},
 'P112_2': {1.0: 'Si', 2.0: 'No'},
 'P113B_2_1': {0.0: 'Pase', 1.0: 'La Comisaria (Policia Nacional del Peru)?'},
 'P113B_2_2': {0.0: 'Pase', 1.0: 'El Ministerio Publico o Fiscalia?'},
 'P113B_2_3': {0.0: 'Pase', 1.0: 'Otro?'},
 'P117_2': {1.0: 'Si', 2.0: 'No'},
 'P118_2': {1.0: 'Comisaría (Policía Nacional del Perú)',
  2.0: 'Ministerio Público o Fiscalía',
  3.0: 'Otro(Especifique)'},
 'P119_2': {1.0: 'Está en trámite',
  2.0: 'No sucedió nada',
  3.0: 'Recuperó sus bienes y se detuvo al delincuente',
  4.0: 'Solo recuperó sus bienes',
  5.0: 'Se detuvo al delincuente',
  6.0: 'Otro(Especifique)'},
 'P121_2': {1.0: 'Por miedo a represalias del agresor/a',
  2.0: 'Es una pérdida de tiempo',
  3.0: 'Desconfía de la Policía',
  4.0: 'No se consumó el hecho',
  5.0: 'Delito de poca importancia',
  6.0: 'Desconoce al delincuente',
  7.0: 'Otro(Especifique)'},
 'P115_2': {1.0: 'Si', 2.0: 'No', 3.0: 'NO SABE'},
 'P116_2_1': {0.0: 'Pase',
  1.0: 'Armas de fuego de mano (revólver, pistola u otro)'},
 'P116_2_2': {0.0: 'Pase',
  1.0: 'Armas de fuego largo (escopeta, rifle, ametralladora)'},
 'P116_2_3': {0.0: 'Pase',
  1.0: 'Arma blanca (cuchillo,objeto punzo cortante)'},
 'P116_2_4': {0.0: 'Pase', 1.0: 'Objetos contundentes (palos, piedras, etc.)'},
 'P116_2_5': {0.0: 'Pase', 1.0: 'Otro'},
 'P121B_2': {1.0: 'Día laborable de lunes a viernes?',
  2.0: 'Fin de semana?',
  3.0: 'Día feriado?',
  4.0: 'NO RECUERDA',
  5.0: 'NO SABE'},
 'P121C_2': {1.0: 'Si', 2.0: 'No', 3.0: 'No recuerda', 4.0: 'NO SABE'},
 'P121D_2_1': {1.0: 'Pase', 2.0: 'Auto/camioneta'},
 'P121D_2_2': {1.0: 'Pase', 2.0: 'Motocicleta'},
 'P121D_2_3': {1.0: 'Pase', 2.0: 'Mototaxi/Mototriciclo'},
 'P121D_2_4': {1.0: 'Pase', 2.0: 'Bicicleta'},
 'P121D_2_5': {1.0: 'Pase', 2.0: 'Otro'},
 'P122A_1': {1.0: 'Si', 2.0: 'No', 3.0: 'NO SABE'},
 'P122A_2': {1.0: 'Si', 2.0: 'No', 3.0: 'NO SABE'},
 'P122A_3': {1.0: 'Si', 2.0: 'No', 3.0: 'NO SABE'},
 'P122A_4': {1.0: 'Si', 2.0: 'No', 3.0: 'NO SABE'},
 'P122A_5': {1.0: 'Si', 2.0: 'No', 3.0: 'NO SABE'},
 'P122A_6': {1.0: 'Si', 2.0: 'No'},
 'P122C_1': {1.0: 'Si', 2.0: 'No'},
 'P122C_2': {1.0: 'Si', 2.0: 'No'},
 'P122C_3': {1.0: 'Si', 2.0: 'No'},
 'P122C_4': {1.0: 'Si', 2.0: 'No'},
 'P122C_5': {1.0: 'Si', 2.0: 'No'},
 'P122C_6': {1.0: 'Si', 2.0: 'No'},
 'P122D_1': {1.0: 'Si', 2.0: 'No', 3.0: 'NO SABE'},
 'P122D_2': {1.0: 'Si', 2.0: 'No', 3.0: 'NO SABE'},
 'P122D_3': {1.0: 'Si', 2.0: 'No', 3.0: 'NO SABE'},
 'P122D_4': {1.0: 'Si', 2.0: 'No', 3.0: 'NO SABE'},
 'P122D_5': {1.0: 'Si', 2.0: 'No', 3.0: 'NO SABE'},
 'P122D_6': {1.0: 'Si', 2.0: 'No', 3.0: 'NO SABE'},
 'P122D_7': {1.0: 'Si', 2.0: 'No', 3.0: 'NO SABE'},
 'P122D_8': {1.0: 'Si', 2.0: 'No'},
 'P122F_1': {1.0: 'Si', 2.0: 'No'},
 'P122F_2': {1.0: 'Si', 2.0: 'No'},
 'P122F_3': {1.0: 'Si', 2.0: 'No'},
 'P122F_4': {1.0: 'Si', 2.0: 'No'},
 'P122F_5': {1.0: 'Si', 2.0: 'No'},
 'P122F_6': {1.0: 'Si', 2.0: 'No'},
 'P122F_7': {1.0: 'Si', 2.0: 'No'},
 'P122F_8': {1.0: 'Si', 2.0: 'No'},
 'P123': {1.0: 'Si', 2.0: 'No'},
 'P124': {1.0: 'Si', 2.0: 'No'},
 'P125': {1.0: 'Si', 2.0: 'No'},
 'P126': {1.0: 'Si', 2.0: 'No', 3.0: 'NO SABE'},
 'P127_1': {0.0: 'Pase', 1.0: 'Electricidad'},
 'P127_2': {0.0: 'Pase', 1.0: 'Petroleo/ Gas (lámpara)'},
 'P127_3': {0.0: 'Pase', 1.0: 'vela'},
 'P127_4': {0.0: 'Pase', 1.0: 'Generador'},
 'P127_5': {0.0: 'Pase', 1.0: 'Panel solar'},
 'P127_6': {0.0: 'Pase', 1.0: 'otro'},
 'P128A_1': {0.0: 'Pase', 1.0: 'Electricidad?'},
 'P128A_2': {0.0: 'Pase', 1.0: 'Gas (balón GLP)?'},
 'P128A_3': {0.0: 'Pase', 1.0: 'Gas natural (sistema de tuberías)?'},
 'P128A_4': {0.0: 'Pase', 1.0: 'Carbón?'},
 'P128A_5': {0.0: 'Pase', 1.0: 'Leña?'},
 'P128A_6': {0.0: 'Pase', 1.0: 'Bosta, estiércol?'},
 'P128A_7': {0.0: 'Pase', 1.0: 'Otro'},
 'P128A_8': {0.0: 'Pase', 1.0: 'NO COCINAN'},
 'P128A_O': {'0': 'Pase', '1': 'OTRO/ESPECIFIQUE'},
 'P129G': {1.0: '¿Red pública dentro de la vivienda?',
  2.0: '¿Red pública fuera de la vivienda, pero dentro de la edificación?',
  3.0: 'Pilón o pileta de uso público?',
  4.0: '¿Camión-cisterna u otro similar?',
  5.0: 'Pozo (agua subterranea)?',
  6.0: 'Manantial o puquio?',
  7.0: 'Rio, acequia, lago, laguna?',
  8.0: '¿Otro?'},
 'P129B': {1.0: 'Si', 2.0: 'No'},
 'P129C': {1.0: 'Mayor o igual a 0,5 mg Seguro',
  2.0: 'De 0,1 mg/l a menos de 0,5 mg/l Inadecuada dosificación de cloro',
  3.0: '0,0 mg/l sin cloro',
  4.0: 'No se realizó la prueba'},
 'P129D_1': {0.0: 'Pase', 1.0: 'No se realizo la prueba'},
 'P129E': {1.0: 'El funcionario de la encuesta', 2.0: 'El informante'},
 'P129F': {1.0: '¿Grifo o caño?',
  2.0: '¿Cilindro de metal?',
  3.0: '¿Balde o batea de plástico?',
  4.0: '¿Tanque (sin filtro)?',
  5.0: '¿Tanque (con filtro)?',
  6.0: '¿Bidón, botella, etc.?',
  7.0: '¿Otro?'},
 'P130': {1.0: 'Si', 2.0: 'No'},
 'P131_1': {0.0: 'Pase', 1.0: 'Cocinar'},
 'P131_2': {0.0: 'Pase', 1.0: 'Aseo personal'},
 'P131_3': {0.0: 'Pase', 1.0: 'Lavar la ropa'},
 'P131_4': {0.0: 'Pase', 1.0: 'Regar el huerto o chacra'},
 'P131_5': {0.0: 'Pase', 1.0: 'Dar de beber a los animales domésticos'},
 'P131_6': {0.0: 'Pase', 1.0: 'Dar de beber a los animales crianza'},
 'P131_7': {0.0: 'Pase', 1.0: 'Otro'},
 'P131A': {1.0: 'Si', 2.0: 'No', 3.0: 'NO SABE'},
 'P131B': {1.0: '¿Diaria?',
  2.0: '¿Interdiaria?',
  3.0: '¿Semanal?',
  4.0: '¿Quincenal?',
  5.0: '¿Mensual?',
  6.0: '¿Anual?',
  7.0: '¿Otro?'},
 'P131C_B': {1.0: 'No sabe'},
 'P131D': {1.0: 'Junta Administradora de los Servicios de Saneamiento (JASS)',
  2.0: 'Otra organización comunal formada para tal fin',
  3.0: 'Municipalidad',
  4.0: 'Empresa prestadora de servicios (EPS)',
  5.0: 'Otro'},
 'P132': {1.0: 'Si', 2.0: 'No', 3.0: 'NO ACCEDIÓ'},
 'P133': {1.0: 'Si', 2.0: 'No'},
 'P134': {1.0: 'Si', 2.0: 'No'},
 'P135': {1.0: 'Si', 2.0: 'No', 3.0: 'NO ACCEDIÓ'},
 'P136': {1.0: 'Si', 2.0: 'No'},
 'P137': {1.0: 'Recipiente con caño en la parte inferior',
  2.0: 'Vasija con asa o mango largo',
  3.0: 'Vasija con asa o mango corto',
  4.0: 'Vasija sin asa',
  5.0: 'De forma directa (verter el agua directamente a la vasija)',
  6.0: 'Otra'},
 'P138_1': {1.0: 'Si', 2.0: 'No'},
 'P138_2': {1.0: 'Si', 2.0: 'No'},
 'P138_3': {1.0: 'Si', 2.0: 'No'},
 'P139_1': {0.0: 'Pase', 1.0: 'Antes de comer'},
 'P139_2': {0.0: 'Pase', 1.0: 'Antes de preparar los alimentos'},
 'P139_3': {0.0: 'Pase', 1.0: 'Despues de defecar'},
 'P139_4': {0.0: 'Pase', 1.0: 'Otro'},
 'P140_1': {1.0: 'Si', 2.0: 'No'},
 'P140_2': {1.0: 'Si', 2.0: 'No'},
 'P140_3': {1.0: 'Si', 2.0: 'No'},
 'P141_1': {0.0: 'Pase', 1.0: 'ONG'},
 'P141_2': {0.0: 'Pase', 1.0: 'MINISTERIO DE VIVIENDA'},
 'P141_3': {0.0: 'Pase', 1.0: 'FONCODES'},
 'P141_4': {0.0: 'Pase', 1.0: 'MINSA'},
 'P141_5': {0.0: 'Pase', 1.0: 'MINEDU'},
 'P141_6': {0.0: 'Pase', 1.0: 'MUNICIPALIDAD'},
 'P141_7': {0.0: 'Pase', 1.0: 'OTRA'},
 'P142A': {1.0: '¿Red pública de desagüe dentro de la vivienda?',
  2.0: '¿Red pública de desagüe fuera de la vivienda, pero dentro de la edificación?',
  3.0: '¿Letrina?',
  4.0: 'Pozo séptico, tanque séptico  o biodigestor?',
  5.0: 'Pozo ciego o negro?',
  6.0: 'Río, acequia o canal o similar?',
  7.0: 'Campo abierto o al aire libre?',
  8.0: 'Otro?'},
 'P143': {1.0: 'Si', 2.0: 'No'},
 'P144': {1.0: 'Arrastre hidráulico',
  2.0: 'Hoyo seco',
  3.0: 'Compostera seca',
  4.0: 'Compostera húmeda'},
 'P146': {3.0: 'Letrina', 4.0: 'Pozo séptico', 5.0: 'Pozo ciego o negro'},
 'P147A_1': {1.0: 'Si', 2.0: 'No'},
 'P147A_2': {1.0: 'Si', 2.0: 'No'},
 'P147A_3': {1.0: 'Si', 2.0: 'No'},
 'P147A_4': {1.0: 'Si', 2.0: 'No'},
 'P147A_5': {1.0: 'Si', 2.0: 'No'},
 'P157': {1.0: 'Si', 2.0: 'No'},
 'P158': {1.0: 'Muy malo', 2.0: 'Malo', 4.0: 'Bueno', 5.0: 'Muy bueno'},
 'P159': {1.0: 'Interrupciones en plena llamada',
  2.0: 'No se escucha bien / No me escuchan bien',
  3.0: 'Los reclamos demoran más de 7 días en ser atendidos',
  4.0: 'Poca disponibilidad de tarjetas',
  5.0: 'Centros de pago alejados',
  6.0: 'Costo elevado',
  7.0: 'Otro'},
 'P161_1': {1.0: 'Si', 2.0: 'No'},
 'P161A_1': {1.0: 'Malo', 3.0: 'Bueno', 4.0: 'No sabe'},
 'P161_2': {1.0: 'Si', 2.0: 'No'},
 'P161A_2': {1.0: 'Malo', 3.0: 'Bueno', 4.0: 'No sabe'},
 'P161_3': {1.0: 'Si', 2.0: 'No'},
 'P161A_3': {1.0: 'Malo', 3.0: 'Bueno', 4.0: 'No sabe'},
 'P161_4': {1.0: 'Si', 2.0: 'No'},
 'P161A_4': {1.0: 'Malo', 3.0: 'Bueno', 4.0: 'No sabe', 5.0: 'No existe'},
 'P162_1': {1.0: 'Si',
  2.0: 'No',
  3.0: 'No sabe',
  4.0: 'No existe transporte público'},
 'P162_2': {1.0: 'Si',
  2.0: 'No',
  3.0: 'No sabe',
  4.0: 'No existe transporte público'},
 'P163_1': {0.0: 'Pase', 1.0: 'A PIE'},
 'P165_1': {1.0: 'Camino de herradura?',
  2.0: 'Camino vecinal (carrozable)?',
  3.0: 'Carretera?'},
 'P163_2': {0.0: 'Pase', 1.0: 'ACEMILA'},
 'P165_2': {1.0: 'Camino de herradura?',
  2.0: 'Camino vecinal (carrozable)?',
  3.0: 'Carretera?'},
 'P163_3': {0.0: 'Pase', 1.0: 'BICICLETA, TRICICLO'},
 'P165_3': {1.0: 'Camino de herradura?',
  2.0: 'Camino vecinal (carrozable)?',
  3.0: 'Carretera?'},
 'P163_4': {0.0: 'Pase', 1.0: 'MOTO, MOTOTAXI, ETC'},
 'P165_4': {1.0: 'Camino de herradura?',
  2.0: 'Camino vecinal (carrozable)?',
  3.0: 'Carretera?'},
 'P163_5': {0.0: 'Pase', 1.0: 'AUTO, CAMIONETA, ETC'},
 'P165_5': {2.0: 'Camino vecinal (carrozable)?', 3.0: 'Carretera?'},
 'P163_6': {0.0: 'Pase', 1.0: 'CAMIONETA RURAL, OMNIBUS, ETC'},
 'P165_6': {2.0: 'Camino vecinal (carrozable)?', 3.0: 'Carretera?'},
 'P163_7': {0.0: 'Pase', 1.0: 'BOTE, LANCHA, ETC. ( ACUATICO CON MOTOR)'},
 'P165_7': {4.0: 'Río o lago?'},
 'P163_8': {0.0: 'Pase', 1.0: 'CANOA, BALSA, ETC. ( ACUATICO SIN MOTOR)'},
 'P165_8': {4.0: 'Río o lago?'},
 'P163_9': {0.0: 'Pase', 1.0: 'NO ACUDE AL MAS CERCANO'},
 'P163_10': {0.0: 'Pase', 1.0: 'NO ACUDE AL ESTABLECIMIENTO DE SALUD'},
 'P166A_1': {0.0: 'Pase', 1.0: 'A PIE'},
 'P168A_1': {1.0: 'Camino de herradura?',
  2.0: 'Camino vecinal (carrozable)?',
  3.0: 'Carretera?'},
 'P166A_2': {0.0: 'Pase', 1.0: 'ACEMILA'},
 'P168A_2': {1.0: 'Camino de herradura?',
  2.0: 'Camino vecinal (carrozable)?',
  3.0: 'Carretera?'},
 'P166A_3': {0.0: 'Pase', 1.0: 'BICICLETA, TRICICLO'},
 'P168A_3': {1.0: 'Camino de herradura?',
  2.0: 'Camino vecinal (carrozable)?',
  3.0: 'Carretera?'},
 'P166A_4': {0.0: 'Pase', 1.0: 'MOTO, MOTOTAXI, ETC'},
 'P168A_4': {1.0: 'Camino de herradura?',
  2.0: 'Camino vecinal (carrozable)?',
  3.0: 'Carretera?'},
 'P166A_5': {0.0: 'Pase', 1.0: 'AUTO, CAMIONETA, ETC'},
 'P168A_5': {2.0: 'Camino vecinal (carrozable)?', 3.0: 'Carretera?'},
 'P166A_6': {0.0: 'Pase', 1.0: 'CAMIONETA RURAL, OMNIBUS, ETC'},
 'P168A_6': {2.0: 'Camino vecinal (carrozable)?', 3.0: 'Carretera?'},
 'P166A_7': {0.0: 'Pase', 1.0: ' BOTE, LANCHA, ETC. ( ACUATICO CON MOTOR)'},
 'P168A_7': {4.0: 'Río o lago?'},
 'P166A_8': {0.0: 'Pase', 1.0: 'CANOA, BALSA, ETC. ( ACUATICO SIN MOTOR)'},
 'P168A_8': {4.0: 'Río o lago?'},
 'P166A_9': {0.0: 'Pase', 1.0: 'NO ACUDE'},
 'P172B_1': {1.0: 'Si', 2.0: 'No'},
 'P172C_1': {1.0: ' Muy insatisfecho/a?',
  2.0: 'Insatisfecho/a?',
  3.0: 'Satisfecho/a?',
  4.0: 'Muy satisfecho/a?'},
 'P172C_2': {1.0: ' Muy insatisfecho/a?',
  2.0: 'Insatisfecho/a?',
  3.0: 'Satisfecho/a?',
  4.0: 'Muy satisfecho/a?'},
 'P172D': {1.0: 'Si', 2.0: 'No'},
 'P172E_1': {1.0: 'Si', 2.0: 'No'},
 'P172F_1_1': {0.0: 'Pase', 1.0: ' Directamente a la municipalidad'},
 'P172F_1_2': {0.0: 'Pase',
  1.0: ' A una asociación de recicladores formalizados'},
 'P172F_1_3': {0.0: 'Pase', 1.0: '  A un reciclador informal'},
 'P172F_1_4': {0.0: 'Pase', 1.0: '  Los traslado a un punto de acopio'},
 'P172F_1_5': {1.0: 'Uso/manejo directo por parte del generador/a'},
 'P172F_1_6': {0.0: 'Pase', 1.0: ' Otro'},
 'P172E_2': {1.0: 'Si', 2.0: 'No'},
 'P172F_2_1': {0.0: 'Pase', 1.0: ' Directamente a la municipalidad'},
 'P172F_2_2': {0.0: 'Pase',
  1.0: ' A una asociación de recicladores formalizados'},
 'P172F_2_3': {0.0: 'Pase', 1.0: '  A un reciclador informal'},
 'P172F_2_4': {0.0: 'Pase', 1.0: '  Los traslado a un punto de acopio'},
 'P172F_2_5': {1.0: 'Uso/manejo directo por parte del generador/a'},
 'P172F_2_6': {0.0: 'Pase', 1.0: ' Otro'},
 'P172E_3': {1.0: 'Si', 2.0: 'No'},
 'P172F_3_1': {0.0: 'Pase', 1.0: ' Directamente a la municipalidad'},
 'P172F_3_2': {0.0: 'Pase',
  1.0: ' A una asociación de recicladores formalizados'},
 'P172F_3_3': {0.0: 'Pase', 1.0: '  A un reciclador informal'},
 'P172F_3_4': {0.0: 'Pase', 1.0: '  Los traslado a un punto de acopio'},
 'P172F_3_5': {1.0: 'Uso/manejo directo por parte del generador/a'},
 'P172F_3_6': {0.0: 'Pase', 1.0: ' Otro'},
 'P172E_4': {1.0: 'Si', 2.0: 'No'},
 'P172F_4_1': {0.0: 'Pase', 1.0: ' Directamente a la municipalidad'},
 'P172F_4_2': {0.0: 'Pase',
  1.0: ' A una asociación de recicladores formalizados'},
 'P172F_4_3': {0.0: 'Pase', 1.0: '  A un reciclador informal'},
 'P172F_4_4': {0.0: 'Pase', 1.0: '  Los traslado a un punto de acopio'},
 'P172F_4_5': {1.0: 'Uso/manejo directo por parte del generador/a'},
 'P172F_4_6': {0.0: 'Pase', 1.0: ' Otro'},
 'P172E_5': {1.0: 'Si', 2.0: 'No'},
 'P172F_5_1': {0.0: 'Pase', 1.0: ' Directamente a la municipalidad'},
 'P172F_5_2': {0.0: 'Pase',
  1.0: ' A una asociación de recicladores formalizados'},
 'P172F_5_3': {0.0: 'Pase', 1.0: '  A un reciclador informal'},
 'P172F_5_4': {0.0: 'Pase', 1.0: '  Los traslado a un punto de acopio'},
 'P172F_5_5': {1.0: 'Uso/manejo directo por parte del generador/a'},
 'P172F_5_6': {0.0: 'Pase', 1.0: ' Otro'},
 'P172E_6': {1.0: 'Si', 2.0: 'No'},
 'P172F_6_1': {0.0: 'Pase', 1.0: ' Directamente a la municipalidad'},
 'P172F_6_2': {0.0: 'Pase',
  1.0: ' A una asociación de recicladores formalizados'},
 'P172F_6_3': {0.0: 'Pase', 1.0: '  A un reciclador informal'},
 'P172F_6_4': {0.0: 'Pase', 1.0: '  Los traslado a un punto de acopio'},
 'P172F_6_5': {1.0: 'Uso/manejo directo por parte del generador/a'},
 'P172F_6_6': {0.0: 'Pase', 1.0: ' Otro'},
 'P172E_7': {1.0: 'Si', 2.0: 'No'},
 'P172F_7_1': {0.0: 'Pase', 1.0: ' Directamente a la municipalidad'},
 'P172F_7_2': {0.0: 'Pase',
  1.0: ' A una asociación de recicladores formalizados'},
 'P172F_7_3': {0.0: 'Pase', 1.0: '  A un reciclador informal'},
 'P172F_7_4': {0.0: 'Pase', 1.0: '  Los traslado a un punto de acopio'},
 'P172F_7_5': {1.0: 'Uso/manejo directo por parte del generador/a'},
 'P172F_7_6': {0.0: 'Pase', 1.0: ' Otro'},
 'P172G': {1.0: 'Si', 2.0: 'No'},
 'P172H_1': {0.0: 'Pase', 1.0: ' Municipalidad'},
 'P172H_2': {0.0: 'Pase', 1.0: ' Ministerio del Ambiente (MINAM)'},
 'P172H_3': {0.0: 'Pase',
  1.0: ' Empresa privada del recojo de basura en su distrito'},
 'P172H_4': {0.0: 'Pase', 1.0: ' Ministerio de Educación (MINEDU)'},
 'P172H_5': {0.0: 'Pase', 1.0: ' Ministerio de Educación (MINEDU)'},
 'P172H_6': {0.0: 'Pase', 1.0: ' Organismo no gubernamental (ONG)'},
 'P172H_7': {0.0: 'Pase', 1.0: ' Ministerio de Salud (MINSA)'},
 'P172H_8': {0.0: 'Pase', 1.0: ' Ministerio de Salud (MINSA)'},
 'P178_1': {1.0: 'Si', 2.0: 'No'},
 'P178_2': {1.0: 'Si', 2.0: 'No'},
 'P178_3': {1.0: 'Si', 2.0: 'No'},
 'P178_4': {1.0: 'Si', 2.0: 'No'},
 'P178_5': {1.0: 'Si', 2.0: 'No'},
 'P178_6': {1.0: 'Si', 2.0: 'No'},
 'P178_7': {1.0: 'Si', 2.0: 'No'},
 'P179': {1.0: 'Si', 2.0: 'No', 3.0: 'NO SABE'},
 'P180_1': {0.0: 'Pase', 1.0: 'Otra'},
 'P180_2': {0.0: 'Pase', 1.0: 'Produce riesgo para el medio ambiente'},

In [ ]:
# Tamaño del DataFrame: número de filas y columnas
enapres2020_1.shape

(42153, 491)