# PANDAS Y DATAFRAMES

In [ ]:
!pip -q install pyreadstat # Lee archivos Stata, SPSS y SAS

- <a href='#1.'>I. `Pandas`</a>  
     - <a href='#1.1.'>1.1. Definición y Características</a>
     - <a href='#1.2.'>1.2. Generación de `Series`</a>
     - <a href='#1.3.'>1.3. `Series` vs `NumPy`</a>
     - <a href='#1.4.'>1.4. Indexar</a></a>
- <a href='#2.'>II. `DataFrames`</a>
     - <a href='#2.1.'>2.1. Generación de `DataFrames`</a>
     - <a href='#2.2.'>2.2. Indexing</a>
     - <a href='#2.3.'>2.3. Métodos Generales</a>
     - <a href='#2.4.'>2.4. Importando Data: GitHub</a>
     - <a href='#2.5.'>2.5. Importando Data: ENAPRES</a>

# <a id='1.'>I. `Pandas`</a>

## <a id='1.1.'>1.1. Definición y Características</a>

**DEFINICIÓN:**

* `Pandas` es una biblioteca de Python utilizada para trabajar con conjuntos de datos: vamos a llamarla cada vez que trabajamos con DataFrames.
* Es la librería más importante de aprender para limpiar, transforar y agregar datos.
* Como es externa, necesitamos importarla para trabajar en nuestro quehacer diario mediante la palabra clave `import`.

In [2]:
import pandas as pd
import numpy as np

* Ahora, el paquete de `Pandas` está referido como `pd` en lugar de Pandas.

**CARACTERÍSTICAS:**

* La primera estructura de datos de `Pandas` es una Serie, que es un arreglo unidimensional que puede contener cualquier tipo de datos, de manera similar a un ndarray.
* Tiene un índice (index) que le asigna una etiqueta a cada entrada. Por lo general, el índice se utiliza para etiquetar los datos.
* Contiene información sobre una sola característica (feature) de los datos.
* Un `Pandas Dataframe` son muchas Series.

## <a id='1.2.'>1.2. Generación de `Series`<a>

### De `lists` a `Series`:

In [ ]:
# Recordemos una lista de Python, vista la clase pasada:
list1 = [0.25, 0.5, 0.75, 1.0]
list1

[0.25, 0.5, 0.75, 1.0]

In [3]:
# Se puede decir que una Serie es una columna:
pd.Series([1, 5, 8, 9, 10])

0     1
1     5
2     8
3     9
4    10
dtype: int64

In [4]:
list2 =  [1, 1.5, 2, 2.5, 3]
list2

[1, 1.5, 2, 2.5, 3]

In [5]:
# Convertimos la lista en una Serie de Pandas:
data = pd.Series(list2)
data

0    1.0
1    1.5
2    2.0
3    2.5
4    3.0
dtype: float64

In [6]:
# Ya tenemos nuestros datos convertidos a Series
print(data)

0    1.0
1    1.5
2    2.0
3    2.5
4    3.0
dtype: float64

* **Una base de datos es un conjunto de Series.**
* Podemos convertir un Numpy y diccionarios a Series también.

### De `NumPy array` a `Series`:

In [10]:
# Veamos un ejemplo de un vector de Numpy, que es otra estructura de datos muy utilizada en Python
# La clase pasada vimos que un vector es una lista de números:
vector1 = np.array([10, 20, 1, 2, 
                    3, 4, 5, 6, 7, 10])
vector1

array([10, 20,  1,  2,  3,  4,  5,  6,  7, 10])

In [8]:
# Ahora convertimos el vector de Numpy a una Serie de Pandas:
series1 = pd.Series( vector1 )
series1

0    10
1    20
2     1
3     2
4     3
5     4
6     5
7     6
8     7
9    10
dtype: int32

In [ ]:
# Las Series de Pandas son más complejas que los vectores de Numpy, ya que permiten almacenar información adicional como el índice y el nombre de la Serie.
print(type(vector1))
print(type(series1))

<class 'numpy.ndarray'>
<class 'pandas.core.series.Series'>

### De `Dictionary` a `Series`:

In [11]:
population_dict= { 'California' : 38332521,
                    'Texas'      : 26448193,
                    'New York'   : 19651127,
                    'Florida'    : 19552860,
                    'Illinois'   : 12882135 }

In [12]:
# Vemos las llaves:
population_dict.keys()

dict_keys(['California', 'Texas', 'New York', 'Florida', 'Illinois'])

In [13]:
# Al convertirlo en Series, la indexación absorde las llaves.
# Por tanto, la indexación también puede tener texto. Sin embargo, no es lo ideal. Se recomienda números partiendo desde 0.
population = pd.Series( population_dict )
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

## <a id='1.3.'>1.3. `Series` vs `NumPy`</a>

* La diferencia esencial es la presencia del índice: mientras que el `Numpy Array` tiene un índice entero definido de forma implícita que se utiliza para acceder a los valores, los `Pandas Series` tienen un índice explícito asociado a los valores.

* El `index` (índice) no necesita ser un entero. Podemos usar `strings` (cadenas de texto).

In [14]:
# Creamos un vector de Numpy con valores del 5 al 20, con un paso de 2:
claudia = np.arange(5, 21, 2)
claudia

array([ 5,  7,  9, 11, 13, 15, 17, 19])

In [ ]:
# Convertimos el vector de Numpy a una Serie de Pandas, con un índice personalizado:
# Ahora la serie es de 3 en 3, y el índice es un nombre de persona.
math = pd.Series( np.arange(5.,21.,3.) , ['joyce','jeremy','ivan','marcy','daniel','franclin'])
math

joyce        5.0
jeremy       8.0
ivan        11.0
marcy       14.0
daniel      17.0
franclin    20.0
dtype: float64

In [16]:
# Creamos una serie del 5 al 15, de 3 en 3, con un índice personalizado:
info = np.arange(5 , 15 ,3.)
index_info =  ['joyce','jeremy','ivan','marcy']

In [17]:
# De los objetos creados anteriormente, podemos crear una Serie de Pandas con un índice personalizado y un nombre para la Serie:
# Students sería el nombre de la Serie, y el índice es el nombre de cada estudiante.
math_2 = pd.Series(  info , index_info,  name = "Students")
math_2

joyce      5.0
jeremy     8.0
ivan      11.0
marcy     14.0
Name: Students, dtype: float64

## <a id='1.4.'>1.4. Indexar</a>

* Indexar (o la indexación) en `Pandas` significa simplemente seleccionar filas y columnas particulares de datos de un DataFrame.
* También puede conocerse como Selección de Subconjuntos.

In [ ]:
# Veamos a data y population:
print(data)
print(population)

0    1.0
1    1.5
2    2.0
3    2.5
4    3.0
dtype: float64
California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [19]:
data[1]

1.5

In [ ]:
# En número, si quiero ir hasta un índice particular, tengo que hacer lo siguiente:
# Si quiero del 0 al 2, la indexación va hasta el 3.
# Siempre uno menos si estoy en números.
print( data[0:3] )

0    1.0
1    1.5
2    2.0
dtype: float64

In [21]:
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

* `dtype` es el tipo de data, no el tipo de objeto.
* Puede haber `int16`, `int32`, `int64` o `float64`. Eso importará cuando hagamos Deep Learning, cuando involucremos al decimal 20.

In [22]:
# Cuando es texto, la indexación sí incluye el último elemento
print( population['Texas':'Florida'] )

Texas       26448193
New York    19651127
Florida     19552860
dtype: int64

| Método 	| Definición 	|
| --- 	| --- 	|
| loc() 	|Obtiene filas (y/o columnas) con etiquetas (labels) particulares.<br> Acepta valores booleanos (`bool`) para el indexado. |
| iloc() 	| Obtiene filas (y/o columnas) en posiciones de enteros (integer locations). <br> No acepta valores booleanos (`bool`) para el indexado.|

* Obtener el valor de Nueva York:

In [23]:
# loc(): Con una etiqueta particular, obtenemos el valor de la Serie. En este caso, la población de New York.
population.loc[ "New York" ]

19651127

In [24]:
# iloc(): Con valores de indexación, obtenemos el valor de la Serie. En este caso, la población desde Texas hasta Illinois.
# Excluimos California por ser el primer elemento.
population.iloc[ 1:6 ]

Texas       26448193
New York    19651127
Florida     19552860
Illinois    12882135
dtype: int64

Replicate this excersice for `data` Series.

# <a id='2.'>II. `DataFrames`</a>

* Un `DataFrame` es una colección de múltiples Series. Puede pensarse como un arreglo bidimensional (2D), donde cada fila es un punto de datos (datapoint) independiente y cada columna es una característica (feature) de los datos. Las filas están etiquetadas con un índice (al igual que en una Series) y las columnas están etiquetadas en el atributo columns.

* Existen muchas formas diferentes de crear `DataFrames`: a partir de listas, diccionarios, etc.

* Usaremos `Pandas` para trabajar con `DataFrames`.

## <a id='2.1.'>2.1. Generación de `DataFrames`</a>
### De `lists` y `dict` a `DataFrame`:

In [61]:
# Notas de estudiantes (lista)
students = [ "Alejandro", "Pedro", "Ramiro", "Axel", "Juan" ]
math     = [ 15, 16, 10, 12, 13 ]
english  = [ 13, 9, 16, 14, 17 ]
art      = [ 12, 16, 15, 19, 10 ]

# Diccionario:
# A cada llave le asignamos una lista 
gradesA = {'Students':students, 'Math':math, 'English':english, 'Art':art}

In [63]:
gradesA

{'Students': ['Alejandro', 'Pedro', 'Ramiro', 'Axel', 'Juan'],
 'Math': [15, 16, 10, 12, 13],
 'English': [13, 9, 16, 14, 17],
 'Art': [12, 16, 15, 19, 10]}

In [64]:
# Convertimos el diccionario en un DataFrame de Pandas:
gradesA1 = pd.DataFrame(gradesA)
gradesA1

    Students  Math  English  Art
0  Alejandro    15       13   12
1      Pedro    16        9   16
2     Ramiro    10       16   15
3       Axel    12       14   19
4       Juan    13       17   10

## <a id='2.2.'>2.2. Indexing</a>

* Podemos utilizar los mismos métodos que en las `Series`: `iloc` y `loc`, seleccionando tanto columnas como filas.

In [83]:
# Otras notas de estudiantes (lista)
students = [ "Gissela", "Daniel", "Andres", "Sandra", "Rosalyn" ]
math     = [ 16, 14, 17, 17, 17 ]
english  = [ 16, 17, 19, 18, 15 ]
art      = [ 11, 17, 13, 14, 17 ]

# Diccionario
diplomado = {'Students':students, 'Math':math, 'English':english, 'Art':art}

# DataFrame:
gradesA1 = pd.DataFrame( diplomado )
gradesA1

  Students  Math  English  Art
0  Gissela    16       16   11
1   Daniel    14       17   17
2   Andres    17       19   13
3   Sandra    17       18   14
4  Rosalyn    17       15   17

In [84]:
# MÉTODO loc(): Con valores de indexación, obtenemos el valor de la Serie.
# En este caso, seleccionamos las filas que van desde el 0 hasta el 3 y las columnas de "Art" y "Students"
# Recordar que loc es un método porque está al costado del objeto y no al costado del alias de la librería (pd como Pandas, por ejemplo).
gradesA1.loc[ 0:3 ,  ["Art", "Students"] ]

   Art Students
0   11  Gissela
1   17   Daniel
2   13   Andres
3   14   Sandra

In [85]:
# Ahora seleccionamos todas las filas (:) y las columnas "Students", "English" y "Art".
gradesA1.loc[ :, ["Students", "English", "Art"] ]

  Students  English  Art
0  Gissela       16   11
1   Daniel       17   17
2   Andres       19   13
3   Sandra       18   14
4  Rosalyn       15   17

## <a id='2.3.'>2.3. Métodos Generales</a>

|Métodos|Descripción|
|------|-----------|
|columns()|Obtiene el nombre de las columnas.|
|sort_values()|Ordena según los valores a lo largo de cualquiera de los ejes.|
|sort_index()|Ordena según el índice.|
|head()|Muestra las primeras N observaciones.|
|drop( )| Elimina las entradas con la etiqueta o etiquetas especificadas.|
|append( )| Concatena dos o más Series.|
|drop_duplicates( )| Elimina los valores duplicados.|
|dropna( ) |Elimina las entradas nulas.|
|fillna( ) |Reemplaza las entradas nulas con un valor o estrategia especificada.|
|reset_index( )| Convierte el índice en una columna.|
|sample( ) |Extrae una entrada aleatoria.|
|shift( ) |Desplaza el índice.|
|unique( ) |Devuelve los valores únicos.|

In [69]:
# Veamos otro ejemplo, ahora con diccionarios:
deps = {
        'dep' : ['Lima', 'Piura', 'Tumbes', 'Cuzco', 'Ica', 'Puno'],
        'year': [ 2000, 2001, 2002, 2001, 2002, 2003 ],
        'pop' : [ 1.5, 1.7, 3.6, 2.4, 2.9, 3.2 ] 
        }
dep1 = pd.DataFrame( deps )
dep1

      dep  year  pop
0    Lima  2000  1.5
1   Piura  2001  1.7
2  Tumbes  2002  3.6
3   Cuzco  2001  2.4
4     Ica  2002  2.9
5    Puno  2003  3.2

* El método `sort_values` tiene muchos argumentos: `inlpace` es uno de ellos y por default es `False`.
* Por ello es importante explicitar cuando lo queremos `True`, para que los cambios tengan efecto en la data ahí mismo. 
* `inplace` = `True` quiere decir que haga efectivo los cambios ahí mismo y que chanques la data. Es razonable para no crear más objetos.

In [ ]:
# Quiero ordenarlo según la variable "dep" (departamento): usamos el método sort_values para ordenar.
# Se ordena alfabéticamente porque dep es chr, si fuera variable int se ordena de menor a mayor.
dep1.sort_values( ["dep"] , inplace=True, )
dep1

      dep  year  pop
3   Cuzco  2001  2.4
4     Ica  2002  2.9
0    Lima  2000  1.5
1   Piura  2001  1.7
5    Puno  2003  3.2
2  Tumbes  2002  3.6

In [ ]:
# ascending=False: ordena de mayor a menor, y en letras, de la Z a la A.
dep1.sort_values( ["dep"], inplace= True, ignore_index=True, ascending=False)
dep1

      dep  year  pop
0  Tumbes  2002  3.6
1    Puno  2003  3.2
2   Piura  2001  1.7
3    Lima  2000  1.5
4     Ica  2002  2.9
5   Cuzco  2001  2.4

In [71]:
# Recordemos el DataFrame de notas de estudiantes:
gradesA1

  Students  Math  English  Art
0  Gissela    16       16   11
1   Daniel    14       17   17
2   Andres    17       19   13
3   Sandra    17       18   14
4  Rosalyn    17       15   17

* Operaciones con DataFrames: Veamos los métodos en acción.

In [ ]:
# Suma de las columnas "Math" y "English" del DataFrame gradesA1:
gradesA1["Math"] + gradesA1["English"]

0    32
1    31
2    36
3    35
4    32
dtype: int64

In [ ]:
# Nueva columna
gradesA1['promedio'] = ( gradesA1['Math'] + gradesA1['English'] + gradesA1['Art'] ) / 3
gradesA1

  Students  Math  English  Art   promedio
0  Gissela    16       16   11  14.333333
1   Daniel    14       17   17  16.000000
2   Andres    17       19   13  16.333333
3   Sandra    17       18   14  16.333333
4  Rosalyn    17       15   17  16.333333

In [ ]:
# drop: Eliminar columnas o filas de un DataFrame 
# El parámetro axis=1 indica que buscamos una columna (axis=0 sería para filas).
# inplace = True significa que los cambios se aplican directamente al DataFrame original, sin necesidad de crear una copia.
gradesA1.drop("promedio", axis=1, inplace=True)
gradesA1

  Students  Math  English  Art
0  Gissela    16       16   11
1   Daniel    14       17   17
2   Andres    17       19   13
3   Sandra    17       18   14
4  Rosalyn    17       15   17

In [ ]:
# rename: Cambiar el nombre de una columna en un DataFrame
gradesA1.rename(columns={"Students": "Estudiantes"}, inplace=True)
gradesA1

  Estudiantes  Math  English  Art
0     Gissela    16       16   11
1      Daniel    14       17   17
2      Andres    17       19   13
3      Sandra    17       18   14
4     Rosalyn    17       15   17

In [ ]:
# iloc(): Con valores de indexación, obtenemos el valor de la Serie. 
# En este caso, el promedio de las columnas de los cursos en las posiciones 2, 3 y 4 (Math, English y Art) para cada estudiante.
# Mean Math & English
gradesA1.iloc[:, 2:4].mean(axis=1)

0    13.5
1    17.0
2    16.0
3    16.0
4    16.0
dtype: float64

In [ ]:
# head: Mostrar las primeras filas de un DataFrame. Por defecto, muestra las primeras 5 filas, pero podemos especificar cuántas queremos ver.
gradesA1.head(4)

  Estudiantes  Math  English  Art
0     Gissela    16       16   11
1      Daniel    14       17   17
2      Andres    17       19   13
3      Sandra    17       18   14

* Renombramos de nuevo la columna **Estudiantes** para no tener problemas con el código que sigue:
* Agregar nuevos datos con el método `concat()` de `Pandas`, usando las mismas columnas que el DataFrame original.

In [ ]:
# MÉTODO rename
# Formato: .rename(columns={"Columna antigua": "Columna nueva"}, inplace=True)
gradesA1.rename(columns={"Estudiantes": "Students"}, inplace=True)
gradesA1

  Students  Math  English  Art
0  Gissela    16       16   11
1   Daniel    14       17   17
2   Andres    17       19   13
3   Sandra    17       18   14
4  Rosalyn    17       15   17

In [ ]:
# Agregamos nueva data: gradesA2
# Nuevos estudiantes y sus notas en Math, English y Art
students = [ "Rebeca", "Xavi", "Cristiano", "Ronaldo", "Leo" ]
math     = [ 15, 18, 14, 7, 10 ]
english  = [ 18, 9, 11, 12, 20 ]
art      = [ 10, 16, 20, 19, 5 ]

# Dictionary
grades_A2 = {'Students':students, 'Math':math, 'English':english, 'Art':art}

# Convertimos el diccionario en un DataFrame de Pandas:
gradesA2 = pd.DataFrame( grades_A2 )
print( gradesA2 , "\n")

    Students  Math  English  Art
0     Rebeca    15       18   10
1       Xavi    18        9   16
2  Cristiano    14       11   20
3    Ronaldo     7       12   19
4        Leo    10       20    5

In [94]:
gradesA1

  Students  Math  English  Art
0  Gissela    16       16   11
1   Daniel    14       17   17
2   Andres    17       19   13
3   Sandra    17       18   14
4  Rosalyn    17       15   17

In [95]:
gradesA2

    Students  Math  English  Art
0     Rebeca    15       18   10
1       Xavi    18        9   16
2  Cristiano    14       11   20
3    Ronaldo     7       12   19
4        Leo    10       20    5

* Unimos ambos datos:

In [98]:
pd.concat( [gradesA1, gradesA2] , ignore_index=True)

    Students  Math  English  Art
0    Gissela    16       16   11
1     Daniel    14       17   17
2     Andres    17       19   13
3     Sandra    17       18   14
4    Rosalyn    17       15   17
5     Rebeca    15       18   10
6       Xavi    18        9   16
7  Cristiano    14       11   20
8    Ronaldo     7       12   19
9        Leo    10       20    5

In [ ]:
# Aquí vemos qué sucede si no colocamos ignore_index=True. 
# El índice se mantiene, y se repiten los índices de 0 a 4.
grades_total = pd.concat([gradesA1, gradesA2])
grades_total

    Students  Math  English  Art
0    Gissela    16       16   11
1     Daniel    14       17   17
2     Andres    17       19   13
3     Sandra    17       18   14
4    Rosalyn    17       15   17
0     Rebeca    15       18   10
1       Xavi    18        9   16
2  Cristiano    14       11   20
3    Ronaldo     7       12   19
4        Leo    10       20    5

In [101]:
# Ahora sí, con ignore_index=True, el índice se reinicia y se asigna un nuevo índice a cada fila del DataFrame resultante.
# copy() es para crear una copia del DataFrame resultante y evitar advertencias de Pandas sobre la modificación de un DataFrame que podría estar vinculado a otro.
grades_total = pd.concat([gradesA1, gradesA2], ignore_index=True).copy()
grades_total

    Students  Math  English  Art
0    Gissela    16       16   11
1     Daniel    14       17   17
2     Andres    17       19   13
3     Sandra    17       18   14
4    Rosalyn    17       15   17
5     Rebeca    15       18   10
6       Xavi    18        9   16
7  Cristiano    14       11   20
8    Ronaldo     7       12   19
9        Leo    10       20    5

* Si hay una columna con datos parciales en una columna, aparecerá "NaN" en los valores faltantes.

In [102]:
# Veamos otro ejemplo de DataFrame, ahora con información de autos:
cars = pd.DataFrame({
            'brands'    : [ 'hyundai', 'hyundai', 'kia', 'kia', 'kia' ] ,
            'model'     : [ 'sedan', 'sedan', 'sedan', 'truck', 'truck' ] ,
            'passengers': [ 4, 4, 5, 6, 8 ]
            })
cars

    brands  model  passengers
0  hyundai  sedan           4
1  hyundai  sedan           4
2      kia  sedan           5
3      kia  truck           6
4      kia  truck           8

In [ ]:
# Eliminamos duplicados de las columnas "brands" y "model" del DataFrame cars, dejando solo la primera ocurrencia de cada combinación única de estas columnas.
# Se quedan las combinaciones únicas de "brands" y "model": 
# * 0 hyuandai sedan
# * 2 kia sedan
# * 3 kia truck
cars.drop_duplicates(subset = [ "brands", "model"])

    brands  model  passengers
0  hyundai  sedan           4
2      kia  sedan           5
3      kia  truck           6

In [106]:
# Si queremos algo más habitual, lo mejor es restringir por columna.
# Usaremos "brands", por lo que ahora solo nos debe mostrar elementos únicos de la columna "brands"
cars_subset = cars.drop_duplicates(subset = [ 'brands' ])
cars_subset

    brands  model  passengers
0  hyundai  sedan           4
2      kia  sedan           5

In [ ]:
# Recordemos el DataFrame de notas de estudiantes:
grades_total

    Students  Math  English  Art
0    Gissela    16       16   11
1     Daniel    14       17   17
2     Andres    17       19   13
3     Sandra    17       18   14
4    Rosalyn    17       15   17
5     Rebeca    15       18   10
6       Xavi    18        9   16
7  Cristiano    14       11   20
8    Ronaldo     7       12   19
9        Leo    10       20    5

In [ ]:
# dropna
print( grades_total )

    Students  Math  English  Art
0    Gissela    16       16   11
1     Daniel    14       17   17
2     Andres    17       19   13
3     Sandra    17       18   14
4    Rosalyn    17       15   17
5     Rebeca    15       18   10
6       Xavi    18        9   16
7  Cristiano    14       11   20
8    Ronaldo     7       12   19
9        Leo    10       20    5

In [ ]:
# MÉTODO dropna(): Elimina las filas que contienen valores nulos (NaN) en el DataFrame.
# Sin embargo, no hay NAs, por lo que la columna permanece igual.
grades_total.dropna()

    Students  Math  English  Art
0    Gissela    16       16   11
1     Daniel    14       17   17
2     Andres    17       19   13
3     Sandra    17       18   14
4    Rosalyn    17       15   17
5     Rebeca    15       18   10
6       Xavi    18        9   16
7  Cristiano    14       11   20
8    Ronaldo     7       12   19
9        Leo    10       20    5

In [ ]:
# MÉTODO sample(): Devuelve una muestra aleatoria de filas del DataFrame.
grades_total.sample( n=3 )

    Students  Math  English  Art
9        Leo    10       20    5
7  Cristiano    14       11   20
4    Rosalyn    17       15   17

In [ ]:
# Ahora una muestra de 5 filas:
print( grades_total.sample(n = 5) )

  Students  Math  English  Art
5   Rebeca    15       18   10
9      Leo    10       20    5
1   Daniel    14       17   17
3   Sandra    17       18   14
4  Rosalyn    17       15   17

In [119]:
# Ahora una muestra del 20% de las filas del DataFrame, con una semilla aleatoria para reproducibilidad.
# La elección es aleatoria, por lo que cada vez que ejecutemos el código obtendremos resultados diferentes.
print( grades_total.sample( frac = 0.2, random_state=123 ), "\n")

  Students  Math  English  Art
4  Rosalyn    17       15   17
0  Gissela    16       16   11

## <a id='2.4.'>2.4. Importando datos: GitHub</a>

**INNOVATION GRAPH:**
* Contiene los repositorios por temática y país alrededor del mundo.

In [35]:
# URL del archivo CSV hospedado en GitHub (hacemos click en "Raw")
# Repositorios de Github de la página de Innovation Graph:
url = "https://raw.githubusercontent.com/github/innovationgraph/refs/heads/main/data/repositories.csv"

# Carga directa desde la URL
df = pd.read_csv(url)

# Muestra las primeras filas del DataFrame
df

      repositories iso2_code  year  quarter
0         30669781        US  2020        1
1         20179087        CN  2020        1
2         17912888        EU  2020        1
3          9254535        IN  2020        1
4          4171705        GB  2020        1
...            ...       ...   ...      ...
5630           231        AQ  2026        1
5631           219        MH  2026        1
5632           196        IO  2026        1
5633           161        PM  2026        1
5634           142        MS  2026        1

[5635 rows x 4 columns]

In [36]:
# Renombrar columnas:
df.rename(columns={"repositories": "num_repos"}, inplace=True)
df

      num_repos iso2_code  year  quarter
0      30669781        US  2020        1
1      20179087        CN  2020        1
2      17912888        EU  2020        1
3       9254535        IN  2020        1
4       4171705        GB  2020        1
...         ...       ...   ...      ...
5630        231        AQ  2026        1
5631        219        MH  2026        1
5632        196        IO  2026        1
5633        161        PM  2026        1
5634        142        MS  2026        1

[5635 rows x 4 columns]

In [37]:
# Seleccionar solo Perú:
# La idea es seleccionar la columna y colocar los valores que quiero encontrar.
# Para eso se crearon booleanos donde se seleccionarán los valores TRUE
# Traducción: En la base df, quiero los valores del df que son PE
df[df["iso2_code"] == "PE"]

      num_repos iso2_code  year  quarter
49       356948        PE  2020        1
263      391794        PE  2020        2
480      424103        PE  2020        3
698      456011        PE  2020        4
916      485312        PE  2021        1
1136     527124        PE  2021        2
1356     567869        PE  2021        3
1580     609800        PE  2021        4
1803     652580        PE  2022        1
2025     704939        PE  2022        2
2247     753704        PE  2022        3
2472     805264        PE  2022        4
2696     852209        PE  2023        1
2923     913172        PE  2023        2
3150     969559        PE  2023        3
3378    1021424        PE  2023        4
3604    1070001        PE  2024        1
3832    1138879        PE  2024        2
4058    1207493        PE  2024        3
4289    1280517        PE  2024        4
4518    1336842        PE  2025        1
4748    1439611        PE  2025        2
4979    1540677        PE  2025        3
5211    1648544        PE  2025        4
5442    1726117        PE  2026        1

In [38]:
# Si quiero dos países: Perú y Argentina
# Usamos un "o" (or) y paréntesis para cada condición
df[ (df["iso2_code"] == "PE") | (df["iso2_code"] == "AR") ]

      num_repos iso2_code  year  quarter
31       608445        AR  2020        1
49       356948        PE  2020        1
244      670189        AR  2020        2
263      391794        PE  2020        2
460      737110        AR  2020        3
480      424103        PE  2020        3
678      802976        AR  2020        4
698      456011        PE  2020        4
898      867545        AR  2021        1
916      485312        PE  2021        1
1118     965194        AR  2021        2
1136     527124        PE  2021        2
1340    1070330        AR  2021        3
1356     567869        PE  2021        3
1563    1180271        AR  2021        4
1580     609800        PE  2021        4
1785    1312481        AR  2022        1
1803     652580        PE  2022        1
2007    1514018        AR  2022        2
2025     704939        PE  2022        2
2231    1692345        AR  2022        3
2247     753704        PE  2022        3
2456    1827329        AR  2022        4
2472     805264        PE  2022        4
2681    1972535        AR  2023        1
2696     852209        PE  2023        1
2908    2158627        AR  2023        2
2923     913172        PE  2023        2
3135    2297445        AR  2023        3
3150     969559        PE  2023        3
3363    2456325        AR  2023        4
3378    1021424        PE  2023        4
3590    2557620        AR  2024        1
3604    1070001        PE  2024        1
3818    2695815        AR  2024        2
3832    1138879        PE  2024        2
4046    2816763        AR  2024        3
4058    1207493        PE  2024        3
4278    2910039        AR  2024        4
4289    1280517        PE  2024        4
4507    3003205        AR  2025        1
4518    1336842        PE  2025        1
4738    3158220        AR  2025        2
4748    1439611        PE  2025        2
4969    3309686        AR  2025        3
4979    1540677        PE  2025        3
5201    3471573        AR  2025        4
5211    1648544        PE  2025        4
5433    3598412        AR  2026        1
5442    1726117        PE  2026        1

In [39]:
# Quiero los códigos de los países de Sudamérica, que son: PE, AR, BR, CL, CO, EC, GY, PY, SR, UY y VE.
# Usamos el método isin() para seleccionar los valores que están en la lista de países sud
# Creamos lista:
south_america_codes = [
    "AR", "BO", "BR", "CL", "CO", "EC",
    "GY", "PY", "PE", "SR", "UY", "VE", "GF"
]

# Filter DataFrame
df_south_america = df[df["iso2_code"].isin(south_america_codes)]
df_south_america

      num_repos iso2_code  year  quarter
5       3602025        BR  2020        1
26       678828        CO  2020        1
31       608445        AR  2020        1
49       356948        PE  2020        1
50       353627        CL  2020        1
...         ...       ...   ...      ...
5493     309547        UY  2026        1
5508     163202        PY  2026        1
5576       9645        GY  2026        1
5582       7373        SR  2026        1
5594       4194        GF  2026        1

[325 rows x 4 columns]

In [40]:
# Queremos saber cuántas columnas y filas hay en DataFrame de países de Sudamérica:
df_south_america.shape

(325, 4)

In [42]:
# Podemos extraer columnas específicas
# Van dos corchetes porque estamos extrayendo varias columnas, y no una sola. Si fuera una sola columna, bastaría con un solo corchete.
# No chancamos la información, solo nos muestra el resultado.
# El corchete indica que es una lista.
df_south_america[["quarter", "year"]]

      quarter  year
5           1  2020
26          1  2020
31          1  2020
49          1  2020
50          1  2020
...       ...   ...
5493        1  2026
5508        1  2026
5576        1  2026
5582        1  2026
5594        1  2026

[325 rows x 2 columns]

In [43]:
# Eso implica que podemos reordenar las columnas:
# Con el siglo igual, ahora sí chanco el df
df_south_america = df_south_america[["iso2_code", "year", "quarter", "num_repos"]]
df_south_america

     iso2_code  year  quarter  num_repos
5           BR  2020        1    3602025
26          CO  2020        1     678828
31          AR  2020        1     608445
49          PE  2020        1     356948
50          CL  2020        1     353627
...        ...   ...      ...        ...
5493        UY  2026        1     309547
5508        PY  2026        1     163202
5576        GY  2026        1       9645
5582        SR  2026        1       7373
5594        GF  2026        1       4194

[325 rows x 4 columns]

In [44]:
# El index sigue siendo caótico, desordenado. Procedemos a ordenarlo y reiniciar el índice:
df_south_america.reset_index(inplace=True)
df_south_america

     index iso2_code  year  quarter  num_repos
0        5        BR  2020        1    3602025
1       26        CO  2020        1     678828
2       31        AR  2020        1     608445
3       49        PE  2020        1     356948
4       50        CL  2020        1     353627
..     ...       ...   ...      ...        ...
320   5493        UY  2026        1     309547
321   5508        PY  2026        1     163202
322   5576        GY  2026        1       9645
323   5582        SR  2026        1       7373
324   5594        GF  2026        1       4194

[325 rows x 5 columns]

In [ ]:
# Podemos eliminar o mantener la nueva columna index creada
# Decidimos eliminarla porque no es necesaria y solo ocupa espacio.
df_south_america.drop(columns=["index"], inplace=True)
df_south_america

    iso2_code  year  quarter  num_repos
0          BR  2020        1    3602025
1          CO  2020        1     678828
2          AR  2020        1     608445
3          PE  2020        1     356948
4          CL  2020        1     353627
..        ...   ...      ...        ...
320        UY  2026        1     309547
321        PY  2026        1     163202
322        GY  2026        1       9645
323        SR  2026        1       7373
324        GF  2026        1       4194

[325 rows x 4 columns]

In [46]:
# Queremos ordenar el DataFrame por las columnas "iso2_code", "year" y "quarter" en orden ascendente.
# Como si fuera una serie de tiempo: primero por país, luego por año y finalmente por trimestre.
df_south_america = df_south_america.sort_values(
    by=["iso2_code", "year", "quarter"],
    ascending=[True, True, True]
)
df_south_america

    iso2_code  year  quarter  num_repos
2          AR  2020        1     608445
15         AR  2020        2     670189
28         AR  2020        3     737110
41         AR  2020        4     802976
54         AR  2021        1     867545
..        ...   ...      ...        ...
266        VE  2025        1     380857
279        VE  2025        2     403230
292        VE  2025        3     421440
305        VE  2025        4     438426
318        VE  2026        1     460235

[325 rows x 4 columns]

* Es importante tener en cuenta que la base debe estar balanceada. 
* Es decir, que todos los quearter tengan dato. Si no sucede, hablar con el encargado. Quizás sea conveniente colocar 0 o NaN.

In [47]:
# Quiero ver los valores nulos (NaN) en la columna "num_repos" del DataFrame df_south_america. 
# Esto me permitirá identificar si hay registros sin información.
df_south_america[df_south_america.num_repos.isna() ]

Empty DataFrame
Columns: [iso2_code, year, quarter, num_repos]
Index: []

In [49]:
# El índice volvió a molestarnos (porque se reordenó el DataFrame). Procedemos a ordenarlo y reiniciar el índice:
df_south_america.reset_index(inplace=True)
df_south_america

     level_0  index iso2_code  year  quarter  num_repos
0          0      2        AR  2020        1     608445
1          1     15        AR  2020        2     670189
2          2     28        AR  2020        3     737110
3          3     41        AR  2020        4     802976
4          4     54        AR  2021        1     867545
..       ...    ...       ...   ...      ...        ...
320      320    266        VE  2025        1     380857
321      321    279        VE  2025        2     403230
322      322    292        VE  2025        3     421440
323      323    305        VE  2025        4     438426
324      324    318        VE  2026        1     460235

[325 rows x 6 columns]

In [50]:
# Eliminamos el índice anterior y el que se creó al reiniciar el índice, ya que no es necesario y solo ocupa espacio.
# Columnas level_0 e index:
df_south_america.drop(columns=["level_0", "index"], inplace=True)
df_south_america

    iso2_code  year  quarter  num_repos
0          AR  2020        1     608445
1          AR  2020        2     670189
2          AR  2020        3     737110
3          AR  2020        4     802976
4          AR  2021        1     867545
..        ...   ...      ...        ...
320        VE  2025        1     380857
321        VE  2025        2     403230
322        VE  2025        3     421440
323        VE  2025        4     438426
324        VE  2026        1     460235

[325 rows x 4 columns]

In [51]:
# Quiero ver el tipo de datos de las columnas:
df_south_america.dtypes

iso2_code    object
year          int64
quarter       int64
num_repos     int64
dtype: object

In [53]:
# Podemos cambiar el tipo de datos de iso2_code a string (str) para asegurarnos de que se trate como texto y no como un número. 
# Esto es útil si queremos realizar operaciones de texto o evitar problemas de interpretación de datos.
df_south_america["iso2_code"] = df_south_america["iso2_code"].astype(str)
df_south_america.dtypes

iso2_code    object
year          int64
quarter       int64
num_repos     int64
dtype: object

In [58]:
# Exportamos a formato csv en la misma carpeta del notebook:
# Guarda el DataFrame en la carpeta 'data'
df_south_america.to_csv("data/south_america_repositorios.csv", index=False)

## <a id='2.5.'>2.5. Importando datos: ENAPRES</a>

|Método|Descripción|
|------|-----------|
|read_excel( )|Lee un archivo Excel y lo convierte en un DataFrame.|
|to_csv( )| Escribe el índice y los registros en un archivo CSV|
|read_csv( )| Lee un archivo CSV y lo convierte en un DataFrame.|
|to_json( )| Convierte el objeto en una cadena de texto JSON.|
|to_pickle( )| Serializa el objeto y lo almacena en un archivo externo.|
|to_sql( )| Escribe los datos del objeto en una base de datos SQL activa.|
|read_html( )| Lee una tabla de una página HTML y la convierte en un DataFrame.|
|read_spss( )| Lee un archivo SPSS y lo convierte en un DataFrame.|

* La Encuesta Nacional de Programas Presupuestales (ENAPRES) se lleva a cabo desde el año 2010 en las zonas urbanas y rurales de los 24 departamentos y la Provincia Constitucional del Callao, como parte de las investigaciones realizadas por el Instituto Nacional de Estadística e Informática (INEI) en coordinación con el Ministerio de Economía y Finanzas (MEF) y los diversos ministerios y organismos del sector público.

In [8]:
import pandas as pd
import os

**DIRECCIONES RELATIVAS**

* Descargar el archivo correspondiente
* Usar **pwd** para saber su ubicación actual
* Dos puntos son un click para atrás seguido de un slash, junto con la nueva ruta que le corresponde.

In [ ]:
# Descargamos el archivo SPSS desde la web del INEI
# La ruta del archivo se construye utilizando os.path.join para asegurar la compatibilidad entre sistemas operativos
ruta_spss = os.path.join("data", "CAP_100_URBANO_RURAL_3.sav")

In [9]:
# Leemos el archivo SPSS usando Pandas
enapres2020_1 = pd.read_spss(ruta_spss)

# Mostramos las primeras 5 filas para verificar que cargó bien
enapres2020_1.head()

,PER,ANIO,MES,CONGLOMERADO,NSELV,TSELV,VIVREM,NUMVIVREM,AREA,CCDD,...,P189_5,P189_6,P189_7,P189_8,P189_8_O,REGIONNATU,ESTRATO,MOD_ENC,FACTOR,FACTOR_CALIBRADO
0,2.0,2020,07,04046,0046,Rural,0.0,NaN,RURAL,14,...,NaN,NaN,NaN,NaN,,COSTA,NaN,No Presencial,121.27014,NaN
1,2.0,2020,09,03981,0120,Urbano,0.0,NaN,URBANO,14,...,NaN,NaN,NaN,NaN,,COSTA,Estrato D,Presencial,245.10805,395.8496
2,2.0,2020,09,03981,0189,Urbano,0.0,NaN,URBANO,14,...,NaN,NaN,NaN,NaN,,COSTA,Estrato D,Presencial,245.10805,395.8496
3,2.0,2020,09,03981,0189,Urbano,0.0,NaN,URBANO,14,...,NaN,NaN,NaN,NaN,,COSTA,Estrato D,Presencial,245.10805,395.8496
4,2.0,2020,07,04046,0043,Rural,0.0,NaN,RURAL,14,...,NaN,NaN,NaN,NaN,,COSTA,NaN,No Presencial,121.27014,NaN

In [ ]:
# Variables
enapres2020_1.attrs

{'column_names': ['PER',
  'ANIO',
  'MES',
  'CONGLOMERADO',
  'NSELV',
  'TSELV',
  'VIVREM',
  'NUMVIVREM',
  'AREA',
  'CCDD',
  'NOMBREDD',
  'CCPP',
  'NOMBREPP',
  'CCDI',
  'NOMBREDI',
  'VIVIENDA',
  'TOT_HOGAR',
  'HOGAR',
  'RESFIN',
  'P100_C',
  'P101',
  'P101_O',
  'P102A',
  'P102A_O',
  'P103',
  'P103_O',
  'P104B',
  'P104B_O',
  'P105',
  'P106',
  'P106_O',
  'P106A',
  'P107',
  'P107A',
  'P107A_O',
  'P107B',
  'P107B_O',
  'P107C',
  'P108',
  'P108_1',
  'P108_1_O',
  'P108A',
  'P108B',
  'P108B_O',
  'P109',
  'P110A',
  'P110AA',
  'P110AB',
  'P110AC',
  'P111A',
  'P111AA',
  'P111AB_HORAS',
  'P111AB_MINUTOS',
  'P112_1',
  'P113_1',
  'P113A_1',
  'P113B_1_1',
  'P113B_1_1_ENT',
  'P113B_1_2',
  'P113B_1_2_ENT',
  'P113B_1_3',
  'P113B_1_3_ENT',
  'P113B_1_3_O',
  'P117_1',
  'P118_1',
  'P118_1_O',
  'P119_1',
  'P119_1_O',
  'P121_1',
  'P121_1_O',
  'P115_1',
  'P116_1_1',
  'P116_1_2',
  'P116_1_3',
  'P116_1_4',
  'P116_1_5',
  'P116_1_5_O',
  'P121A_1',
  'P121B_1',
  'P121C_1',
  'P121D_1_1',
  'P121D_1_2',
  'P121D_1_3',
  'P121D_1_4',
  'P121D_1_5',
  'P121D_1_5_O',
  'P112_2',
  'P113_2',
  'P113A_2',
  'P113B_2_1',
  'P113B_2_1_ENT',
  'P113B_2_2',
  'P113B_2_2_ENT',
  'P113B_2_3',
  'P113B_2_3_ENT',
  'P113B_2_3_O',
  'P117_2',
  'P118_2',
  'P118_2_O',
  'P119_2',
  'P119_2_O',
  'P121_2',
  'P121_2_O',
  'P115_2',
  'P116_2_1',
  'P116_2_2',
  'P116_2_3',
  'P116_2_4',
  'P116_2_5',
  'P116_2_5_O',
  'P121A_2',
  'P121B_2',
  'P121C_2',
  'P121D_2_1',
  'P121D_2_2',
  'P121D_2_3',
  'P121D_2_4',
  'P121D_2_5',
  'P121D_2_5_O',
  'P122A_1',
  'P122A_2',
  'P122A_3',
  'P122A_4',
  'P122A_5',
  'P122A_6',
  'P122A_6_O',
  'P122B_1',
  'P122B_2',
  'P122B_3',
  'P122B_4',
  'P122B_5',
  'P122B_6',
  'P122C_1',
  'P122C_2',
  'P122C_3',
  'P122C_4',
  'P122C_5',
  'P122C_6',
  'P122D_1',
  'P122D_2',
  'P122D_3',
  'P122D_4',
  'P122D_5',
  'P122D_6',
  'P122D_7',
  'P122D_8',
  'P122D_O',
  'P122E_1',
  'P122E_2',
  'P122E_3',
  'P122E_4',
  'P122E_5',
  'P122E_6',
  'P122E_7',
  'P122E_8',
  'P122F_1',
  'P122F_2',
  'P122F_3',
  'P122F_4',
  'P122F_5',
  'P122F_6',
  'P122F_7',
  'P122F_8',
  'P123',
  'P124',
  'P125',
  'P126',
  'P127_1',
  'P127_2',
  'P127_3',
  'P127_4',
  'P127_5',
  'P127_6',
  'P127_6_O',
  'P128A_1',
  'P128A_2',
  'P128A_3',
  'P128A_4',
  'P128A_5',
  'P128A_6',
  'P128A_7',
  'P128A_8',
  'P128A_O',
  'P129G',
  'P129G_O',
  'P129B',
  'P129C',
  'P100_C_2',
  'P129D_ENT',
  'P129D_DEC',
  'P129D_1',
  'P129E',
  'P129F',
  'P129F_O',
  'P129_DIA',
  'P129_MES',
  'P129_ANIO',
  'P129_HORA_INI',
  'P129_MIN_INI',
  'P130',
  'P130A',
  'P130B',
  'P130C',
  'P131_1',
  'P131_2',
  'P131_3',
  'P131_4',
  'P131_5',
  'P131_6',
  'P131_7',
  'P131_7_O',
  'P131A',
  'P131B',
  'P131B_O',
  'P131C_A',
  'P131C_B',
  'P131D',
  'P131D_O',
  'P132',
  'P133',
  'P134',
  'P135',
  'P136',
  'P137',
  'P137_O',
  'P138_1',
  'P138_2',
  'P138_3',
  'P138_N',
  'P139_1',
  'P139_2',
  'P139_3',
  'P139_4',
  'P139_O',
  'P140_1',
  'P140_2',
  'P140_3',
  'P141_1',
  'P141_2',
  'P141_3',
  'P141_4',
  'P141_5',
  'P141_6',
  'P141_7',
  'P141_7_O',
  'P142A',
  'P142A_O',
  'P143',
  'P144',
  'P145C_1_2',
  'P145C_1_4',
  'P145C_1_5',
  'P145C_1_6',
  'P145C_1_7',
  'P145C_2_1',
  'P145C_2_4',
  'P145C_2_5',
  'P145C_2_6',
  'P145C_2_7',
  'P145C_3_3',
  'P145C_3_4',
  'P145C_3_5',
  'P145C_3_6',
  'P145C_3_7',
  'P145C_4_3',
  'P145C_4_4',
  'P145C_4_5',
  'P145C_4_6',
  'P145C_4_7',
  'P146',
  'P147A_1',
  'P147A_2',
  'P147A_3',
  'P147A_4',
  'P147A_5',
  'P157',
  'P158',
  'P159',
  'P159_O',
  'P161_1',
  'P161A_1',
  'P161_2',
  'P161A_2',
  'P161_3',
  'P161A_3',
  'P161_4',
  'P161A_4',
  'P162_1',
  'P162_2',
  'P163_1',
  'P164_1_H',
  'P164_1_M',
  'P165_1',
  'P163_2',
  'P164_2_H',
  'P164_2_M',
  'P165_2',
  'P163_3',
  'P164_3_H',
  'P164_3_M',
  'P165_3',
  'P163_4',
  'P164_4_H',
  'P164_4_M',
  'P165_4',
  'P163_5',
  'P164_5_H',
  'P164_5_M',
  'P165_5',
  'P163_6',
  'P164_6_H',
  'P164_6_M',
  'P165_6',
  'P163_7',
  'P164_7_H',
  'P164_7_M',
  'P165_7',
  'P163_8',
  'P164_8_H',
  'P164_8_M',
  'P165_8',
  'P163_9',
  'P163_10',
  'P166A_1',
  'P167A_1_H',
  'P167A_1_M',
  'P168A_1',
  'P166A_2',
  'P167A_2_H',
  'P167A_2_M',
  'P168A_2',
  'P166A_3',
  'P167A_3_H',
  'P167A_3_M',
  'P168A_3',
  'P166A_4',
  'P167A_4_H',
  'P167A_4_M',
  'P168A_4',
  'P166A_5',
  'P167A_5_H',
  'P167A_5_M',
  'P168A_5',
  'P166A_6',
  'P167A_6_H',
  'P167A_6_M',
  'P168A_6',
  'P166A_7',
  'P167A_7_H',
  'P167A_7_M',
  'P168A_7',
  'P166A_8',
  'P167A_8_H',
  'P167A_8_M',
  'P168A_8',
  'P166A_9',
  'P172B_1',
  'P172C_1',
  'P172B_2',
  'P172C_2',
  'P172D',
  'P172E_1',
  'P172F_1_1',
  'P172F_1_2',
  'P172F_1_3',
  'P172F_1_4',
  'P172F_1_5',
  'P172F_1_6',
  'P172F_1_6_O',
  'P172E_2',
  'P172F_2_1',
  'P172F_2_2',
  'P172F_2_3',
  'P172F_2_4',
  'P172F_2_5',
  'P172F_2_6',
  'P172F_2_6_O',
  'P172E_3',
  'P172F_3_1',
  'P172F_3_2',
  'P172F_3_3',
  'P172F_3_4',
  'P172F_3_5',
  'P172F_3_6',
  'P172F_3_6_O',
  'P172E_4',
  'P172F_4_1',
  'P172F_4_2',
  'P172F_4_3',
  'P172F_4_4',
  'P172F_4_5',
  'P172F_4_6',
  'P172F_4_6_O',
  'P172E_5',
  'P172F_5_1',
  'P172F_5_2',
  'P172F_5_3',
  'P172F_5_4',
  'P172F_5_5',
  'P172F_5_6',
  'P172F_5_6_O',
  'P172E_6',
  'P172F_6_1',
  'P172F_6_2',
  'P172F_6_3',
  'P172F_6_4',
  'P172F_6_5',
  'P172F_6_6',
  'P172F_6_6_O',
  'P172E_7',
  'P172E_7_O',
  'P172F_7_1',
  'P172F_7_2',
  'P172F_7_3',
  'P172F_7_4',
  'P172F_7_5',
  'P172F_7_6',
  'P172F_7_6_O',
  'P172G',
  'P172H_1',
  'P172H_2',
  'P172H_3',
  'P172H_4',
  'P172H_5',
  'P172H_6',
  'P172H_7',
  'P172H_8',
  'P172H_8_O',
  'P178_1',
  'P178_2',
  'P178_3',
  'P178_4',
  'P178_5',
  'P178_6',
  'P178_7',
  'P179',
  'P180_1',
  'P180_2',
  'P180_3',
  'P180_4',
  'P180_5',
  'P180_6',
  'P180_O',
  'P181',
  'P184A_1',
  'P184A_2',
  'P184A_3',
  'P184A_4',
  'P184A_5',
  'P184A_6',
  'P184A_7',
  'P184A_8',
  'P184A_9',
  'P184A_10',
  'P184A_11',
  'P184A_12',
  'P184A_13',
  'P184A_14',
  'P184A_15',
  'P184A_16',
  'P184A_17',
  'P184A_18',
  'P185',
  'P185A',
  'P186',
  'P186A',
  'P187_1',
  'P187_2',
  'P187_3',
  'P187_4',
  'P187_5',
  'P187_6',
  'P187_7',
  'P187_8',
  'P187_9',
  'P187_9_O',
  'P188',
  'P189_1',
  'P189_2',
  'P189_3',
  'P189_4',
  'P189_5',
  'P189_6',
  'P189_7',
  'P189_8',
  'P189_8_O',
  'REGIONNATU',
  'ESTRATO',
  'MOD_ENC',
  'FACTOR',
  'FACTOR_CALIBRADO'],
 'column_labels': ['PERIODO',
  'AÑO',
  'MES DE LA ENCUESTA',
  'N° de conglomerado',
  'Nº de selección de la vivienda',
  'Tipo de selección de la vivienda',
  '¿Es una vivienda de reemplazo?',
  'Anote el número de selección de la vivienda reemplazada',
  'AREA',
  'Código de Departamento',
  'Nombre de Departamento',
  'Código de Provincia',
  'Nombre de la Provincia',
  'Código del Distrito',
  'Nombre del Distrito',
  'N° de Vivienda',
  '¿Cuántos hogares ocupa esta vivienda?',
  'Hogar N°',
  'Resultado final del hogar',
  'INFORMANTE N°',
  'TIPO DE VIVIENDA',
  'TIPO DE VIVIENDA: ESPECIFIQUE',
  'EN LA VIVIENDA, ¿EL MATERIAL DE CONSTRUCCIÓN PREDOMINANTE EN LAS PAREDES EXTERIORES ES DE:',
  'EN LA VIVIENDA, ¿EL MATERIAL DE CONSTRUCCIÓN PREDOMINANTE EN LAS PAREDES EXTERIORES ES DE: Otros materiales Especifique',
  'EL MATERIAL PREDOMINANTE EN LOS PISOS DE LA VIVIENDA ES',
  'EL MATERIAL PREDOMINANTE EN LOS PISOS DE LA VIVIENDA ES: ESPECIFIQUE',
  'EN LA VIVIENDA,  ¿EL MATERIAL DE CONSTRUCCIÓN PREDOMINANTE EN LOS TECHOS ES DE:',
  'EN LA VIVIENDA,  ¿EL MATERIAL DE CONSTRUCCIÓN PREDOMINANTE EN LOS TECHOS ES DE: Otro maaterial Especifique',
  '¿CUÁNTAS HABITACIONES EN TOTAL TIENE LA VIVIENDA, SIN CONTAR EL BAÑO, LA COCINA, LOS PASADIZOS, NI EL GARAJE?',
  'LA VIVIENDA QUE OCUPA ES:',
  'LA VIVIENDA QUE OCUPA ES: ESPECIFIQUE',
  '¿DESDE QUE AÑO VIVEN EN ESTA VIVIENDA?',
  '¿LA VIVIENDA CUENTA CON ALGÙN DOCUMENTO QUE ACREDITE LA PROPIEDAD?',
  '¿QUÉ TIPO DE DOCUMENTO ACREDITA EL DERECHO DE PROPIEDAD DE LA VIVIENDA?',
  '¿QUÉ TIPO DE DOCUMENTO ACREDITA EL DERECHO DE PROPIEDAD DE LA VIVIENDA?_ESPECIFIQUE',
  '¿QUÉ ENTIDAD O AUTORIDAD LE EMITIÓ EL/LA …...?',
  '¿QUÉ ENTIDAD O AUTORIDAD LE EMITIÓ EL/LA …...?_ESPECIFIQUE',
  '¿EL/LA ……ESTÁ A NOMBRE DE ALGÚN MIEMBRO DEL HOGAR DE ESTA VIVIENDA?',
  '¿EL/LA …… DE ESTA VIVIENDA ESTÀ REGISTRADO EN LOS REGISTROS PÚBLICOS?',
  '¿CUÁL ES EL PRINCIPAL MOTIVO POR EL CUAL NO REGISTRO EL/LA…?',
  '¿CUÁL ES EL PRINCIPAL MOTIVO POR EL CUAL NO REGISTRO EL/LA…?_ESPECIFIQUE',
  'LA CONSTRUCCIÓN DE ESTA VIVIENDA, ¿ESTÁ REGISTRADA EN LOS REGISTROS PÚBLICOS?',
  '¿CUÁL ES EL PRINCIPAL MOTIVO POR EL CUAL NO REGISTRO LA CONSTRUCCIÓN?',
  '¿CUÁL ES EL PRINCIPAL MOTIVO POR EL CUAL NO REGISTRO LA CONSTRUCCIÓN?_ESPECIFIQUE',
  '¿LA VIVIENDA TIENE ALUMBRADO ELÉCTRICO POR RED PÚBLICA?',
  '¿LA VIVIENDA TIENE ACCESO AL SERVICIO DE LA ENERGÍA ELÉCTRICA POR RED PÚBLICA TODOS LOS DÍAS DE LA SEMANA?',
  '¿CUÁNTAS HORAS AL DÍA?',
  '¿CUÁNTOS DÍAS A LA SEMANA TIENE ESTE SERVICIO?',
  '¿CUÁNTAS HORAS AL DÍA?',
  'EL MES ANTERIOR……., LA VIVIENDA ¿HA TENIDO INTERRUPCIONES O CORTES EN LA ENERGÍA ELÉCTRICA?',
  '¿Cuántas interrupciones o cortes tuvo en el mes anterior…..?',
  '¿Cuánto tiempo duró la última interrupción o corte?.....HORAS',
  '¿Cuánto tiempo duró la última interrupción o corte?.....MINUTOS',
  'EN LOS ÚLTIMOS 12 MESES ¿HAN SIDO VÍCTIMAS DE:..ROBO EN LA VIVIENDA',
  'EN LOS ÚLTIMOS 12 MESES ¿CUÁNTAS VECES FUERON VÍCTIMAS DE…ROBO EN LA VIVIENDA:',
  'DE ESTAS ……… VECES ¿CUÁNTAS FUERON DENUNCIADAS?....ROBO EN LA VIVIENDA',
  'DE ESTAS ……¿CUÁNTAS FUERON DENUNCIADAS EN: La Comisaria (Policia Nacional del Peru)....ROBO EN LA VIVIENDA',
  'DE ESTAS ……¿CUÁNTAS FUERON DENUNCIADAS EN: La Comisaria (Policia Nacional del Peru)_Nro DE VECES....ROBO EN LA VIVIENDA',
  'DE ESTAS ……¿CUÁNTAS FUERON DENUNCIADAS EN:  El Ministerio Publico o Fiscalia?....ROBO EN LA VIVIENDA',
  'DE ESTAS ……¿CUÁNTAS FUERON DENUNCIADAS EN:  El Ministerio Publico o Fiscalia?_Nro DE VECES....ROBO EN LA VIVIENDA',
  'DE ESTAS ……¿CUÁNTAS FUERON DENUNCIADAS EN: Otro?....ROBO EN LA VIVIENDA',
  'DE ESTAS ……¿CUÁNTAS FUERON DENUNCIADAS EN: Otro?_Nro DE VECES....ROBO EN LA VIVIENDA',
  'DE ESTAS ……¿CUÁNTAS FUERON DENUNCIADAS EN: Otro?.....ROBO EN LA VIVIENDA_OTRO/ESPECIFIQUE',
  '¿DENUNCIÓ EL: ROBO EN LA VIVIENDA?',
  '¿DÓNDE REALIZÓ LA DENUNCIA DEL? ROBO EN LA VIVIENDA',
  '¿DONDE REALIZÓ LA DENUNCIA DEL? ROBO EN LA VIVIENDA_OTRO/ESPECIFIQUE',
  '¿QUÉ SUCEDIÓ CON SU DENUNCIA ? ROBO EN LA VIVIENDA',
  '¿QUÉ SUCEDIÓ CON SU DENUNCIA ?…ROBO EN LA VIVIENDA_OTRO/ESPECIFIQUE',
  '¿CUÁL FUE EL MOTIVO PRINCIPAL POR EL CUAL NO REALIZÓ LA DENUNCIA?…ROBO EN LA VIVIENDA',
  '¿CUÁL FUE EL MOTIVO PRINCIPAL POR EL CUAL NO REALIZÓ LA DENUNCIA?…ROBO EN LA VIVIENDA_OTRO/ESPECIFIQUE',
  'EL DELINCUENTE / AGRESOR PORTABA ALGÚN ARMA (REVÓLVER, PISTOLA, PIEDRAS, PALOS, ETC.)…ROBO EN LA VIVIENDA',
  '¿QUÉ TIPO DE ARMA PORTABA? ROBO EN LA VIVIENDA Armas de fuego de mano (revólver, pistola u otro)',
  '¿QUÉ TIPO DE ARMA PORTABA? ROBO EN LA VIVIENDA Armas de fuego largo (escopeta, rifle, ametralladora)',
  '¿QUÉ TIPO DE ARMA PORTABA? ROBO EN LA VIVIENDA Arma blanca (cuchillo, objeto punzo cortante)',
  '¿QUÉ TIPO DE ARMA PORTABA? ROBO EN LA VIVIENDA Objetos contundentes (palos, piedras, etc.)',
  '¿QUÉ TIPO DE ARMA PORTABA? ROBO EN LA VIVIENDA Otro',
  '¿QUÉ TIPO DE ARMA PORTABA? ROBO EN LA VIVIENDA Otro _ESPECIFIQUE',
  '¿EN QUÉ MES SUCEDIÓ EL ROBO EN LA VIVIENDA?',
  '¿EL/LA  ROBO EN LA VIVIENDA OCURRIÓ UN:...',
  '¿EL/LOS DELINCUENTE/S UTILIZARON ALGÚN MEDIO DE TRANSPORTE PARA MOVILIZARSE?',
  '¿Qué MEDIO DE TRANSPORTE UTILIZÓ O UTILIZARÓN? Auto/camioneta',
  '¿Qué MEDIO DE TRANSPORTE UTILIZÓ O UTILIZARÓN? Motocicleta',
  '¿Qué MEDIO DE TRANSPORTE UTILIZÓ O UTILIZARÓN? Mototaxi/Mototriciclo',
  '¿Qué MEDIO DE TRANSPORTE UTILIZÓ O UTILIZARÓN? Bicicleta',
  '¿Qué MEDIO DE TRANSPORTE UTILIZÓ O UTILIZARÓN? Otro',
  '¿Qué MEDIO DE TRANSPORTE UTILIZÓ O UTILIZARÓN? Otro_Especifique',
  'EN LOS ÚLTIMOS 12 MESES DE……A……., ¿HAN SIDO VÍCTIMAS DE: INTENTO DE ROBO EN LA VIVIENDA?',
  'EN LOS ÚLTIMOS 12 MESES DE…….A………., ¿CUANTAS VECES FUERON VÍCTIMAS DE: INTENTO DE ROBO EN LA VIVIENDA?',
  'DE ESTAS ……… VECES ¿CUÁNTAS FUERON DENUNCIADAS? ...... INTENTO DE ROBO EN LA VIVIENDA',
  'DE ESTAS ……¿CUÁNTAS FUERON DENUNCIADAS EN: La Comisaria (Policia Nacional del Peru) ...... INTENTO DE ROBO EN LA VIVIENDA',
  'DE ESTAS ……¿CUÁNTAS FUERON DENUNCIADAS EN: La Comisaria (Policia Nacional del Peru)_Nro DE VECES ...... INTENTO DE ROBO EN LA VIVIENDA',
  'DE ESTAS ……¿CUÁNTAS FUERON DENUNCIADAS EN:  El Ministerio Publico o Fiscalia? ...... INTENTO DE ROBO EN LA VIVIENDA',
  'DE ESTAS ……¿CUÁNTAS FUERON DENUNCIADAS EN:  El Ministerio Publico o Fiscalia?_Nro DE VECES ...... INTENTO DE ROBO EN LA VIVIENDA',
  'DE ESTAS ……¿CUÁNTAS FUERON DENUNCIADAS EN: Otro? ...... INTENTO DE ROBO EN LA VIVIENDA',
  'DE ESTAS ……¿CUÁNTAS FUERON DENUNCIADAS EN: Otro?_Nro DE VECES ...... INTENTO DE ROBO EN LA VIVIENDA',
  'DE ESTAS ……¿CUÁNTAS FUERON DENUNCIADAS EN: Otro? ...... INTENTO DE ROBO EN LA VIVIENDA',
  'DENUNCIÓ EL …INTENTO DE ROBO EN LA VIVIENDA',
  '¿DÓNDE REALIZO LA DENUNCIA ?…INTENTO DE ROBO EN LA VIVIENDA',
  '¿DÓNDE REALIZO LA DENUNCIA ?…INTENTO DE ROBO EN LA VIVIENDA_OTRO/ESPECIFIQUE',
  '¿QUÉ SUCEDIÓ CON SU DENUNCIA ?…INTENTO DE ROBO EN LA VIVIENDA',
  '¿QUÉ SUCEDIÓ CON SU DENUNCIA ?…INTENTO DE ROBO EN LA VIVIENDA OTRO/ESPECIFIQUE',
  '¿CUÁL FUE EL MOTIVO PRINCIPAL POR EL CUAL NO REALIZÓ LA DENUNCIA?…INTENTO DE ROBO EN LA VIVIENDA',
  '¿CUÁL FUE EL MOTIVO PRINCIPAL POR EL CUAL NO REALIZÓ LA DENUNCIA?…INTENTO DE ROBO EN LA VIVIENDA_OTRO/ESPECIFIQUE',
  'EL DELINCUENTE / AGRESOR PORTABA ALGÚN ARMA (REVÓLVER, PISTOLA, PIEDRAS, PALOS, ETC.)…INTENTO DE ROBO EN LA VIVIENDA',
  '¿QUÉ TIPO DE ARMA PORTABA? INTENTO ROBO EN LA VIVIENDA Armas de fuego de mano (revólver, pistola u otro)',
  '¿QUÉ TIPO DE ARMA PORTABA? INTENTO ROBO EN LA VIVIENDA Armas de fuego largo (escopeta, rifle, ametralladora)',
  '¿QUÉ TIPO DE ARMA PORTABA? INTENTO ROBO EN LA VIVIENDA Arma blanca (cuchillo,objeto punzo cortante)',
  '¿QUÉ TIPO DE ARMA PORTABA? INTENTO ROBO EN LA VIVIENDA Objetos contundentes (palos, piedras, etc.)',
  '¿QUÉ TIPO DE ARMA PORTABA? INTENTO ROBO EN LA VIVIENDA Otro',
  '¿QUÉ TIPO DE ARMA PORTABA? INTENTO ROBO EN LA VIVIENDA Otro _ESPECIFIQUE',
  '¿EN QUÉ MES SUCEDIÓ EL ….?',
  '¿EL/LA  INTENTO DE ROBO EN LA VIVIENDA OCURRIÓ UN:...',
  '¿EL/LOS DELINCUENTE/S UTILIZARON ALGÚN MEDIO DE TRANSPORTE PARA MOVILIZARSE?',
  '¿Qué MEDIO DE TRANSPORTE UTILIZÓ O UTILIZARÓN? Auto/camioneta',
  '¿Qué MEDIO DE TRANSPORTE UTILIZÓ O UTILIZARÓN? Motocicleta',
  '¿Qué MEDIO DE TRANSPORTE UTILIZÓ O UTILIZARÓN? Mototaxi/Mototriciclo',
  '¿Qué MEDIO DE TRANSPORTE UTILIZÓ O UTILIZARÓN? Bicicleta',
  '¿Qué MEDIO DE TRANSPORTE UTILIZÓ O UTILIZARÓN? Otro',
  '¿Qué MEDIO DE TRANSPORTE UTILIZÓ O UTILIZARÓN? Otro_Especifique',
  'EN SU ZONA O BARRIO, ¿SE HA ADOPTADO ALGUNA MEDIDA DE SEGURIDAD PARA PREVENIR LA DELINCUENCIA, COMO: Sistema de vigilancia a través de video camaras?',
  'EN SU ZONA O BARRIO, ¿SE HA ADOPTADO ALGUNA MEDIDA DE SEGURIDAD PARA PREVENIR LA DELINCUENCIA, COMO: Vigilante particular?',
  'EN SU ZONA O BARRIO, ¿SE HA ADOPTADO ALGUNA MEDIDA DE SEGURIDAD PARA PREVENIR LA DELINCUENCIA, COMO: Sistema de alarma comunitaria?',
  'EN SU ZONA O BARRIO, ¿SE HA ADOPTADO ALGUNA MEDIDA DE SEGURIDAD PARA PREVENIR LA DELINCUENCIA, COMO: Sistema de control de acceso a personas ajenas al lugar?',
  'EN SU ZONA O BARRIO, ¿SE HA ADOPTADO ALGUNA MEDIDA DE SEGURIDAD PARA PREVENIR LA DELINCUENCIA, COMO: Junta vecinal con fines de velar por la seguridad?',
  'EN SU ZONA O BARRIO, ¿SE HA ADOPTADO ALGUNA MEDIDA DE SEGURIDAD PARA PREVENIR LA DELINCUENCIA, COMO: Otra?',
  'EN SU ZONA O BARRIO, ¿SE HA ADOPTADO ALGUNA MEDIDA DE SEGURIDAD PARA PREVENIR LA DELINCUENCIA, COMO: Otra?/Especifique',
  '¿DESDE QUE AÑO CUENTAN CON EL/LA: Sistema de vigilancia a traves de video camaras?',
  '¿DESDE QUE AÑO CUENTAN CON EL/LA: Vigilante particular?',
  '¿DESDE QUE AÑO CUENTAN CON EL/LA: Sistema de alarma comunitaria?',
  '¿DESDE QUE AÑO CUENTAN CON EL/LA: Sistema de control de acceso a personas ajenas al lugar?',
  '¿DESDE QUE AÑO CUENTAN CON EL/LA: Junta vecinal con fines de velar por la seguridad?',
  '¿DESDE QUE AÑO CUENTAN CON EL/LA: Otra?',
  '¿ESTA MEDIDA LA TOMÓ O SE INSTALÓ DURANTE LOS ÚLTIMOS 12 MESES DE………A ……….? Sistema de vigilancia a traves de video camaras?',
  '¿ESTA MEDIDA LA TOMÓ O SE INSTALÓ DURANTE LOS ÚLTIMOS 12 MESES DE………A ……….? Vigilante particular?',
  '¿ESTA MEDIDA LA TOMÓ O SE INSTALÓ DURANTE LOS ÚLTIMOS 12 MESES DE………A ……….? Sistema de alarma comunitaria?',
  '¿ESTA MEDIDA LA TOMÓ O SE INSTALÓ DURANTE LOS ÚLTIMOS 12 MESES DE………A ……….? Sistema de control de acceso a personas ajenas al lugar?',
  '¿ESTA MEDIDA LA TOMÓ O SE INSTALÓ DURANTE LOS ÚLTIMOS 12 MESES DE………A ……….? Junta vecinal con fines de velar por la seguridad?',
  '¿ESTA MEDIDA LA TOMÓ O SE INSTALÓ DURANTE LOS ÚLTIMOS 12 MESES DE………A ……….? Otra?',
  'ACTUALMENTE, ¿HAN ADOPTADO ALGUNA MEDIDA DE SEGURIDAD PARA PREVENIR EL ROBO EN SU VIVIENDA COMO: Evitar dejar la casa sola?',
  'ACTUALMENTE, ¿HAN ADOPTADO ALGUNA MEDIDA DE SEGURIDAD PARA PREVENIR EL ROBO EN SU VIVIENDA COMO: Colocar o adicionar cerrojos?',
  'ACTUALMENTE, ¿HAN ADOPTADO ALGUNA MEDIDA DE SEGURIDAD PARA PREVENIR EL ROBO EN SU VIVIENDA COMO: Colocar o adicionar cerraduras y/o candados?',
  'ACTUALMENTE, ¿HAN ADOPTADO ALGUNA MEDIDA DE SEGURIDAD PARA PREVENIR EL ROBO EN SU VIVIENDA COMO: Cambiar cerraduras y/o candados?',
  'ACTUALMENTE, ¿HAN ADOPTADO ALGUNA MEDIDA DE SEGURIDAD PARA PREVENIR EL ROBO EN SU VIVIENDA COMO: Tener perro guardián?',
  'ACTUALMENTE, ¿HAN ADOPTADO ALGUNA MEDIDA DE SEGURIDAD PARA PREVENIR EL ROBO EN SU VIVIENDA COMO: Poner puerta de rejas?',
  'ACTUALMENTE, ¿HAN ADOPTADO ALGUNA MEDIDA DE SEGURIDAD PARA PREVENIR EL ROBO EN SU VIVIENDA COMO: Instalar rejas en las ventanas?',
  'ACTUALMENTE, ¿HAN ADOPTADO ALGUNA MEDIDA DE SEGURIDAD PARA PREVENIR EL ROBO EN SU VIVIENDA COMO: Otro?',
  'ACTUALMENTE, ¿HAN ADOPTADO ALGUNA MEDIDA DE SEGURIDAD PARA PREVENIR EL ROBO EN SU VIVIENDA COMO: Otro?_Especifique',
  '122E. ¿DESDE QUÉ AÑO ADOPTÓ ESTA MEDIDA?  Evitar dejar la casa sola?',
  '122E. ¿DESDE QUÉ AÑO ADOPTÓ ESTA MEDIDA?  Colocar o adicionar cerrojos?',
  '122E. ¿DESDE QUÉ AÑO ADOPTÓ ESTA MEDIDA?  Colocar o adicionar cerraduras y/o candados?',
  '122E. ¿DESDE QUÉ AÑO ADOPTÓ ESTA MEDIDA?  Cambiar cerraduras y/o candados?',
  '122E. ¿DESDE QUÉ AÑO ADOPTÓ ESTA MEDIDA?  Tener perro guardián?',
  '122E. ¿DESDE QUÉ AÑO ADOPTÓ ESTA MEDIDA?  Poner puerta de rejas?',
  '122E. ¿DESDE QUÉ AÑO ADOPTÓ ESTA MEDIDA?  Instalar rejas en las ventanas?',
  '122E. ¿DESDE QUÉ AÑO ADOPTÓ ESTA MEDIDA?  Otro?',
  '122F. ¿ESTA MEDIDA FUE ADOPTADA O SE INSTALÓ DURANTE LOS ÚLTIMOS 12 MESES DE………A ……….? Evitar dejar la casa sola?',
  '122F. ¿ESTA MEDIDA FUE ADOPTADA O SE INSTALÓ DURANTE LOS ÚLTIMOS 12 MESES DE………A ……….? Colocar o adicionar cerrojos?',
  '122F. ¿ESTA MEDIDA FUE ADOPTADA O SE INSTALÓ DURANTE LOS ÚLTIMOS 12 MESES DE………A ……….? Colocar o adicionar cerraduras y/o candados?',
  '122F. ¿ESTA MEDIDA FUE ADOPTADA O SE INSTALÓ DURANTE LOS ÚLTIMOS 12 MESES DE………A ……….? Cambiar cerraduras y/o candados?',
  '122F. ¿ESTA MEDIDA FUE ADOPTADA O SE INSTALÓ DURANTE LOS ÚLTIMOS 12 MESES DE………A ……….? Tener perro guardián?',
  '122F. ¿ESTA MEDIDA FUE ADOPTADA O SE INSTALÓ DURANTE LOS ÚLTIMOS 12 MESES DE………A ……….? Poner puerta de rejas?',
  '122F. ¿ESTA MEDIDA FUE ADOPTADA O SE INSTALÓ DURANTE LOS ÚLTIMOS 12 MESES DE………A ……….? Instalar rejas en las ventanas?',
  '122F. ¿ESTA MEDIDA FUE ADOPTADA O SE INSTALÓ DURANTE LOS ÚLTIMOS 12 MESES DE………A ……….? Otro?',
  '¿EN SU CENTRO POBLADO EXISTE EL SERVICIO DE INTERNET EN CABINA PÚBLICA?',
  '¿EN SU CENTRO POBLADO EXISTEN INSTALACIONES PARA BRINDAR EL SERVICIO DE TELEFONÍA PÚBLICA?',

In [15]:
# adding labels to variables
enapres2020_1.attrs[ 'value_labels' ] = labels_enapres2020_1
enapres2020_1.attrs[ 'var_labels' ] = metadata.varLabels

NameError: name 'labels_enapres2020_1' is not defined

In [11]:
enapres2020_1

,PER,ANIO,MES,CONGLOMERADO,NSELV,TSELV,VIVREM,NUMVIVREM,AREA,CCDD,...,P189_5,P189_6,P189_7,P189_8,P189_8_O,REGIONNATU,ESTRATO,MOD_ENC,FACTOR,FACTOR_CALIBRADO
0,2.0,2020,07,04046,0046,Rural,0.0,NaN,RURAL,14,...,NaN,NaN,NaN,NaN,,COSTA,NaN,No Presencial,121.270140,NaN
1,2.0,2020,09,03981,0120,Urbano,0.0,NaN,URBANO,14,...,NaN,NaN,NaN,NaN,,COSTA,Estrato D,Presencial,245.108050,395.8496
2,2.0,2020,09,03981,0189,Urbano,0.0,NaN,URBANO,14,...,NaN,NaN,NaN,NaN,,COSTA,Estrato D,Presencial,245.108050,395.8496
3,2.0,2020,09,03981,0189,Urbano,0.0,NaN,URBANO,14,...,NaN,NaN,NaN,NaN,,COSTA,Estrato D,Presencial,245.108050,395.8496
4,2.0,2020,07,04046,0043,Rural,0.0,NaN,RURAL,14,...,NaN,NaN,NaN,NaN,,COSTA,NaN,No Presencial,121.270140,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42148,2.0,2020,05,51489,0073,Urbano,0.0,NaN,URBANO,18,...,NaN,NaN,NaN,NaN,,COSTA,Estrato D,No Presencial,8.948965,NaN
42149,2.0,2020,05,51489,0079,Urbano,0.0,NaN,URBANO,18,...,NaN,NaN,NaN,NaN,,COSTA,Estrato D,No Presencial,8.948965,NaN
42150,3.0,2020,08,51548,0026,Urbano,0.0,NaN,URBANO,23,...,NaN,NaN,NaN,NaN,,COSTA,Estrato E más bajo,No Presencial,102.009870,NaN
42151,3.0,2020,08,51548,0046,Urbano,0.0,NaN,URBANO,23,...,NaN,NaN,NaN,NaN,,COSTA,Estrato E más bajo,No Presencial,102.009870,NaN
42152,3.0,2020,08,51548,0066,Urbano,0.0,NaN,URBANO,23,...,NaN,NaN,NaN,NaN,,COSTA,Estrato E más bajo,No Presencial,102.009870,NaN

In [14]:
enapres2020_1.attrs[ 'value_labels' ]

{'labels0': {1.0: 'Urbano', 4.0: 'SemiRural', 5.0: 'Rural'},
 'labels1': {1.0: 'Si', 2.0: 'No'},
 'labels2': {1.0: 'URBANO', 2.0: 'RURAL'},
 'labels3': {1.0: 'Completa', 2.0: 'Incompleta'},
 'labels4': {1.0: 'Casa independiente',
  2.0: 'Departamento en edificio',
  3.0: 'Vivienda en quinta',
  4.0: 'Vivienda en casa de vecindad (callejón, solar o corralón)',
  5.0: 'Choza o cabaña',
  6.0: 'Vivienda improvisada',
  7.0: 'Local no destinado para habitación humana',
  8.0: 'Otro(Especifique)'},
 'labels5': {1.0: 'Ladrillo o bloque de cemento?',
  2.0: 'Piedra o sillar con cal o cemento?',
  3.0: 'Adobe?',
  4.0: 'Tapia?',
  5.0: 'Quincha (caña con barro)?',
  6.0: 'Piedra con barro?',
  7.0: ' Madera (pona, tornillo, etc.)?',
  8.0: 'Tripley/ Calamina/ Estera?',
  9.0: 'Otro material?'},
 'labels6': {1.0: '¿Parquet o madera pulida?',
  2.0: '¿Láminas asfálticas, vinílicos o similares?',
  3.0: '¿Losetas, terrazos o similares?',
  4.0: '¿Madera (pona, tornillo, etc.)?',
  5.0: '¿Cemento?',
  6.0: '¿Tierra?',
  7.0: '¿Otro(Especifique)?'},
 'labels7': {1.0: '¿Concreto armado?',
  2.0: '¿Madera?',
  3.0: '¿Tejas?',
  4.0: '¿Planchas de calamina, fibra de cemento o similares?',
  5.0: 'Caña o estera con torta de barro o cemento?',
  6.0: 'Tripley/ estera/ carrizo?',
  7.0: 'Paja, hojas de palmera y similares.?',
  8.0: 'Otro material'},
 'labels8': {1.0: '¿Alquilada?',
  2.0: '¿Propia, totalmente pagada?',
  3.0: '¿Propia, por invasión?',
  4.0: '¿Propia, comprándola a plazos?',
  5.0: '¿Cedida por otro hogar?',
  6.0: '¿Cedida por el centro de trabajo?',
  7.0: '¿Cedida por otra institución?',
  8.0: '¿Otra?(Especifique)'},
 'labels9': {1.0: 'Hasta el 2004',
  2.0: '2005',
  3.0: '2006',
  4.0: '2007',
  5.0: '2008',
  6.0: '2009',
  7.0: '2010',
  8.0: '2011',
  9.0: '2012',
  10.0: '2013',
  11.0: '2014',
  12.0: '2015',
  13.0: '2016',
  14.0: '2017',
  15.0: '2018',
  16.0: '2019',
  17.0: '2020'},
 'labels10': {1.0: 'Si', 2.0: 'No', 3.0: 'NO SABE'},
 'labels11': {1.0: 'Título de Propiedad',
  2.0: 'Sentencia Judicial',
  3.0: 'Escritura Pública',
  4.0: 'Contrato de Compra-Venta',
  5.0: 'Minuta',
  6.0: 'Documento de Posesión',
  7.0: 'Otro(Especifique)'},
 'labels12': {1.0: 'COFOPRI',
  2.0: 'Municipalidad',
  3.0: 'Juez/a',
  4.0: 'Notaría',
  5.0: 'Otro(Especifique)',
  6.0: 'NINGUNO'},
 'labels13': {1.0: 'Si', 2.0: 'No'},
 'labels14': {1.0: 'Desconocía que tenía que inscribirlo en los Registros Públicos',
  2.0: 'Los costos para tramitar son elevados',
  3.0: 'El trámite es engorroso',
  4.0: 'Los impuestos son elevados',
  5.0: 'Otro(Especifique)'},
 'labels15': {1.0: 'Desconocía que tenía que inscribirlo en los Registros Públicos',
  2.0: 'Los costos para tramitar son elevados',
  3.0: 'El trámite es engorroso',
  4.0: 'Los impuestos son elevados',
  5.0: 'Otro(Especifique)'},
 'labels16': {1.0: 'Si', 2.0: 'No'},
 'labels17': {0.0: 'Pase', 1.0: 'La Comisaria (Policia Nacional del Peru)?'},
 'labels18': {0.0: 'Pase', 1.0: 'El Ministerio Publico o Fiscalia?'},
 'labels19': {0.0: 'Pase', 1.0: 'Otro?'},
 'labels20': {1.0: 'Comisaría (Policía Nacional del Perú)',
  2.0: 'Ministerio Público o Fiscalía',
  3.0: 'Otro(Especifique)'},
 'labels21': {1.0: 'Está en trámite',
  2.0: 'No sucedió nada',
  3.0: 'Recuperó sus bienes y se detuvo al delincuente',
  4.0: 'Solo recuperó sus bienes',
  5.0: 'Se detuvo al delincuente',
  6.0: 'Otro(Especifique)'},
 'labels22': {1.0: 'Por miedo a represalias del agresor/a',
  2.0: 'Es una pérdida de tiempo',
  3.0: 'Desconfía de la Policía',
  4.0: 'No se consumó el hecho',
  5.0: 'Delito de poca importancia',
  6.0: 'Desconoce al delincuente',
  7.0: 'Otro(Especifique)'},
 'labels23': {0.0: 'Pase',
  1.0: 'Armas de fuego de mano (revólver, pistola u otro)'},
 'labels24': {0.0: 'Pase',
  1.0: 'Armas de fuego largo (escopeta, rifle, ametralladora)'},
 'labels25': {0.0: 'Pase',
  1.0: 'Arma blanca (cuchillo,objeto punzo cortante)'},
 'labels26': {0.0: 'Pase', 1.0: 'Objetos contundentes (palos, piedras, etc.)'},
 'labels27': {0.0: 'Pase', 1.0: 'Otro'},
 'labels28': {1.0: 'Día laborable de lunes a viernes?',
  2.0: 'Fin de semana?',
  3.0: 'Día feriado?',
  4.0: 'NO RECUERDA',
  5.0: 'NO SABE'},
 'labels29': {1.0: 'Si', 2.0: 'No', 3.0: 'No recuerda', 4.0: 'NO SABE'},
 'labels30': {1.0: 'Pase', 2.0: 'Auto/camioneta'},
 'labels31': {1.0: 'Pase', 2.0: 'Motocicleta'},
 'labels32': {1.0: 'Pase', 2.0: 'Mototaxi/Mototriciclo'},
 'labels33': {1.0: 'Pase', 2.0: 'Bicicleta'},
 'labels34': {1.0: 'Pase', 2.0: 'Otro'},
 'labels35': {0.0: 'Pase', 1.0: 'La Comisaria (Policia Nacional del Peru)?'},
 'labels36': {0.0: 'Pase', 1.0: 'El Ministerio Publico o Fiscalia?'},
 'labels37': {0.0: 'Pase', 1.0: 'Otro?'},
 'labels38': {0.0: 'Pase',
  1.0: 'Armas de fuego de mano (revólver, pistola u otro)'},
 'labels39': {0.0: 'Pase',
  1.0: 'Armas de fuego largo (escopeta, rifle, ametralladora)'},
 'labels40': {0.0: 'Pase',
  1.0: 'Arma blanca (cuchillo,objeto punzo cortante)'},
 'labels41': {0.0: 'Pase', 1.0: 'Objetos contundentes (palos, piedras, etc.)'},
 'labels42': {0.0: 'Pase', 1.0: 'Otro'},
 'labels43': {1.0: 'Pase', 2.0: 'Auto/camioneta'},
 'labels44': {1.0: 'Pase', 2.0: 'Motocicleta'},
 'labels45': {1.0: 'Pase', 2.0: 'Mototaxi/Mototriciclo'},
 'labels46': {1.0: 'Pase', 2.0: 'Bicicleta'},
 'labels47': {1.0: 'Pase', 2.0: 'Otro'},
 'labels48': {1.0: 'Si', 2.0: 'No'},
 'labels49': {1.0: 'Si', 2.0: 'No', 3.0: 'NO SABE'},
 'labels50': {1.0: 'Si', 2.0: 'No'},
 'labels51': {0.0: 'Pase', 1.0: 'Electricidad'},
 'labels52': {0.0: 'Pase', 1.0: 'Petroleo/ Gas (lámpara)'},
 'labels53': {0.0: 'Pase', 1.0: 'vela'},
 'labels54': {0.0: 'Pase', 1.0: 'Generador'},
 'labels55': {0.0: 'Pase', 1.0: 'Panel solar'},
 'labels56': {0.0: 'Pase', 1.0: 'otro'},
 'labels57': {0.0: 'Pase', 1.0: 'Electricidad?'},
 'labels58': {0.0: 'Pase', 1.0: 'Gas (balón GLP)?'},
 'labels59': {0.0: 'Pase', 1.0: 'Gas natural (sistema de tuberías)?'},
 'labels60': {0.0: 'Pase', 1.0: 'Carbón?'},
 'labels61': {0.0: 'Pase', 1.0: 'Leña?'},
 'labels62': {0.0: 'Pase', 1.0: 'Bosta, estiércol?'},
 'labels63': {0.0: 'Pase', 1.0: 'Otro'},
 'labels64': {0.0: 'Pase', 1.0: 'NO COCINAN'},
 'labels65': {1.0: '¿Red pública dentro de la vivienda?',
  2.0: '¿Red pública fuera de la vivienda, pero dentro de la edificación?',
  3.0: 'Pilón o pileta de uso público?',
  4.0: '¿Camión-cisterna u otro similar?',
  5.0: 'Pozo (agua subterranea)?',
  6.0: 'Manantial o puquio?',
  7.0: 'Rio, acequia, lago, laguna?',
  8.0: '¿Otro?'},
 'labels66': {1.0: 'Mayor o igual a 0,5 mg Seguro',
  2.0: 'De 0,1 mg/l a menos de 0,5 mg/l Inadecuada dosificación de cloro',
  3.0: '0,0 mg/l sin cloro',
  4.0: 'No se realizó la prueba'},
 'labels67': {0.0: 'Pase', 1.0: 'No se realizo la prueba'},
 'labels68': {1.0: 'El funcionario de la encuesta', 2.0: 'El informante'},
 'labels69': {1.0: '¿Grifo o caño?',
  2.0: '¿Cilindro de metal?',
  3.0: '¿Balde o batea de plástico?',
  4.0: '¿Tanque (sin filtro)?',
  5.0: '¿Tanque (con filtro)?',
  6.0: '¿Bidón, botella, etc.?',
  7.0: '¿Otro?'},
 'labels70': {0.0: 'Pase', 1.0: 'Cocinar'},
 'labels71': {0.0: 'Pase', 1.0: 'Aseo personal'},
 'labels72': {0.0: 'Pase', 1.0: 'Lavar la ropa'},
 'labels73': {0.0: 'Pase', 1.0: 'Regar el huerto o chacra'},
 'labels74': {0.0: 'Pase', 1.0: 'Dar de beber a los animales domésticos'},
 'labels75': {0.0: 'Pase', 1.0: 'Dar de beber a los animales crianza'},
 'labels76': {0.0: 'Pase', 1.0: 'Otro'},
 'labels77': {1.0: 'Si', 2.0: 'No', 3.0: 'NO SABE'},
 'labels78': {1.0: '¿Diaria?',
  2.0: '¿Interdiaria?',
  3.0: '¿Semanal?',
  4.0: '¿Quincenal?',
  5.0: '¿Mensual?',
  6.0: '¿Anual?',
  7.0: '¿Otro?'},
 'labels79': {1.0: 'No sabe'},
 'labels80': {1.0: 'Junta Administradora de los Servicios de Saneamiento (JASS)',
  2.0: 'Otra organización comunal formada para tal fin',
  3.0: 'Municipalidad',
  4.0: 'Empresa prestadora de servicios (EPS)',
  5.0: 'Otro'},
 'labels81': {1.0: 'Si', 2.0: 'No', 3.0: 'NO ACCEDIÓ'},
 'labels82': {1.0: 'Si', 2.0: 'No', 3.0: 'NO ACCEDIÓ'},
 'labels83': {1.0: 'Recipiente con caño en la parte inferior',
  2.0: 'Vasija con asa o mango largo',
  3.0: 'Vasija con asa o mango corto',
  4.0: 'Vasija sin asa',
  5.0: 'De forma directa (verter el agua directamente a la vasija)',
  6.0: 'Otra'},
 'labels84': {0.0: 'Pase', 1.0: 'Antes de comer'},
 'labels85': {0.0: 'Pase', 1.0: 'Antes de preparar los alimentos'},
 'labels86': {0.0: 'Pase', 1.0: 'Despues de defecar'},
 'labels87': {0.0: 'Pase', 1.0: 'Otro'},
 'labels88': {0.0: 'Pase', 1.0: 'ONG'},
 'labels89': {0.0: 'Pase', 1.0: 'MINISTERIO DE VIVIENDA'},
 'labels90': {0.0: 'Pase', 1.0: 'FONCODES'},
 'labels91': {0.0: 'Pase', 1.0: 'MINSA'},
 'labels92': {0.0: 'Pase', 1.0: 'MINEDU'},
 'labels93': {0.0: 'Pase', 1.0: 'MUNICIPALIDAD'},
 'labels94': {0.0: 'Pase', 1.0: 'OTRA'},
 'labels95': {1.0: '¿Red pública de desagüe dentro de la vivienda?',
  2.0: '¿Red pública de desagüe fuera de la vivienda, pero dentro de la edificación?',
  3.0: '¿Letrina?',
  4.0: 'Pozo séptico, tanque séptico  o biodigestor?',
  5.0: 'Pozo ciego o negro?',
  6.0: 'Río, acequia o canal o similar?',
  7.0: 'Campo abierto o al aire libre?',
  8.0: 'Otro?'},
 'labels96': {1.0: 'Arrastre hidráulico',
  2.0: 'Hoyo seco',
  3.0: 'Compostera seca',
  4.0: 'Compostera húmeda'},
 'labels97': {3.0: 'Letrina', 4.0: 'Pozo séptico', 5.0: 'Pozo ciego o negro'},
 'labels98': {1.0: 'Muy malo', 2.0: 'Malo', 4.0: 'Bueno', 5.0: 'Muy bueno'},
 'labels99': {1.0: 'Interrupciones en plena llamada',
  2.0: 'No se escucha bien / No me escuchan bien',
  3.0: 'Los reclamos demoran más de 7 días en ser atendidos',
  4.0: 'Poca disponibilidad de tarjetas',
  5.0: 'Centros de pago alejados',
  6.0: 'Costo elevado',
  7.0: 'Otro'},
 'labels100': {1.0: 'Malo', 3.0: 'Bueno', 4.0: 'No sabe'},
 'labels101': {1.0: 'Malo', 3.0: 'Bueno', 4.0: 'No sabe', 5.0: 'No existe'},
 'labels102': {1.0: 'Si',
  2.0: 'No',
  3.0: 'No sabe',
  4.0: 'No existe transporte público'},
 'labels103': {0.0: 'Pase', 1.0: 'A PIE'},
 'labels104': {1.0: 'Camino de herradura?',
  2.0: 'Camino vecinal (carrozable)?',
  3.0: 'Carretera?'},
 'labels105': {0.0: 'Pase', 1.0: 'ACEMILA'},
 'labels106': {0.0: 'Pase', 1.0: 'BICICLETA, TRICICLO'},
 'labels107': {0.0: 'Pase', 1.0: 'MOTO, MOTOTAXI, ETC'},
 'labels108': {0.0: 'Pase', 1.0: 'AUTO, CAMIONETA, ETC'},
 'labels109': {2.0: 'Camino vecinal (carrozable)?', 3.0: 'Carretera?'},
 'labels110': {0.0: 'Pase', 1.0: 'CAMIONETA RURAL, OMNIBUS, ETC'},
 'labels111': {0.0: 'Pase', 1.0: 'BOTE, LANCHA, ETC. ( ACUATICO CON MOTOR)'},
 'labels112': {4.0: 'Río o lago?'},
 'labels113': {0.0: 'Pase', 1.0: 'CANOA, BALSA, ETC. ( ACUATICO SIN MOTOR)'},
 'labels114': {0.0: 'Pase', 1.0: 'NO ACUDE AL MAS CERCANO'},
 'labels115': {0.0: 'Pase', 1.0: 'NO ACUDE AL ESTABLECIMIENTO DE SALUD'},
 'labels116': {0.0: 'Pase', 1.0: 'A PIE'},
 'labels117': {0.0: 'Pase', 1.0: 'ACEMILA'},
 'labels118': {0.0: 'Pase', 1.0: 'BICICLETA, TRICICLO'},
 'labels119': {0.0: 'Pase', 1.0: 'MOTO, MOTOTAXI, ETC'},
 'labels120': {0.0: 'Pase', 1.0: 'AUTO, CAMIONETA, ETC'},
 'labels121': {0.0: 'Pase', 1.0: 'CAMIONETA RURAL, OMNIBUS, ETC'},
 'labels122': {0.0: 'Pase', 1.0: ' BOTE, LANCHA, ETC. ( ACUATICO CON MOTOR)'},
 'labels123': {0.0: 'Pase', 1.0: 'CANOA, BALSA, ETC. ( ACUATICO SIN MOTOR)'},
 'labels124': {0.0: 'Pase', 1.0: 'NO ACUDE'},
 'labels125': {1.0: 'Si', 2.0: 'No'},
 'labels126': {1.0: ' Muy insatisfecho/a?',
  2.0: 'Insatisfecho/a?',
  3.0: 'Satisfecho/a?',
  4.0: 'Muy satisfecho/a?'},
 'labels127': {1.0: ' Muy insatisfecho/a?',
  2.0: 'Insatisfecho/a?',
  3.0: 'Satisfecho/a?',
  4.0: 'Muy satisfecho/a?'},
 'labels128': {1.0: 'Si', 2.0: 'No'},
 'labels129': {1.0: 'Si', 2.0: 'No'},
 'labels130': {0.0: 'Pase', 1.0: ' Directamente a la municipalidad'},
 'labels131': {0.0: 'Pase',
  1.0: ' A una asociación de recicladores formalizados'},
 'labels132': {0.0: 'Pase', 1.0: '  A un reciclador informal'},
 'labels133': {0.0: 'Pase', 1.0: '  Los traslado a un punto de acopio'},
 'labels134': {1.0: 'Uso/manejo directo por parte del generador/a'},
 'labels135': {0.0: 'Pase', 1.0: ' Otro'},
 'labels136': {1.0: 'Si', 2.0: 'No'},
 'labels137': {0.0: 'Pase', 1.0: ' Directamente a la municipalidad'},
 'labels138': {0.0: 'Pase',
  1.0: ' A una asociación de recicladores formalizados'},
 'labels139': {0.0: 'Pase', 1.0: '  A un reciclador informal'},
 'labels140': {0.0: 'Pase', 1.0: '  Los traslado a un punto de acopio'},
 'labels141': {0.0: 'Pase', 1.0: ' Otro'},
 'labels142': {1.0: 'Si', 2.0: 'No'},
 'labels143': {0.0: 'Pase', 1.0: ' Directamente a la municipalidad'},
 'labels144': {0.0: 'Pase',
  1.0: ' A una asociación de recicladores formalizados'},
 'labels145': {0.0: 'Pase', 1.0: '  A un reciclador informal'},
 'labels146': {0.0: 'Pase', 1.0: '  Los traslado a un punto de acopio'},
 'labels147': {0.0: 'Pase', 1.0: ' Otro'},
 'labels148': {1.0: 'Si', 2.0: 'No'},
 'labels149': {0.0: 'Pase', 1.0: ' Directamente a la municipalidad'},
 'labels150': {0.0: 'Pase',
  1.0: ' A una asociación de recicladores formalizados'},
 'labels151': {0.0: 'Pase', 1.0: '  A un reciclador informal'},
 'labels152': {0.0: 'Pase', 1.0: '  Los traslado a un punto de acopio'},
 'labels153': {0.0: 'Pase', 1.0: ' Otro'},
 'labels154': {1.0: 'Si', 2.0: 'No'},
 'labels155': {0.0: 'Pase', 1.0: ' Directamente a la municipalidad'},
 'labels156': {0.0: 'Pase',
  1.0: ' A una asociación de recicladores formalizados'},
 'labels157': {0.0: 'Pase', 1.0: '  A un reciclador informal'},
 'labels158': {0.0: 'Pase', 1.0: '  Los traslado a un punto de acopio'},
 'labels159': {0.0: 'Pase', 1.0: ' Otro'},
 'labels160': {1.0: 'Si', 2.0: 'No'},
 'labels161': {0.0: 'Pase', 1.0: ' Directamente a la municipalidad'},
 'labels162': {0.0: 'Pase',
  1.0: ' A una asociación de recicladores formalizados'},
 'labels163': {0.0: 'Pase', 1.0: '  A un reciclador informal'},
 'labels164': {0.0: 'Pase', 1.0: '  Los traslado a un punto de acopio'},
 'labels165': {0.0: 'Pase', 1.0: ' Otro'},
 'labels166': {1.0: 'Si', 2.0: 'No'},
 'labels167': {0.0: 'Pase', 1.0: ' Directamente a la municipalidad'},
 'labels168': {0.0: 'Pase',
  1.0: ' A una asociación de recicladores formalizados'},
 'labels169': {0.0: 'Pase', 1.0: '  A un reciclador informal'},
 'labels170': {0.0: 'Pase', 1.0: '  Los traslado a un punto de acopio'},
 'labels171': {0.0: 'Pase', 1.0: ' Otro'},
 'labels172': {1.0: 'Si', 2.0: 'No'},
 'labels173': {0.0: 'Pase', 1.0: ' Municipalidad'},
 'labels174': {0.0: 'Pase', 1.0: ' Ministerio del Ambiente (MINAM)'},
 'labels175': {0.0: 'Pase',
  1.0: ' Empresa privada del recojo de basura en su distrito'},
 'labels176': {0.0: 'Pase', 1.0: ' Ministerio de Educación (MINEDU)'},
 'labels177': {0.0: 'Pase', 1.0: ' Ministerio de Educación (MINEDU)'},
 'labels178': {0.0: 'Pase', 1.0: ' Organismo no gubernamental (ONG)'},
 'labels179': {0.0: 'Pase', 1.0: ' Ministerio de Salud (MINSA)'},
 'labels180': {0.0: 'Pase', 1.0: ' Ministerio de Salud (MINSA)'},
 'labels181': {1.0: 'Si', 2.0: 'No'},
 'labels182': {1.0: 'Si', 2.0: 'No'},
 'labels183': {1.0: 'Si', 2.0: 'No'},
 'labels184': {1.0: 'Si', 2.0: 'No'},
 'labels185': {1.0: 'Si', 2.0: 'No'},
 'labels186': {1.0: 'Si', 2.0: 'No'},
 'labels187': {1.0: 'Si', 2.0: 'No'},
 'labels188': {0.0: 'Pase', 1.0: 'Otra'},
 'labels189': {0.0: 'Pase', 1.0: 'Produce riesgo para el medio ambiente'},
 'labels190': {0.0: 'Pase',
  1.0: 'Interfieren con los aparatos de uso cotidiano'},
 'labels191': {0.0: 'Pase', 1.0: 'Emiten ruidos, zumbidos'},
 'labels192': {0.0: 'Pase', 1.0: 'Produce riesgo de accidente'},
 'labels193': {0.0: 'Pase', 1.0: 'Otra'},
 'labels194': {0.0: 'Pase', 1.0: '¿Equipo de sonido?'},
 'labels195': {0.0: 'Pase', 1.0: '¿Televisor a color?'},
 'labels196': {0.0: 'Pase', 1.0: '¿Cocina a gas?'},
 'labels197': {0.0: 'Pase', 1.0: '¿Refrigeradora o congeladora?'},
 'labels198': {0.0: 'Pase', 1.0: '¿Lavadora de ropa?'},
 'labels199': {0.0: 'Pase', 1.0: '¿Horno microondas?'},
 'labels200': {0.0: 'Pase', 1.0: '¿Licuadora?'},
 'labels201': {0.0: 'Pase', 1.0: '¿Plancha electrica?'},
 'labels202': {0.0: 'Pase', 1.0: '¿Computadora / Laptop / Tablet?'},
 'labels203': {0.0: 'Pase',
  1.0: '¿Teléfono celular sin servicio de internet?'},
 'labels204': {0.0: 'Pase', 1.0: '¿Teléfono celular con servicio de internet'},
 'labels205': {0.0: 'Pase', 1.0: '¿Teléfono fijo?'},
 'labels206': {0.0: 'Pase', 1.0: '¿Conexión a TV por cable o satelital?'},
 'labels207': {0.0: 'Pase', 1.0: '¿Conexión a Internet?'},
 'labels208': {0.0: 'Pase', 1.0: '¿Automóvil, camioneta?'},
 'labels209': {0.0: 'Pase', 1.0: '¿Motocicleta?'},
 'labels210': {0.0: 'Pase', 1.0: '¿Lancha, bote motor o peque peque, canoa?'},
 'labels211': {0.0: 'Pase', 1.0: 'NO TIENE NINGUNO'},
 'labels212': {1.0: 'Si', 2.0: 'No'},
 'labels213': {1.0: 'Si', 2.0: 'No'},
 'labels214': {1.0: 'Si', 2.0: 'No'},
 'labels215': {1.0: 'Si', 2.0: 'No'},
 'labels216': {1.0: 'Si', 2.0: 'No'},
 'labels217': {1.0: 'Si', 2.0: 'No'},
 'labels218': {1.0: 'Si', 2.0: 'No'},
 'labels219': {1.0: 'Si', 2.0: 'No'},
 'labels220': {1.0: 'Si', 2.0: 'No'},
 'labels221': {1.0: 'Si', 2.0: 'No'},
 'labels222': {0.0: 'Pase', 1.0: 'Municipalidad'},
 'labels223': {0.0: 'Pase', 1.0: 'Ministerio del Ambiente (MINAM)'},
 'labels224': {0.0: 'Pase',
  1.0: 'Empresa privada del recojo de basura en su distrito'},
 'labels225': {0.0: 'Pase', 1.0: 'Asociación de Recicladores'},
 'labels226': {0.0: 'Pase', 1.0: 'Ministerio de Educación (MINEDU)'},
 'labels227': {0.0: 'Pase', 1.0: 'Organismo no gubernamental (ONG)'},
 'labels228': {0.0: 'Pase', 1.0: 'Ministerio de Salud (MINSA)'},
 'labels229': {0.0: 'Pase', 1.0: 'Otra'},
 'labels230': {'1': 'COSTA', '2': 'SIERRA', '3': 'SELVA'},
 'labels231': {1.0: 'Estrato A más alto',
  2.0: 'Estrato B',
  3.0: 'Estrato C',
  4.0: 'Estrato D',
  5.0: 'Estrato E más bajo'},
 'labels232': {1.0: 'Presencial', 2.0: 'No Presencial'},
 'labels233': {'0': 'Pase', '1': 'OTRO/ESPECIFIQUE'}}

### 3.3.5. <a id='3.3.5'>Filtering data</a>

In [16]:
enapres2020_1.AREA == "RURAL"

0         True
1        False
2        False
3        False
4         True
         ...
42148    False
42149    False
42150    False
42151    False
42152    False
Name: AREA, Length: 42153, dtype: bool

In [20]:
enapres2020_1.shape

(42153, 491)

In [17]:
enapres2020_1.loc[ enapres2020_1.AREA == 'URBANO',  :  ]

,PER,ANIO,MES,CONGLOMERADO,NSELV,TSELV,VIVREM,NUMVIVREM,AREA,CCDD,...,P189_5,P189_6,P189_7,P189_8,P189_8_O,REGIONNATU,ESTRATO,MOD_ENC,FACTOR,FACTOR_CALIBRADO
1,2.0,2020,09,03981,0120,Urbano,0.0,NaN,URBANO,14,...,NaN,NaN,NaN,NaN,,COSTA,Estrato D,Presencial,245.108050,395.8496
2,2.0,2020,09,03981,0189,Urbano,0.0,NaN,URBANO,14,...,NaN,NaN,NaN,NaN,,COSTA,Estrato D,Presencial,245.108050,395.8496
3,2.0,2020,09,03981,0189,Urbano,0.0,NaN,URBANO,14,...,NaN,NaN,NaN,NaN,,COSTA,Estrato D,Presencial,245.108050,395.8496
6,2.0,2020,09,06703,0037,Urbano,0.0,NaN,URBANO,01,...,NaN,NaN,NaN,NaN,,SELVA,Estrato E más bajo,No Presencial,79.149970,NaN
7,2.0,2020,09,03981,0057,Urbano,0.0,NaN,URBANO,14,...,NaN,NaN,NaN,NaN,,COSTA,Estrato D,Presencial,245.108050,395.8496
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42148,2.0,2020,05,51489,0073,Urbano,0.0,NaN,URBANO,18,...,NaN,NaN,NaN,NaN,,COSTA,Estrato D,No Presencial,8.948965,NaN
42149,2.0,2020,05,51489,0079,Urbano,0.0,NaN,URBANO,18,...,NaN,NaN,NaN,NaN,,COSTA,Estrato D,No Presencial,8.948965,NaN
42150,3.0,2020,08,51548,0026,Urbano,0.0,NaN,URBANO,23,...,NaN,NaN,NaN,NaN,,COSTA,Estrato E más bajo,No Presencial,102.009870,NaN
42151,3.0,2020,08,51548,0046,Urbano,0.0,NaN,URBANO,23,...,NaN,NaN,NaN,NaN,,COSTA,Estrato E más bajo,No Presencial,102.009870,NaN
42152,3.0,2020,08,51548,0066,Urbano,0.0,NaN,URBANO,23,...,NaN,NaN,NaN,NaN,,COSTA,Estrato E más bajo,No Presencial,102.009870,NaN

In [19]:
# select observations
# when we create a sample from our data, copy the object.
df_urban_main = enapres2020_1.loc[ enapres2020_1.AREA == 'URBANO', : ]
df_urban_main

,PER,ANIO,MES,CONGLOMERADO,NSELV,TSELV,VIVREM,NUMVIVREM,AREA,CCDD,...,P189_5,P189_6,P189_7,P189_8,P189_8_O,REGIONNATU,ESTRATO,MOD_ENC,FACTOR,FACTOR_CALIBRADO
1,2.0,2020,09,03981,0120,Urbano,0.0,NaN,URBANO,14,...,NaN,NaN,NaN,NaN,,COSTA,Estrato D,Presencial,245.108050,395.8496
2,2.0,2020,09,03981,0189,Urbano,0.0,NaN,URBANO,14,...,NaN,NaN,NaN,NaN,,COSTA,Estrato D,Presencial,245.108050,395.8496
3,2.0,2020,09,03981,0189,Urbano,0.0,NaN,URBANO,14,...,NaN,NaN,NaN,NaN,,COSTA,Estrato D,Presencial,245.108050,395.8496
6,2.0,2020,09,06703,0037,Urbano,0.0,NaN,URBANO,01,...,NaN,NaN,NaN,NaN,,SELVA,Estrato E más bajo,No Presencial,79.149970,NaN
7,2.0,2020,09,03981,0057,Urbano,0.0,NaN,URBANO,14,...,NaN,NaN,NaN,NaN,,COSTA,Estrato D,Presencial,245.108050,395.8496
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42148,2.0,2020,05,51489,0073,Urbano,0.0,NaN,URBANO,18,...,NaN,NaN,NaN,NaN,,COSTA,Estrato D,No Presencial,8.948965,NaN
42149,2.0,2020,05,51489,0079,Urbano,0.0,NaN,URBANO,18,...,NaN,NaN,NaN,NaN,,COSTA,Estrato D,No Presencial,8.948965,NaN
42150,3.0,2020,08,51548,0026,Urbano,0.0,NaN,URBANO,23,...,NaN,NaN,NaN,NaN,,COSTA,Estrato E más bajo,No Presencial,102.009870,NaN
42151,3.0,2020,08,51548,0046,Urbano,0.0,NaN,URBANO,23,...,NaN,NaN,NaN,NaN,,COSTA,Estrato E más bajo,No Presencial,102.009870,NaN
42152,3.0,2020,08,51548,0066,Urbano,0.0,NaN,URBANO,23,...,NaN,NaN,NaN,NaN,,COSTA,Estrato E más bajo,No Presencial,102.009870,NaN

In [22]:
df_urban_completa = df_urban_main.loc[ df_urban_main.RESFIN == 'Completa', : ]
df_urban_completa

,PER,ANIO,MES,CONGLOMERADO,NSELV,TSELV,VIVREM,NUMVIVREM,AREA,CCDD,...,P189_5,P189_6,P189_7,P189_8,P189_8_O,REGIONNATU,ESTRATO,MOD_ENC,FACTOR,FACTOR_CALIBRADO
1,2.0,2020,09,03981,0120,Urbano,0.0,NaN,URBANO,14,...,NaN,NaN,NaN,NaN,,COSTA,Estrato D,Presencial,245.108050,395.8496
2,2.0,2020,09,03981,0189,Urbano,0.0,NaN,URBANO,14,...,NaN,NaN,NaN,NaN,,COSTA,Estrato D,Presencial,245.108050,395.8496
3,2.0,2020,09,03981,0189,Urbano,0.0,NaN,URBANO,14,...,NaN,NaN,NaN,NaN,,COSTA,Estrato D,Presencial,245.108050,395.8496
6,2.0,2020,09,06703,0037,Urbano,0.0,NaN,URBANO,01,...,NaN,NaN,NaN,NaN,,SELVA,Estrato E más bajo,No Presencial,79.149970,NaN
7,2.0,2020,09,03981,0057,Urbano,0.0,NaN,URBANO,14,...,NaN,NaN,NaN,NaN,,COSTA,Estrato D,Presencial,245.108050,395.8496
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42148,2.0,2020,05,51489,0073,Urbano,0.0,NaN,URBANO,18,...,NaN,NaN,NaN,NaN,,COSTA,Estrato D,No Presencial,8.948965,NaN
42149,2.0,2020,05,51489,0079,Urbano,0.0,NaN,URBANO,18,...,NaN,NaN,NaN,NaN,,COSTA,Estrato D,No Presencial,8.948965,NaN
42150,3.0,2020,08,51548,0026,Urbano,0.0,NaN,URBANO,23,...,NaN,NaN,NaN,NaN,,COSTA,Estrato E más bajo,No Presencial,102.009870,NaN
42151,3.0,2020,08,51548,0046,Urbano,0.0,NaN,URBANO,23,...,NaN,NaN,NaN,NaN,,COSTA,Estrato E más bajo,No Presencial,102.009870,NaN
42152,3.0,2020,08,51548,0066,Urbano,0.0,NaN,URBANO,23,...,NaN,NaN,NaN,NaN,,COSTA,Estrato E más bajo,No Presencial,102.009870,NaN

In [26]:
enapres2020_1.loc[ (enapres2020_1.AREA == 'URBANO') & (enapres2020_1.RESFIN == 'Completa') ]

,PER,ANIO,MES,CONGLOMERADO,NSELV,TSELV,VIVREM,NUMVIVREM,AREA,CCDD,...,P189_5,P189_6,P189_7,P189_8,P189_8_O,REGIONNATU,ESTRATO,MOD_ENC,FACTOR,FACTOR_CALIBRADO
1,2.0,2020,09,03981,0120,Urbano,0.0,NaN,URBANO,14,...,NaN,NaN,NaN,NaN,,COSTA,Estrato D,Presencial,245.108050,395.8496
2,2.0,2020,09,03981,0189,Urbano,0.0,NaN,URBANO,14,...,NaN,NaN,NaN,NaN,,COSTA,Estrato D,Presencial,245.108050,395.8496
3,2.0,2020,09,03981,0189,Urbano,0.0,NaN,URBANO,14,...,NaN,NaN,NaN,NaN,,COSTA,Estrato D,Presencial,245.108050,395.8496
6,2.0,2020,09,06703,0037,Urbano,0.0,NaN,URBANO,01,...,NaN,NaN,NaN,NaN,,SELVA,Estrato E más bajo,No Presencial,79.149970,NaN
7,2.0,2020,09,03981,0057,Urbano,0.0,NaN,URBANO,14,...,NaN,NaN,NaN,NaN,,COSTA,Estrato D,Presencial,245.108050,395.8496
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42148,2.0,2020,05,51489,0073,Urbano,0.0,NaN,URBANO,18,...,NaN,NaN,NaN,NaN,,COSTA,Estrato D,No Presencial,8.948965,NaN
42149,2.0,2020,05,51489,0079,Urbano,0.0,NaN,URBANO,18,...,NaN,NaN,NaN,NaN,,COSTA,Estrato D,No Presencial,8.948965,NaN
42150,3.0,2020,08,51548,0026,Urbano,0.0,NaN,URBANO,23,...,NaN,NaN,NaN,NaN,,COSTA,Estrato E más bajo,No Presencial,102.009870,NaN
42151,3.0,2020,08,51548,0046,Urbano,0.0,NaN,URBANO,23,...,NaN,NaN,NaN,NaN,,COSTA,Estrato E más bajo,No Presencial,102.009870,NaN
42152,3.0,2020,08,51548,0066,Urbano,0.0,NaN,URBANO,23,...,NaN,NaN,NaN,NaN,,COSTA,Estrato E más bajo,No Presencial,102.009870,NaN

In [27]:
df_urb_compl = enapres2020_1.loc[ (enapres2020_1.AREA == 'URBANO') &  (enapres2020_1.RESFIN == 'Completa') , : ]
df_urb_compl

,PER,ANIO,MES,CONGLOMERADO,NSELV,TSELV,VIVREM,NUMVIVREM,AREA,CCDD,...,P189_5,P189_6,P189_7,P189_8,P189_8_O,REGIONNATU,ESTRATO,MOD_ENC,FACTOR,FACTOR_CALIBRADO
1,2.0,2020,09,03981,0120,Urbano,0.0,NaN,URBANO,14,...,NaN,NaN,NaN,NaN,,COSTA,Estrato D,Presencial,245.108050,395.8496
2,2.0,2020,09,03981,0189,Urbano,0.0,NaN,URBANO,14,...,NaN,NaN,NaN,NaN,,COSTA,Estrato D,Presencial,245.108050,395.8496
3,2.0,2020,09,03981,0189,Urbano,0.0,NaN,URBANO,14,...,NaN,NaN,NaN,NaN,,COSTA,Estrato D,Presencial,245.108050,395.8496
6,2.0,2020,09,06703,0037,Urbano,0.0,NaN,URBANO,01,...,NaN,NaN,NaN,NaN,,SELVA,Estrato E más bajo,No Presencial,79.149970,NaN
7,2.0,2020,09,03981,0057,Urbano,0.0,NaN,URBANO,14,...,NaN,NaN,NaN,NaN,,COSTA,Estrato D,Presencial,245.108050,395.8496
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42148,2.0,2020,05,51489,0073,Urbano,0.0,NaN,URBANO,18,...,NaN,NaN,NaN,NaN,,COSTA,Estrato D,No Presencial,8.948965,NaN
42149,2.0,2020,05,51489,0079,Urbano,0.0,NaN,URBANO,18,...,NaN,NaN,NaN,NaN,,COSTA,Estrato D,No Presencial,8.948965,NaN
42150,3.0,2020,08,51548,0026,Urbano,0.0,NaN,URBANO,23,...,NaN,NaN,NaN,NaN,,COSTA,Estrato E más bajo,No Presencial,102.009870,NaN
42151,3.0,2020,08,51548,0046,Urbano,0.0,NaN,URBANO,23,...,NaN,NaN,NaN,NaN,,COSTA,Estrato E más bajo,No Presencial,102.009870,NaN
42152,3.0,2020,08,51548,0066,Urbano,0.0,NaN,URBANO,23,...,NaN,NaN,NaN,NaN,,COSTA,Estrato E más bajo,No Presencial,102.009870,NaN

In [79]:
# We will work on this variable
df_urban.attrs[ 'var_labels' ]['P172D']

'¿USTED O ALGÚN MIEMBRO DE SU HOGAR SEPARA LOS RESIDUOS GENERADOS EN SU HOGAR?'

In [80]:
df_urban.columns

Index(['PER', 'ANIO', 'MES', 'CONGLOMERADO', 'NSELV', 'TSELV', 'VIVREM',
       'NUMVIVREM', 'AREA', 'CCDD',
       ...
       'P189_5', 'P189_6', 'P189_7', 'P189_8', 'P189_8_O', 'REGIONNATU',
       'ESTRATO', 'MOD_ENC', 'FACTOR', 'FACTOR_CALIBRADO'],
      dtype='object', length=491)

In [ ]:
P172

In [31]:
# Select columns with regex
# All the columns that start with P172
df_urban.filter( regex = "P172*").columns

Index(['P172B_1', 'P172C_1', 'P172B_2', 'P172C_2', 'P172D', 'P172E_1',
       'P172F_1_1', 'P172F_1_2', 'P172F_1_3', 'P172F_1_4', 'P172F_1_5',
       'P172F_1_6', 'P172F_1_6_O', 'P172E_2', 'P172F_2_1', 'P172F_2_2',
       'P172F_2_3', 'P172F_2_4', 'P172F_2_5', 'P172F_2_6', 'P172F_2_6_O',
       'P172E_3', 'P172F_3_1', 'P172F_3_2', 'P172F_3_3', 'P172F_3_4',
       'P172F_3_5', 'P172F_3_6', 'P172F_3_6_O', 'P172E_4', 'P172F_4_1',
       'P172F_4_2', 'P172F_4_3', 'P172F_4_4', 'P172F_4_5', 'P172F_4_6',
       'P172F_4_6_O', 'P172E_5', 'P172F_5_1', 'P172F_5_2', 'P172F_5_3',
       'P172F_5_4', 'P172F_5_5', 'P172F_5_6', 'P172F_5_6_O', 'P172E_6',
       'P172F_6_1', 'P172F_6_2', 'P172F_6_3', 'P172F_6_4', 'P172F_6_5',
       'P172F_6_6', 'P172F_6_6_O', 'P172E_7', 'P172E_7_O', 'P172F_7_1',
       'P172F_7_2', 'P172F_7_3', 'P172F_7_4', 'P172F_7_5', 'P172F_7_6',
       'P172F_7_6_O', 'P172G', 'P172H_1', 'P172H_2', 'P172H_3', 'P172H_4',
       'P172H_5', 'P172H_6', 'P172H_7', 'P172H_8', 'P172H_8_O', 'P178_1',
       'P178_2', 'P178_3', 'P178_4', 'P178_5', 'P178_6', 'P178_7', 'P179'],
      dtype='object')

In [32]:
# all columns that have an X
df_urban.filter( like = "P172")

,P172B_1,P172C_1,P172B_2,P172C_2,P172D,P172E_1,P172F_1_1,P172F_1_2,P172F_1_3,P172F_1_4,...,P172G,P172H_1,P172H_2,P172H_3,P172H_4,P172H_5,P172H_6,P172H_7,P172H_8,P172H_8_O
1,No,NaN,1.0,Insatisfecho/a?,Si,No,NaN,NaN,NaN,NaN,...,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
2,No,NaN,1.0,Insatisfecho/a?,Si,No,NaN,NaN,NaN,NaN,...,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
3,No,NaN,1.0,Insatisfecho/a?,Si,Si,Pase,Pase,A un reciclador informal,Pase,...,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
6,Si,Insatisfecho/a?,1.0,Insatisfecho/a?,Si,No,NaN,NaN,NaN,NaN,...,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
7,No,NaN,1.0,Insatisfecho/a?,Si,Si,Pase,Pase,A un reciclador informal,Pase,...,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42148,No,NaN,1.0,Insatisfecho/a?,Si,Si,Pase,Pase,A un reciclador informal,Pase,...,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
42149,No,NaN,1.0,Muy insatisfecho/a?,Si,Si,Pase,Pase,A un reciclador informal,Pase,...,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
42150,No,NaN,1.0,Insatisfecho/a?,No,NaN,NaN,NaN,NaN,NaN,...,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
42151,No,NaN,1.0,Satisfecho/a?,Si,No,NaN,NaN,NaN,NaN,...,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
42152,No,NaN,1.0,Insatisfecho/a?,No,NaN,NaN,NaN,NaN,NaN,...,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,

### 3.3.6. <a id='3.3.6'>Dealing with nulls</a>

We drop columns that at least 30% values are null to simplify our Exploratory Data Analysis (EDA).

In [35]:
df_urban

,PER,ANIO,MES,CONGLOMERADO,NSELV,TSELV,VIVREM,NUMVIVREM,AREA,CCDD,...,P189_5,P189_6,P189_7,P189_8,P189_8_O,REGIONNATU,ESTRATO,MOD_ENC,FACTOR,FACTOR_CALIBRADO
1,2.0,2020,09,03981,0120,Urbano,0.0,NaN,URBANO,14,...,NaN,NaN,NaN,NaN,,COSTA,Estrato D,Presencial,245.108050,395.8496
2,2.0,2020,09,03981,0189,Urbano,0.0,NaN,URBANO,14,...,NaN,NaN,NaN,NaN,,COSTA,Estrato D,Presencial,245.108050,395.8496
3,2.0,2020,09,03981,0189,Urbano,0.0,NaN,URBANO,14,...,NaN,NaN,NaN,NaN,,COSTA,Estrato D,Presencial,245.108050,395.8496
6,2.0,2020,09,06703,0037,Urbano,0.0,NaN,URBANO,01,...,NaN,NaN,NaN,NaN,,SELVA,Estrato E más bajo,No Presencial,79.149970,NaN
7,2.0,2020,09,03981,0057,Urbano,0.0,NaN,URBANO,14,...,NaN,NaN,NaN,NaN,,COSTA,Estrato D,Presencial,245.108050,395.8496
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42148,2.0,2020,05,51489,0073,Urbano,0.0,NaN,URBANO,18,...,NaN,NaN,NaN,NaN,,COSTA,Estrato D,No Presencial,8.948965,NaN
42149,2.0,2020,05,51489,0079,Urbano,0.0,NaN,URBANO,18,...,NaN,NaN,NaN,NaN,,COSTA,Estrato D,No Presencial,8.948965,NaN
42150,3.0,2020,08,51548,0026,Urbano,0.0,NaN,URBANO,23,...,NaN,NaN,NaN,NaN,,COSTA,Estrato E más bajo,No Presencial,102.009870,NaN
42151,3.0,2020,08,51548,0046,Urbano,0.0,NaN,URBANO,23,...,NaN,NaN,NaN,NaN,,COSTA,Estrato E más bajo,No Presencial,102.009870,NaN
42152,3.0,2020,08,51548,0066,Urbano,0.0,NaN,URBANO,23,...,NaN,NaN,NaN,NaN,,COSTA,Estrato E más bajo,No Presencial,102.009870,NaN

In [34]:
df_urban.isnull()

,PER,ANIO,MES,CONGLOMERADO,NSELV,TSELV,VIVREM,NUMVIVREM,AREA,CCDD,...,P189_5,P189_6,P189_7,P189_8,P189_8_O,REGIONNATU,ESTRATO,MOD_ENC,FACTOR,FACTOR_CALIBRADO
1,False,False,False,False,False,False,False,True,False,False,...,True,True,True,True,False,False,False,False,False,False
2,False,False,False,False,False,False,False,True,False,False,...,True,True,True,True,False,False,False,False,False,False
3,False,False,False,False,False,False,False,True,False,False,...,True,True,True,True,False,False,False,False,False,False
6,False,False,False,False,False,False,False,True,False,False,...,True,True,True,True,False,False,False,False,False,True
7,False,False,False,False,False,False,False,True,False,False,...,True,True,True,True,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42148,False,False,False,False,False,False,False,True,False,False,...,True,True,True,True,False,False,False,False,False,True
42149,False,False,False,False,False,False,False,True,False,False,...,True,True,True,True,False,False,False,False,False,True
42150,False,False,False,False,False,False,False,True,False,False,...,True,True,True,True,False,False,False,False,False,True
42151,False,False,False,False,False,False,False,True,False,False,...,True,True,True,True,False,False,False,False,False,True
42152,False,False,False,False,False,False,False,True,False,False,...,True,True,True,True,False,False,False,False,False,True

In [36]:
df_urban.isnull().sum()

PER                     0
ANIO                    0
MES                     0
CONGLOMERADO            0
NSELV                   0
                    ...
REGIONNATU              0
ESTRATO                 0
MOD_ENC                 0
FACTOR                  0
FACTOR_CALIBRADO    12230
Length: 491, dtype: int64

In [37]:
null_sum = df_urban.isnull().sum()
null_sum

PER                     0
ANIO                    0
MES                     0
CONGLOMERADO            0
NSELV                   0
                    ...
REGIONNATU              0
ESTRATO                 0
MOD_ENC                 0
FACTOR                  0
FACTOR_CALIBRADO    12230
Length: 491, dtype: int64

In [40]:
len( df_urban ) * 0.3

7304.099999999999

In [38]:
df_urban.columns[ null_sum < len( df_urban ) * 0.3 ]

Index(['PER', 'ANIO', 'MES', 'CONGLOMERADO', 'NSELV', 'TSELV', 'VIVREM',
       'AREA', 'CCDD', 'NOMBREDD',
       ...
       'P184A_15', 'P184A_16', 'P184A_17', 'P184A_18', 'P187_9_O', 'P189_8_O',
       'REGIONNATU', 'ESTRATO', 'MOD_ENC', 'FACTOR'],
      dtype='object', length=120)

In [39]:
df_urban

,PER,ANIO,MES,CONGLOMERADO,NSELV,TSELV,VIVREM,NUMVIVREM,AREA,CCDD,...,P189_5,P189_6,P189_7,P189_8,P189_8_O,REGIONNATU,ESTRATO,MOD_ENC,FACTOR,FACTOR_CALIBRADO
1,2.0,2020,09,03981,0120,Urbano,0.0,NaN,URBANO,14,...,NaN,NaN,NaN,NaN,,COSTA,Estrato D,Presencial,245.108050,395.8496
2,2.0,2020,09,03981,0189,Urbano,0.0,NaN,URBANO,14,...,NaN,NaN,NaN,NaN,,COSTA,Estrato D,Presencial,245.108050,395.8496
3,2.0,2020,09,03981,0189,Urbano,0.0,NaN,URBANO,14,...,NaN,NaN,NaN,NaN,,COSTA,Estrato D,Presencial,245.108050,395.8496
6,2.0,2020,09,06703,0037,Urbano,0.0,NaN,URBANO,01,...,NaN,NaN,NaN,NaN,,SELVA,Estrato E más bajo,No Presencial,79.149970,NaN
7,2.0,2020,09,03981,0057,Urbano,0.0,NaN,URBANO,14,...,NaN,NaN,NaN,NaN,,COSTA,Estrato D,Presencial,245.108050,395.8496
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42148,2.0,2020,05,51489,0073,Urbano,0.0,NaN,URBANO,18,...,NaN,NaN,NaN,NaN,,COSTA,Estrato D,No Presencial,8.948965,NaN
42149,2.0,2020,05,51489,0079,Urbano,0.0,NaN,URBANO,18,...,NaN,NaN,NaN,NaN,,COSTA,Estrato D,No Presencial,8.948965,NaN
42150,3.0,2020,08,51548,0026,Urbano,0.0,NaN,URBANO,23,...,NaN,NaN,NaN,NaN,,COSTA,Estrato E más bajo,No Presencial,102.009870,NaN
42151,3.0,2020,08,51548,0046,Urbano,0.0,NaN,URBANO,23,...,NaN,NaN,NaN,NaN,,COSTA,Estrato E más bajo,No Presencial,102.009870,NaN
42152,3.0,2020,08,51548,0066,Urbano,0.0,NaN,URBANO,23,...,NaN,NaN,NaN,NaN,,COSTA,Estrato E más bajo,No Presencial,102.009870,NaN

In [41]:
df_urban.drop(columns = df_urban.columns[null_sum > len( df_urban ) * 0.3 ], inplace = True )
df_urban

C:\Users\ALEXAN~1\AppData\Local\Temp/ipykernel_20560/2430473974.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_urban.drop(columns = df_urban.columns[null_sum > len( df_urban ) * 0.3 ], inplace = True )

,PER,ANIO,MES,CONGLOMERADO,NSELV,TSELV,VIVREM,AREA,CCDD,NOMBREDD,...,P184A_15,P184A_16,P184A_17,P184A_18,P187_9_O,P189_8_O,REGIONNATU,ESTRATO,MOD_ENC,FACTOR
1,2.0,2020,09,03981,0120,Urbano,0.0,URBANO,14,LAMBAYEQUE,...,Pase,Pase,Pase,Pase,,,COSTA,Estrato D,Presencial,245.108050
2,2.0,2020,09,03981,0189,Urbano,0.0,URBANO,14,LAMBAYEQUE,...,Pase,Pase,Pase,Pase,,,COSTA,Estrato D,Presencial,245.108050
3,2.0,2020,09,03981,0189,Urbano,0.0,URBANO,14,LAMBAYEQUE,...,Pase,Pase,Pase,Pase,,,COSTA,Estrato D,Presencial,245.108050
6,2.0,2020,09,06703,0037,Urbano,0.0,URBANO,01,AMAZONAS,...,Pase,¿Motocicleta?,Pase,Pase,,,SELVA,Estrato E más bajo,No Presencial,79.149970
7,2.0,2020,09,03981,0057,Urbano,0.0,URBANO,14,LAMBAYEQUE,...,Pase,Pase,Pase,Pase,,,COSTA,Estrato D,Presencial,245.108050
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42148,2.0,2020,05,51489,0073,Urbano,0.0,URBANO,18,MOQUEGUA,...,Pase,Pase,Pase,Pase,,,COSTA,Estrato D,No Presencial,8.948965
42149,2.0,2020,05,51489,0079,Urbano,0.0,URBANO,18,MOQUEGUA,...,Pase,Pase,Pase,Pase,,,COSTA,Estrato D,No Presencial,8.948965
42150,3.0,2020,08,51548,0026,Urbano,0.0,URBANO,23,TACNA,...,Pase,Pase,Pase,Pase,,,COSTA,Estrato E más bajo,No Presencial,102.009870
42151,3.0,2020,08,51548,0046,Urbano,0.0,URBANO,23,TACNA,...,Pase,Pase,Pase,Pase,,,COSTA,Estrato E más bajo,No Presencial,102.009870
42152,3.0,2020,08,51548,0066,Urbano,0.0,URBANO,23,TACNA,...,Pase,Pase,Pase,Pase,,,COSTA,Estrato E más bajo,No Presencial,102.009870

In [86]:
df_urban.attrs['var_labels']

{'PER': 'PERIODO',
 'ANIO': 'AÑO',
 'MES': 'MES DE LA ENCUESTA',
 'CONGLOMERADO': 'N° de conglomerado',
 'NSELV': 'Nº de selección de la vivienda',
 'TSELV': 'Tipo de selección de la vivienda',
 'VIVREM': '¿Es una vivienda de reemplazo?',
 'NUMVIVREM': 'Anote el número de selección de la vivienda reemplazada',
 'AREA': 'AREA',
 'CCDD': 'Código de Departamento',
 'NOMBREDD': 'Nombre de Departamento',
 'CCPP': 'Código de Provincia',
 'NOMBREPP': 'Nombre de la Provincia',
 'CCDI': 'Código del Distrito',
 'NOMBREDI': 'Nombre del Distrito',
 'VIVIENDA': 'N° de Vivienda',
 'TOT_HOGAR': '¿Cuántos hogares ocupa esta vivienda?',
 'HOGAR': 'Hogar N°',
 'RESFIN': 'Resultado final del hogar',
 'P100_C': 'INFORMANTE N°',
 'P101': 'TIPO DE VIVIENDA',
 'P101_O': 'TIPO DE VIVIENDA: ESPECIFIQUE',
 'P102A': 'EN LA VIVIENDA, ¿EL MATERIAL DE CONSTRUCCIÓN PREDOMINANTE EN LAS PAREDES EXTERIORES ES DE:',
 'P102A_O': 'EN LA VIVIENDA, ¿EL MATERIAL DE CONSTRUCCIÓN PREDOMINANTE EN LAS PAREDES EXTERIORES ES DE: Otros materiales Especifique',
 'P103': 'EL MATERIAL PREDOMINANTE EN LOS PISOS DE LA VIVIENDA ES',
 'P103_O': 'EL MATERIAL PREDOMINANTE EN LOS PISOS DE LA VIVIENDA ES: ESPECIFIQUE',
 'P104B': 'EN LA VIVIENDA,  ¿EL MATERIAL DE CONSTRUCCIÓN PREDOMINANTE EN LOS TECHOS ES DE:',
 'P104B_O': 'EN LA VIVIENDA,  ¿EL MATERIAL DE CONSTRUCCIÓN PREDOMINANTE EN LOS TECHOS ES DE: Otro maaterial Especifique',
 'P105': '¿CUÁNTAS HABITACIONES EN TOTAL TIENE LA VIVIENDA, SIN CONTAR EL BAÑO, LA COCINA, LOS PASADIZOS, NI EL GARAJE?',
 'P106': 'LA VIVIENDA QUE OCUPA ES:',
 'P106_O': 'LA VIVIENDA QUE OCUPA ES: ESPECIFIQUE',
 'P106A': '¿DESDE QUE AÑO VIVEN EN ESTA VIVIENDA?',
 'P107': '¿LA VIVIENDA CUENTA CON ALGÙN DOCUMENTO QUE ACREDITE LA PROPIEDAD?',
 'P107A': '¿QUÉ TIPO DE DOCUMENTO ACREDITA EL DERECHO DE PROPIEDAD DE LA VIVIENDA?',
 'P107A_O': '¿QUÉ TIPO DE DOCUMENTO ACREDITA EL DERECHO DE PROPIEDAD DE LA VIVIENDA?_ESPECIFIQUE',
 'P107B': '¿QUÉ ENTIDAD O AUTORIDAD LE EMITIÓ EL/LA …...?',
 'P107B_O': '¿QUÉ ENTIDAD O AUTORIDAD LE EMITIÓ EL/LA …...?_ESPECIFIQUE',
 'P107C': '¿EL/LA ……ESTÁ A NOMBRE DE ALGÚN MIEMBRO DEL HOGAR DE ESTA VIVIENDA?',
 'P108': '¿EL/LA …… DE ESTA VIVIENDA ESTÀ REGISTRADO EN LOS REGISTROS PÚBLICOS?',
 'P108_1': '¿CUÁL ES EL PRINCIPAL MOTIVO POR EL CUAL NO REGISTRO EL/LA…?',
 'P108_1_O': '¿CUÁL ES EL PRINCIPAL MOTIVO POR EL CUAL NO REGISTRO EL/LA…?_ESPECIFIQUE',
 'P108A': 'LA CONSTRUCCIÓN DE ESTA VIVIENDA, ¿ESTÁ REGISTRADA EN LOS REGISTROS PÚBLICOS?',
 'P108B': '¿CUÁL ES EL PRINCIPAL MOTIVO POR EL CUAL NO REGISTRO LA CONSTRUCCIÓN?',
 'P108B_O': '¿CUÁL ES EL PRINCIPAL MOTIVO POR EL CUAL NO REGISTRO LA CONSTRUCCIÓN?_ESPECIFIQUE',
 'P109': '¿LA VIVIENDA TIENE ALUMBRADO ELÉCTRICO POR RED PÚBLICA?',
 'P110A': '¿LA VIVIENDA TIENE ACCESO AL SERVICIO DE LA ENERGÍA ELÉCTRICA POR RED PÚBLICA TODOS LOS DÍAS DE LA SEMANA?',
 'P110AA': '¿CUÁNTAS HORAS AL DÍA?',
 'P110AB': '¿CUÁNTOS DÍAS A LA SEMANA TIENE ESTE SERVICIO?',
 'P110AC': '¿CUÁNTAS HORAS AL DÍA?',
 'P111A': 'EL MES ANTERIOR……., LA VIVIENDA ¿HA TENIDO INTERRUPCIONES O CORTES EN LA ENERGÍA ELÉCTRICA?',
 'P111AA': '¿Cuántas interrupciones o cortes tuvo en el mes anterior…..?',
 'P111AB_HORAS': '¿Cuánto tiempo duró la última interrupción o corte?.....HORAS',
 'P111AB_MINUTOS': '¿Cuánto tiempo duró la última interrupción o corte?.....MINUTOS',
 'P112_1': 'EN LOS ÚLTIMOS 12 MESES ¿HAN SIDO VÍCTIMAS DE:..ROBO EN LA VIVIENDA',
 'P113_1': 'EN LOS ÚLTIMOS 12 MESES ¿CUÁNTAS VECES FUERON VÍCTIMAS DE…ROBO EN LA VIVIENDA:',
 'P113A_1': 'DE ESTAS ……… VECES ¿CUÁNTAS FUERON DENUNCIADAS?....ROBO EN LA VIVIENDA',
 'P113B_1_1': 'DE ESTAS ……¿CUÁNTAS FUERON DENUNCIADAS EN: La Comisaria (Policia Nacional del Peru)....ROBO EN LA VIVIENDA',
 'P113B_1_1_ENT': 'DE ESTAS ……¿CUÁNTAS FUERON DENUNCIADAS EN: La Comisaria (Policia Nacional del Peru)_Nro DE VECES....ROBO EN LA VIVIENDA',
 'P113B_1_2': 'DE ESTAS ……¿CUÁNTAS FUERON DENUNCIADAS EN:  El Ministerio Publico o Fiscalia?....ROBO EN LA VIVIENDA',
 'P113B_1_2_ENT': 'DE ESTAS ……¿CUÁNTAS FUERON DENUNCIADAS EN:  El Ministerio Publico o Fiscalia?_Nro DE VECES....ROBO EN LA VIVIENDA',
 'P113B_1_3': 'DE ESTAS ……¿CUÁNTAS FUERON DENUNCIADAS EN: Otro?....ROBO EN LA VIVIENDA',
 'P113B_1_3_ENT': 'DE ESTAS ……¿CUÁNTAS FUERON DENUNCIADAS EN: Otro?_Nro DE VECES....ROBO EN LA VIVIENDA',
 'P113B_1_3_O': 'DE ESTAS ……¿CUÁNTAS FUERON DENUNCIADAS EN: Otro?.....ROBO EN LA VIVIENDA_OTRO/ESPECIFIQUE',
 'P117_1': '¿DENUNCIÓ EL: ROBO EN LA VIVIENDA?',
 'P118_1': '¿DÓNDE REALIZÓ LA DENUNCIA DEL? ROBO EN LA VIVIENDA',
 'P118_1_O': '¿DONDE REALIZÓ LA DENUNCIA DEL? ROBO EN LA VIVIENDA_OTRO/ESPECIFIQUE',
 'P119_1': '¿QUÉ SUCEDIÓ CON SU DENUNCIA ? ROBO EN LA VIVIENDA',
 'P119_1_O': '¿QUÉ SUCEDIÓ CON SU DENUNCIA ?…ROBO EN LA VIVIENDA_OTRO/ESPECIFIQUE',
 'P121_1': '¿CUÁL FUE EL MOTIVO PRINCIPAL POR EL CUAL NO REALIZÓ LA DENUNCIA?…ROBO EN LA VIVIENDA',
 'P121_1_O': '¿CUÁL FUE EL MOTIVO PRINCIPAL POR EL CUAL NO REALIZÓ LA DENUNCIA?…ROBO EN LA VIVIENDA_OTRO/ESPECIFIQUE',
 'P115_1': 'EL DELINCUENTE / AGRESOR PORTABA ALGÚN ARMA (REVÓLVER, PISTOLA, PIEDRAS, PALOS, ETC.)…ROBO EN LA VIVIENDA',
 'P116_1_1': '¿QUÉ TIPO DE ARMA PORTABA? ROBO EN LA VIVIENDA Armas de fuego de mano (revólver, pistola u otro)',
 'P116_1_2': '¿QUÉ TIPO DE ARMA PORTABA? ROBO EN LA VIVIENDA Armas de fuego largo (escopeta, rifle, ametralladora)',
 'P116_1_3': '¿QUÉ TIPO DE ARMA PORTABA? ROBO EN LA VIVIENDA Arma blanca (cuchillo, objeto punzo cortante)',
 'P116_1_4': '¿QUÉ TIPO DE ARMA PORTABA? ROBO EN LA VIVIENDA Objetos contundentes (palos, piedras, etc.)',
 'P116_1_5': '¿QUÉ TIPO DE ARMA PORTABA? ROBO EN LA VIVIENDA Otro',
 'P116_1_5_O': '¿QUÉ TIPO DE ARMA PORTABA? ROBO EN LA VIVIENDA Otro _ESPECIFIQUE',
 'P121A_1': '¿EN QUÉ MES SUCEDIÓ EL ROBO EN LA VIVIENDA?',
 'P121B_1': '¿EL/LA  ROBO EN LA VIVIENDA OCURRIÓ UN:...',
 'P121C_1': '¿EL/LOS DELINCUENTE/S UTILIZARON ALGÚN MEDIO DE TRANSPORTE PARA MOVILIZARSE?',
 'P121D_1_1': '¿Qué MEDIO DE TRANSPORTE UTILIZÓ O UTILIZARÓN? Auto/camioneta',
 'P121D_1_2': '¿Qué MEDIO DE TRANSPORTE UTILIZÓ O UTILIZARÓN? Motocicleta',
 'P121D_1_3': '¿Qué MEDIO DE TRANSPORTE UTILIZÓ O UTILIZARÓN? Mototaxi/Mototriciclo',
 'P121D_1_4': '¿Qué MEDIO DE TRANSPORTE UTILIZÓ O UTILIZARÓN? Bicicleta',
 'P121D_1_5': '¿Qué MEDIO DE TRANSPORTE UTILIZÓ O UTILIZARÓN? Otro ',
 'P121D_1_5_O': '¿Qué MEDIO DE TRANSPORTE UTILIZÓ O UTILIZARÓN? Otro_Especifique',
 'P112_2': 'EN LOS ÚLTIMOS 12 MESES DE……A……., ¿HAN SIDO VÍCTIMAS DE: INTENTO DE ROBO EN LA VIVIENDA?',
 'P113_2': 'EN LOS ÚLTIMOS 12 MESES DE…….A………., ¿CUANTAS VECES FUERON VÍCTIMAS DE: INTENTO DE ROBO EN LA VIVIENDA?',
 'P113A_2': 'DE ESTAS ……… VECES ¿CUÁNTAS FUERON DENUNCIADAS? ...... INTENTO DE ROBO EN LA VIVIENDA',
 'P113B_2_1': 'DE ESTAS ……¿CUÁNTAS FUERON DENUNCIADAS EN: La Comisaria (Policia Nacional del Peru) ...... INTENTO DE ROBO EN LA VIVIENDA',
 'P113B_2_1_ENT': 'DE ESTAS ……¿CUÁNTAS FUERON DENUNCIADAS EN: La Comisaria (Policia Nacional del Peru)_Nro DE VECES ...... INTENTO DE ROBO EN LA VIVIENDA',
 'P113B_2_2': 'DE ESTAS ……¿CUÁNTAS FUERON DENUNCIADAS EN:  El Ministerio Publico o Fiscalia? ...... INTENTO DE ROBO EN LA VIVIENDA',
 'P113B_2_2_ENT': 'DE ESTAS ……¿CUÁNTAS FUERON DENUNCIADAS EN:  El Ministerio Publico o Fiscalia?_Nro DE VECES ...... INTENTO DE ROBO EN LA VIVIENDA',
 'P113B_2_3': 'DE ESTAS ……¿CUÁNTAS FUERON DENUNCIADAS EN: Otro? ...... INTENTO DE ROBO EN LA VIVIENDA',
 'P113B_2_3_ENT': 'DE ESTAS ……¿CUÁNTAS FUERON DENUNCIADAS EN: Otro?_Nro DE VECES ...... INTENTO DE ROBO EN LA VIVIENDA',
 'P113B_2_3_O': 'DE ESTAS ……¿CUÁNTAS FUERON DENUNCIADAS EN: Otro? ...... INTENTO DE ROBO EN LA VIVIENDA',
 'P117_2': 'DENUNCIÓ EL …INTENTO DE ROBO EN LA VIVIENDA',
 'P118_2': '¿DÓNDE REALIZO LA DENUNCIA ?…INTENTO DE ROBO EN LA VIVIENDA',
 'P118_2_O': '¿DÓNDE REALIZO LA DENUNCIA ?…INTENTO DE ROBO EN LA VIVIENDA_OTRO/ESPECIFIQUE',
 'P119_2': '¿QUÉ SUCEDIÓ CON SU DENUNCIA ?…INTENTO DE ROBO EN LA VIVIENDA',
 'P119_2_O': '¿QUÉ SUCEDIÓ CON SU DENUNCIA ?…INTENTO DE ROBO EN LA VIVIENDA OTRO/ESPECIFIQUE',
 'P121_2': '¿CUÁL FUE EL MOTIVO PRINCIPAL POR EL CUAL NO REALIZÓ LA DENUNCIA?…INTENTO DE ROBO EN LA VIVIENDA',
 'P121_2_O': '¿CUÁL FUE EL MOTIVO PRINCIPAL POR EL CUAL NO REALIZÓ LA DENUNCIA?…INTENTO DE ROBO EN LA VIVIENDA_OTRO/ESPECIFIQUE',
 'P115_2': 'EL DELINCUENTE / AGRESOR PORTABA ALGÚN ARMA (REVÓLVER, PISTOLA, PIEDRAS, PALOS, ETC.)…INTENTO DE ROBO EN LA VIVIENDA',
 'P116_2_1': '¿QUÉ TIPO DE ARMA PORTABA? INTENTO ROBO EN LA VIVIENDA Armas de fuego de mano (revólver, pistola u otro)',
 'P116_2_2': '¿QUÉ TIPO DE ARMA PORTABA? INTENTO ROBO EN LA VIVIENDA Armas de fuego largo (escopeta, rifle, ametralladora)',
 'P116_2_3': '¿QUÉ TIPO DE ARMA PORTABA? INTENTO ROBO EN LA VIVIENDA Arma blanca (cuchillo,objeto punzo cortante)',
 'P116_2_4': '¿QUÉ TIPO DE ARMA PORTABA? INTENTO ROBO EN LA VIVIENDA Objetos contundentes (palos, piedras, etc.) ',
 'P116_2_5': '¿QUÉ TIPO DE ARMA PORTABA? INTENTO ROBO EN LA VIVIENDA Otro',
 'P116_2_5_O': '¿QUÉ TIPO DE ARMA PORTABA? INTENTO ROBO EN LA VIVIENDA Otro _ESPECIFIQUE',
 'P121A_2': '¿EN QUÉ MES SUCEDIÓ EL ….?',
 'P121B_2': '¿EL/LA  INTENTO DE ROBO EN LA VIVIENDA OCURRIÓ UN:...',
 'P121C_2': '¿EL/LOS DELINCUENTE/S UTILIZARON ALGÚN MEDIO DE TRANSPORTE PARA MOVILIZARSE?',
 'P121D_2_1': '¿Qué MEDIO DE TRANSPORTE UTILIZÓ O UTILIZARÓN? Auto/camioneta',
 'P121D_2_2': '¿Qué MEDIO DE TRANSPORTE UTILIZÓ O UTILIZARÓN? Motocicleta',
 'P121D_2_3': '¿Qué MEDIO DE TRANSPORTE UTILIZÓ O UTILIZARÓN? Mototaxi/Mototriciclo',
 'P121D_2_4': '¿Qué MEDIO DE TRANSPORTE UTILIZÓ O UTILIZARÓN? Bicicleta',
 'P121D_2_5': '¿Qué MEDIO DE TRANSPORTE UTILIZÓ O UTILIZARÓN? Otro ',
 'P121D_2_5_O': '¿Qué MEDIO DE TRANSPORTE UTILIZÓ O UTILIZARÓN? Otro_Especifique',
 'P122A_1': 'EN SU ZONA O BARRIO, ¿SE HA ADOPTADO ALGUNA MEDIDA DE SEGURIDAD PARA PREVENIR LA DELINCUENCIA, COMO: Sistema de vigilancia a través de video camaras?',
 'P122A_2': 'EN SU ZONA O BARRIO, ¿SE HA ADOPTADO ALGUNA MEDIDA DE SEGURIDAD PARA PREVENIR LA DELINCUENCIA, COMO: Vigilante particular?',
 'P122A_3': 'EN SU ZONA O BARRIO, ¿SE HA ADOPTADO ALGUNA MEDIDA DE SEGURIDAD PARA PREVENIR LA DELINCUENCIA, COMO: Sistema de alarma comunitaria?',
 'P122A_4': 'EN SU ZONA O BARRIO, ¿SE HA ADOPTADO ALGUNA MEDIDA DE SEGURIDAD PARA PREVENIR LA DELINCUENCIA, COMO: Sistema de control de acceso a personas ajenas al lugar?',
 'P122A_5': 'EN SU ZONA O BARRIO, ¿SE HA ADOPTADO ALGUNA MEDIDA DE SEGURIDAD PARA PREVENIR LA DELINCUENCIA, COMO: Junta vecinal con fines de velar por la seguridad?',
 'P122A_6': 'EN SU ZONA O BARRIO, ¿SE HA ADOPTADO ALGUNA MEDIDA DE SEGURIDAD PARA PREVENIR LA DELINCUENCIA, COMO: Otra?',
 'P122A_6_O': 'EN SU ZONA O BARRIO, ¿SE HA ADOPTADO ALGUNA MEDIDA DE SEGURIDAD PARA PREVENIR LA DELINCUENCIA, COMO: Otra?/Especifique',
 'P122B_1': '¿DESDE QUE AÑO CUENTAN CON EL/LA: Sistema de vigilancia a traves de video camaras?',
 'P122B_2': '¿DESDE QUE AÑO CUENTAN CON EL/LA: Vigilante particular?',
 'P122B_3': '¿DESDE QUE AÑO CUENTAN CON EL/LA: Sistema de alarma comunitaria?',
 'P122B_4': '¿DESDE QUE AÑO CUENTAN CON EL/LA: Sistema de control de acceso a personas ajenas al lugar?',
 'P122B_5': '¿DESDE QUE AÑO CUENTAN CON EL/LA: Junta vecinal con fines de velar por la seguridad?',
 'P122B_6': '¿DESDE QUE AÑO CUENTAN CON EL/LA: Otra?',
 'P122C_1': '¿ESTA MEDIDA LA TOMÓ O SE INSTALÓ DURANTE LOS ÚLTIMOS 12 MESES DE………A ……….? Sistema de vigilancia a traves de video camaras?',
 'P122C_2': '¿ESTA MEDIDA LA TOMÓ O SE INSTALÓ DURANTE LOS ÚLTIMOS 12 MESES DE………A ……….? Vigilante particular?',
 'P122C_3': '¿ESTA MEDIDA LA TOMÓ O SE INSTALÓ DURANTE LOS ÚLTIMOS 12 MESES DE………A ……….? Sistema de alarma comunitaria?',
 'P122C_4': '¿ESTA MEDIDA LA TOMÓ O SE INSTALÓ DURANTE LOS ÚLTIMOS 12 MESES DE………A ……….? Sistema de control de acceso a personas ajenas al lugar?',
 'P122C_5': '¿ESTA MEDIDA LA TOMÓ O SE INSTALÓ DURANTE LOS ÚLTIMOS 12 MESES DE………A ……….? Junta vecinal con fines de velar por la seguridad?',
 'P122C_6': '¿ESTA MEDIDA LA TOMÓ O SE INSTALÓ DURANTE LOS ÚLTIMOS 12 MESES DE………A ……….? Otra?',
 'P122D_1': 'ACTUALMENTE, ¿HAN ADOPTADO ALGUNA MEDIDA DE SEGURIDAD PARA PREVENIR EL ROBO EN SU VIVIENDA COMO: Evitar dejar la casa sola?',
 'P122D_2': 'ACTUALMENTE, ¿HAN ADOPTADO ALGUNA MEDIDA DE SEGURIDAD PARA PREVENIR EL ROBO EN SU VIVIENDA COMO: Colocar o adicionar cerrojos?',
 'P122D_3': 'ACTUALMENTE, ¿HAN ADOPTADO ALGUNA MEDIDA DE SEGURIDAD PARA PREVENIR EL ROBO EN SU VIVIENDA COMO: Colocar o adicionar cerraduras y/o candados?',
 'P122D_4': 'ACTUALMENTE, ¿HAN ADOPTADO ALGUNA MEDIDA DE SEGURIDAD PARA PREVENIR EL ROBO EN SU VIVIENDA COMO: Cambiar cerraduras y/o candados?',
 'P122D_5': 'ACTUALMENTE, ¿HAN ADOPTADO ALGUNA MEDIDA DE SEGURIDAD PARA PREVENIR EL ROBO EN SU VIVIENDA COMO: Tener perro guardián?',
 'P122D_6': 'ACTUALMENTE, ¿HAN ADOPTADO ALGUNA MEDIDA DE SEGURIDAD PARA PREVENIR EL ROBO EN SU VIVIENDA COMO: Poner puerta de rejas?',
 'P122D_7': 'ACTUALMENTE, ¿HAN ADOPTADO ALGUNA MEDIDA DE SEGURIDAD PARA PREVENIR EL ROBO EN SU VIVIENDA COMO: Instalar rejas en las ventanas?',
 'P122D_8': 'ACTUALMENTE, ¿HAN ADOPTADO ALGUNA MEDIDA DE SEGURIDAD PARA PREVENIR EL ROBO EN SU VIVIENDA COMO: Otro?',
 'P122D_O': 'ACTUALMENTE, ¿HAN ADOPTADO ALGUNA MEDIDA DE SEGURIDAD PARA PREVENIR EL ROBO EN SU VIVIENDA COMO: Otro?_Especifique',
 'P122E_1': '122E. ¿DESDE QUÉ AÑO ADOPTÓ ESTA MEDIDA?  Evitar dejar la casa sola?',
 'P122E_2': '122E. ¿DESDE QUÉ AÑO ADOPTÓ ESTA MEDIDA?  Colocar o adicionar cerrojos?',
 'P122E_3': '122E. ¿DESDE QUÉ AÑO ADOPTÓ ESTA MEDIDA?  Colocar o adicionar cerraduras y/o candados?',
 'P122E_4': '122E. ¿DESDE QUÉ AÑO ADOPTÓ ESTA MEDIDA?  Cambiar cerraduras y/o candados?',
 'P122E_5': '122E. ¿DESDE QUÉ AÑO ADOPTÓ ESTA MEDIDA?  Tener perro guardián?',
 'P122E_6': '122E. ¿DESDE QUÉ AÑO ADOPTÓ ESTA MEDIDA?  Poner puerta de rejas?',
 'P122E_7': '122E. ¿DESDE QUÉ AÑO ADOPTÓ ESTA MEDIDA?  Instalar rejas en las ventanas?',
 'P122E_8': '122E. ¿DESDE QUÉ AÑO ADOPTÓ ESTA MEDIDA?  Otro?',
 'P122F_1': '122F. ¿ESTA MEDIDA FUE ADOPTADA O SE INSTALÓ DURANTE LOS ÚLTIMOS 12 MESES DE………A ……….? Evitar dejar la casa sola?',
 'P122F_2': '122F. ¿ESTA MEDIDA FUE ADOPTADA O SE INSTALÓ DURANTE LOS ÚLTIMOS 12 MESES DE………A ……….? Colocar o adicionar cerrojos?',
 'P122F_3': '122F. ¿ESTA MEDIDA FUE ADOPTADA O SE INSTALÓ DURANTE LOS ÚLTIMOS 12 MESES DE………A ……….? Colocar o adicionar cerraduras y/o candados?',
 'P122F_4': '122F. ¿ESTA MEDIDA FUE ADOPTADA O SE INSTALÓ DURANTE LOS ÚLTIMOS 12 MESES DE………A ……….? Cambiar cerraduras y/o candados?',
 'P122F_5': '122F. ¿ESTA MEDIDA FUE ADOPTADA O SE INSTALÓ DURANTE LOS ÚLTIMOS 12 MESES DE………A ……….? Tener perro guardián?',
 'P122F_6': '122F. ¿ESTA MEDIDA FUE ADOPTADA O SE INSTALÓ DURANTE LOS ÚLTIMOS 12 MESES DE………A ……….? Poner puerta de rejas?',
 'P122F_7': '122F. ¿ESTA MEDIDA FUE ADOPTADA O SE INSTALÓ DURANTE LOS ÚLTIMOS 12 MESES DE………A ……….? Instalar rejas en las ventanas?',
 'P122F_8': '122F. ¿ESTA MEDIDA FUE ADOPTADA O SE INSTALÓ DURANTE LOS ÚLTIMOS 12 MESES DE………A ……….? Otro?',
 'P123': '¿EN SU CENTRO POBLADO EXISTE EL SERVICIO DE INTERNET EN CABINA PÚBLICA?',
 'P124': '¿EN SU CENTRO POBLADO EXISTEN INSTALACIONES PARA BRINDAR EL SERVICIO DE TELEFONÍA PÚBLICA?',
 'P125': '¿EN SU CENTRO POBLADO EXISTE SEÑAL DE TELEFONÍA CELULAR?',
 'P126': '¿TIENE QUE SALIR DE SU VIVIENDA PARA ENCONTRAR SEÑAL?',
 'P127_1': '¿CUAL ES EL TIPO DE ALUMBRADO QUE USA SU HOGAR:_ELECTRICIDAD',
 'P127_2': '¿CUAL ES EL TIPO DE ALUMBRADO QUE USA SU HOGAR:_PETROLEO GAS (Lámpara)',
 'P127_3': '¿CUAL ES EL TIPO DE ALUMBRADO QUE USA SU HOGAR:_VELA',
 'P127_4': '¿CUAL ES EL TIPO DE ALUMBRADO QUE USA SU HOGAR:_GENERADOR',
 'P127_5': '¿CUAL ES EL TIPO DE ALUMBRADO QUE USA SU HOGAR:_PANEL SOLAR',
 'P127_6': '¿CUAL ES EL TIPO DE ALUMBRADO QUE USA SU HOGAR:_OTRO',
 'P127_6_O': '¿CUAL ES EL TIPO DE ALUMBRADO QUE USA SU HOGAR:_OTRO/ESPECIFIQUE',
 'P128A_1': 'EN SU HOGAR, ¿LA ENERGÍA O COMBUSTIBLE QUE UTILIZA PARA COCINAR LOS ALIMENTOS ES: (Circule uno o más códigos) Electricidad?',
 'P128A_2': 'EN SU HOGAR, ¿LA ENERGÍA O COMBUSTIBLE QUE UTILIZA PARA COCINAR LOS ALIMENTOS ES: (Circule uno o más códigos) Gas (balón GLP)?',
 'P128A_3': 'EN SU HOGAR, ¿LA ENERGÍA O COMBUSTIBLE QUE UTILIZA PARA COCINAR LOS ALIMENTOS ES: (Circule uno o más códigos) .Gas natural (sistema de tuberías)?',
 'P128A_4': 'EN SU HOGAR, ¿LA ENERGÍA O COMBUSTIBLE QUE UTILIZA PARA COCINAR LOS ALIMENTOS ES: (Circule uno o más códigos) .Carbón?',
 'P128A_5': 'EN SU HOGAR, ¿LA ENERGÍA O COMBUSTIBLE QUE UTILIZA PARA COCINAR LOS ALIMENTOS ES: (Circule uno o más códigos) 5.Leña?',
 'P128A_6': 'EN SU HOGAR, ¿LA ENERGÍA O COMBUSTIBLE QUE UTILIZA PARA COCINAR LOS ALIMENTOS ES: (Circule uno o más códigos) .Bosta, estiércol?',
 'P128A_7': 'EN SU HOGAR, ¿LA ENERGÍA O COMBUSTIBLE QUE UTILIZA PARA COCINAR LOS ALIMENTOS ES: (Circule uno o más códigos) .Otro (residuos agrícolas, etc)?',
 'P128A_8': 'EN SU HOGAR, ¿LA ENERGÍA O COMBUSTIBLE QUE UTILIZA PARA COCINAR LOS ALIMENTOS ES: (Circule uno o más códigos) NO COCINAN',
 'P128A_O': 'EN SU HOGAR, ¿LA ENERGÍA O COMBUSTIBLE QUE UTILIZA PARA COCINAR LOS ALIMENTOS ES: OTRO/ESPECIFIQUE',
 'P129G': 'EL AGUA QUE UTILIZAN EN EL HOGAR, ¿PROCEDE PRINCIPALMENTE DE: ',
 'P129G_O': 'EL AGUA QUE UTILIZAN EN EL HOGAR, ¿PROCEDE PRINCIPALMENTE DE: Otro Especifique',
 'P129B': '¿EL AGUA ES POTABLE?',
 'P129C': 'RESULTADO OBTENIDO EN LA EVALUACIÓN DE LOS NIVELES DE CLORO RESIDUAL LIBRE EN LA MUESTRA DE AGUA DEL HOGAR',
 'P100_C_2': 'INFORMANTE DE LA PRUEBA DEL AGUA',
 'P129D_ENT': 'RESULTADO OBTENIDO EN LA EVALUACIÓN DE LOS NIVELES DE CLORO RESIDUAL LIBRE EN LA MUESTRA DE AGUA DEL HOGAR_Enteros',
 'P129D_DEC': 'RESULTADO OBTENIDO EN LA EVALUACIÓN DE LOS NIVELES DE CLORO RESIDUAL LIBRE EN LA MUESTRA DE AGUA DEL HOGAR_Decimales',
 'P129D_1': 'RESULTADO OBTENIDO EN LA EVALUACIÓN DE LOS NIVELES DE CLORO RESIDUAL LIBRE EN LA MUESTRA DE AGUA DEL HOGAR_No se realizo la prueba',
 'P129E': 'LA MUESTRA DE AGUA FUE EXTRAÍDA POR:',
 'P129F': 'LA MUESTRA DEL AGUA SE EXTRAJO DEL:',
 'P129F_O': 'LA MUESTRA DEL AGUA SE EXTRAJO DEL:Otros',
 'P129_DIA': 'RESULTADO OBTENIDO EN LA EVALUACIÓN DE LOS NIVELES DE CLORO RESIDUAL LIBRE EN LA MUESTRA DE AGUA DEL HOGAR_Dia',
 'P129_MES': 'RESULTADO OBTENIDO EN LA EVALUACIÓN DE LOS NIVELES DE CLORO RESIDUAL LIBRE EN LA MUESTRA DE AGUA DEL HOGAR_Mes',
 'P129_ANIO': 'RESULTADO OBTENIDO EN LA EVALUACIÓN DE LOS NIVELES DE CLORO RESIDUAL LIBRE EN LA MUESTRA DE AGUA DEL HOGAR_Anio',
 'P129_HORA_INI': 'RESULTADO OBTENIDO EN LA EVALUACIÓN DE LOS NIVELES DE CLORO RESIDUAL LIBRE EN LA MUESTRA DE AGUA DEL HOGAR_Hora_Inicio',
 'P129_MIN_INI': 'RESULTADO OBTENIDO EN LA EVALUACIÓN DE LOS NIVELES DE CLORO RESIDUAL LIBRE EN LA MUESTRA DE AGUA DEL HOGAR_Minuto_Inicio',
 'P130': '¿EL HOGAR TIENE EL SERVICIO DE AGUA TODOS LOS DÍAS DE LA SEMANA?',
 'P130A': '¿CUÁNTAS HORAS AL DÍA?',
 'P130B': '¿CUÁNTOS DÍAS A LA SEMANA TIENE ESTE SERVICIO?',
 'P130C': '¿CUÁNTAS HORAS AL DÍA?',
 'P131_1': '¿EN SU HOGAR EL AGUA LO UTILIZA PARA: Cocinar?',
 'P131_2': '¿EN SU HOGAR EL AGUA LO UTILIZA PARA: Aseo personal?',
 'P131_3': '¿EN SU HOGAR EL AGUA LO UTILIZA PARA: Lavar la ropa?',
 'P131_4': '¿EN SU HOGAR EL AGUA LO UTILIZA PARA: Regar el huerto o chacra?',
 'P131_5': '¿EN SU HOGAR EL AGUA LO UTILIZA PARA: Dar de beber a los animales domésticos?',
 'P131_6': '¿EN SU HOGAR EL AGUA LO UTILIZA PARA: Dar de beber a los animales de crianza?',
 'P131_7': '¿EN SU HOGAR EL AGUA LO UTILIZA PARA: Otro?',
 'P131_7_O': '¿EN SU HOGAR EL AGUA LO UTILIZA PARA: Otro_Especifique?',
 'P131A': 'EN LOS ÚLTIMOS 12 MESES DE………A ………. , ¿SU HOGAR REALIZÓ ALGÚN PAGO POR LA OPERACIÓN Y MANTENIMIENTO DEL SERVICIO DE AGUA?',
 'P131B': 'LA FRECUENCIA DE PAGO POR LA OPERACIÓN Y MANTENIMIENTO DEL SERVICIO DE AGUA ES:',
 'P131B_O': 'LA FRECUENCIA DE PAGO POR LA OPERACIÓN Y MANTENIMIENTO DEL SERVICIO DE AGUA ES:Especifique?',
 'P131C_A': '¿CUÁNTO PAGA EL HOGAR………………..POR LA OPERACIÓN Y MANTENIMIENTO DEL SERVICIO DE AGUA?_SOLES',

In [87]:
df_urban

,PER,ANIO,MES,CONGLOMERADO,NSELV,TSELV,VIVREM,AREA,CCDD,NOMBREDD,...,P184A_15,P184A_16,P184A_17,P184A_18,P187_9_O,P189_8_O,REGIONNATU,ESTRATO,MOD_ENC,FACTOR
1,2.0,2020,09,03981,0120,Urbano,0.0,URBANO,14,LAMBAYEQUE,...,Pase,Pase,Pase,Pase,,,COSTA,Estrato D,Presencial,245.108050
2,2.0,2020,09,03981,0189,Urbano,0.0,URBANO,14,LAMBAYEQUE,...,Pase,Pase,Pase,Pase,,,COSTA,Estrato D,Presencial,245.108050
3,2.0,2020,09,03981,0189,Urbano,0.0,URBANO,14,LAMBAYEQUE,...,Pase,Pase,Pase,Pase,,,COSTA,Estrato D,Presencial,245.108050
6,2.0,2020,09,06703,0037,Urbano,0.0,URBANO,01,AMAZONAS,...,Pase,¿Motocicleta?,Pase,Pase,,,SELVA,Estrato E más bajo,No Presencial,79.149970
7,2.0,2020,09,03981,0057,Urbano,0.0,URBANO,14,LAMBAYEQUE,...,Pase,Pase,Pase,Pase,,,COSTA,Estrato D,Presencial,245.108050
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42148,2.0,2020,05,51489,0073,Urbano,0.0,URBANO,18,MOQUEGUA,...,Pase,Pase,Pase,Pase,,,COSTA,Estrato D,No Presencial,8.948965
42149,2.0,2020,05,51489,0079,Urbano,0.0,URBANO,18,MOQUEGUA,...,Pase,Pase,Pase,Pase,,,COSTA,Estrato D,No Presencial,8.948965
42150,3.0,2020,08,51548,0026,Urbano,0.0,URBANO,23,TACNA,...,Pase,Pase,Pase,Pase,,,COSTA,Estrato E más bajo,No Presencial,102.009870
42151,3.0,2020,08,51548,0046,Urbano,0.0,URBANO,23,TACNA,...,Pase,Pase,Pase,Pase,,,COSTA,Estrato E más bajo,No Presencial,102.009870
42152,3.0,2020,08,51548,0066,Urbano,0.0,URBANO,23,TACNA,...,Pase,Pase,Pase,Pase,,,COSTA,Estrato E más bajo,No Presencial,102.009870

In [88]:
# cheack ID in pandas
( df_urban['PER'].astype(str)+ "_" + 
 df_urban['MES'].astype(str)+ "_" + 
 df_urban['CCDD'].astype(str) + "_" + 
 df_urban['CCPP'].astype(str) + "_" + 
 df_urban['CCDI'].astype(str) + "_" + 
 df_urban['CONGLOMERADO'].astype(str) + "_" + 
 df_urban['NSELV'].astype(str) + "_" +
 df_urban['VIVIENDA'].astype(str) + "_" + 
 df_urban['HOGAR'].astype(int).astype(str) 
).is_unique

True

### 3.3.7. <a id='3.3.7'>[Duplicates](https://thispointer.com/pandas-find-duplicate-rows-in-a-dataframe-based-on-all-or-selected-columns-using-dataframe-duplicated-in-python/)</a>  

See duplicatedes in rows.

In [43]:
df_urban[ df_urban.loc[ : , ['CCDD' ,'CCPP' , 'CCDI' ,'CONGLOMERADO' , 
                             'NSELV', 'VIVIENDA', 'HOGAR'] ].duplicated( keep=False) ]

,PER,ANIO,MES,CONGLOMERADO,NSELV,TSELV,VIVREM,AREA,CCDD,NOMBREDD,...,P184A_15,P184A_16,P184A_17,P184A_18,P187_9_O,P189_8_O,REGIONNATU,ESTRATO,MOD_ENC,FACTOR
4848,1.0,2020,07,39066,0140,Urbano,0.0,URBANO,17,MADRE DE DIOS,...,Pase,¿Motocicleta?,Pase,Pase,,,SELVA,Estrato D,No Presencial,17.688435
5693,3.0,2020,12,36856,0003,Urbano,0.0,URBANO,03,APURIMAC,...,Pase,¿Motocicleta?,Pase,Pase,,,SIERRA,Estrato D,Presencial,68.095590
26150,2.0,2020,05,15120,0110,Urbano,0.0,URBANO,25,UCAYALI,...,Pase,¿Motocicleta?,Pase,Pase,,,SELVA,Estrato D,No Presencial,15.969518
26157,2.0,2020,06,15120,0110,Urbano,0.0,URBANO,25,UCAYALI,...,Pase,¿Motocicleta?,Pase,Pase,,,SELVA,Estrato C,No Presencial,81.580700
36993,1.0,2020,06,36856,0003,Urbano,0.0,URBANO,03,APURIMAC,...,Pase,Pase,Pase,Pase,,,SIERRA,Estrato C,No Presencial,129.106380
37886,1.0,2020,06,38913,0008,Urbano,0.0,URBANO,17,MADRE DE DIOS,...,Pase,¿Motocicleta?,Pase,Pase,,,SELVA,Estrato C,No Presencial,67.858284
37889,1.0,2020,08,38913,0008,Urbano,0.0,URBANO,17,MADRE DE DIOS,...,Pase,¿Motocicleta?,Pase,Pase,,,SELVA,Estrato D,No Presencial,43.645770
38215,2.0,2020,06,39066,0140,Urbano,0.0,URBANO,17,MADRE DE DIOS,...,Pase,¿Motocicleta?,Pase,Pase,,,SELVA,Estrato D,No Presencial,42.489746
39625,3.0,2020,07,43264,0008,Urbano,0.0,URBANO,04,AREQUIPA,...,Pase,Pase,Pase,Pase,,,SIERRA,Estrato D,No Presencial,526.626160
39631,1.0,2020,10,43264,0008,Urbano,0.0,URBANO,04,AREQUIPA,...,"¿Automóvil, camioneta?",Pase,Pase,Pase,,,SIERRA,Estrato E más bajo,Presencial,241.596770

We will drop the last duplication.

In [45]:
df_urban.shape

(24347, 120)

In [44]:
df_urban_no_dpl = df_urban[ ~ df_urban.loc[:, ['CCDD' ,'CCPP' , 'CCDI' ,'CONGLOMERADO' , 'NSELV', 
                                               'VIVIENDA', 'HOGAR'] ].duplicated() ].copy()
df_urban_no_dpl

,PER,ANIO,MES,CONGLOMERADO,NSELV,TSELV,VIVREM,AREA,CCDD,NOMBREDD,...,P184A_15,P184A_16,P184A_17,P184A_18,P187_9_O,P189_8_O,REGIONNATU,ESTRATO,MOD_ENC,FACTOR
1,2.0,2020,09,03981,0120,Urbano,0.0,URBANO,14,LAMBAYEQUE,...,Pase,Pase,Pase,Pase,,,COSTA,Estrato D,Presencial,245.108050
2,2.0,2020,09,03981,0189,Urbano,0.0,URBANO,14,LAMBAYEQUE,...,Pase,Pase,Pase,Pase,,,COSTA,Estrato D,Presencial,245.108050
3,2.0,2020,09,03981,0189,Urbano,0.0,URBANO,14,LAMBAYEQUE,...,Pase,Pase,Pase,Pase,,,COSTA,Estrato D,Presencial,245.108050
6,2.0,2020,09,06703,0037,Urbano,0.0,URBANO,01,AMAZONAS,...,Pase,¿Motocicleta?,Pase,Pase,,,SELVA,Estrato E más bajo,No Presencial,79.149970
7,2.0,2020,09,03981,0057,Urbano,0.0,URBANO,14,LAMBAYEQUE,...,Pase,Pase,Pase,Pase,,,COSTA,Estrato D,Presencial,245.108050
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42148,2.0,2020,05,51489,0073,Urbano,0.0,URBANO,18,MOQUEGUA,...,Pase,Pase,Pase,Pase,,,COSTA,Estrato D,No Presencial,8.948965
42149,2.0,2020,05,51489,0079,Urbano,0.0,URBANO,18,MOQUEGUA,...,Pase,Pase,Pase,Pase,,,COSTA,Estrato D,No Presencial,8.948965
42150,3.0,2020,08,51548,0026,Urbano,0.0,URBANO,23,TACNA,...,Pase,Pase,Pase,Pase,,,COSTA,Estrato E más bajo,No Presencial,102.009870
42151,3.0,2020,08,51548,0046,Urbano,0.0,URBANO,23,TACNA,...,Pase,Pase,Pase,Pase,,,COSTA,Estrato E más bajo,No Presencial,102.009870
42152,3.0,2020,08,51548,0066,Urbano,0.0,URBANO,23,TACNA,...,Pase,Pase,Pase,Pase,,,COSTA,Estrato E más bajo,No Presencial,102.009870

In [91]:
df_urban_no_dpl.value_counts()

PER  ANIO  MES  CONGLOMERADO  NSELV  TSELV   VIVREM  AREA    CCDD  NOMBREDD   CCPP  NOMBREPP               CCDI  NOMBREDI   VIVIENDA  TOT_HOGAR  HOGAR  RESFIN    P100_C  P101_O  P102A_O  P103_O  P104B_O  P106_O  P107A_O                    P107B_O                         P108_1_O  P108B_O  P109  P110A  P110AA  P111A  P112_1  P113B_1_3_O  P118_1_O  P119_1_O  P121_1_O  P116_1_5_O  P121D_1_5_O  P112_2  P113B_2_3_O  P118_2_O  P119_2_O  P121_2_O  P116_2_5_O  P121D_2_5_O  P122A_6_O       P122D_O  P127_1        P127_2  P127_3  P127_4  P127_5  P127_6  P127_6_O  P128A_1        P128A_2           P128A_3                             P128A_4  P128A_5  P128A_6  P128A_7  P128A_8     P128A_O  P129G                                P129G_O  P129B  P100_C_2  P129F_O  P130  P130A  P131_7_O  P131B_O  P131C_B  P131D_O  P137_O  P139_O  P141_7_O  P142A                                           P142A_O                     P159_O  P172B_1  P172B_2  P172C_2               P172D  P172F_1_6_O  P172F_2_6_O  P172F_3_6_O  P172F_4_6_O  P172F_5_6_O  P172F_6_6_O                                   P172E_7_O  P172F_7_6_O  P172G  P172H_8_O  P180_O  P184A_1             P184A_2              P184A_3         P184A_4                        P184A_5             P184A_6             P184A_7      P184A_8              P184A_9                          P184A_10                                     P184A_11                                    P184A_12         P184A_13                               P184A_14               P184A_15                P184A_16       P184A_17  P184A_18  P187_9_O  P189_8_O  REGIONNATU  ESTRATO             MOD_ENC        FACTOR
1.0  2020  01   00123         0127   Urbano  0.0     URBANO  24    TUMBES     01    TUMBES                 01    TUMBES     006       1.0        1.0    Completa  1.0                                               DOCUMENTO DE ADJUDICACION  PRESIDENTE DE LA JUNTA VECINAL                     Si    Si     24.0    No     No                                                                          No                                                                                                   Electricidad  Pase    Pase    Pase    Pase    Pase              Pase           Gas (balón GLP)?  Pase                                Pase     Pase     Pase     Pase     Pase                 ¿Red pública dentro de la vivienda?           Si     1.0                Si    3.0                       0.0                                         ¿Red pública de desagüe dentro de la vivienda?                                      No       1.0       Muy insatisfecho/a?  No                                                                                                                                            No                        Pase                ¿Televisor a color?  ¿Cocina a gas?  ¿Refrigeradora o congeladora?  Pase                Pase                ¿Licuadora?  ¿Plancha electrica?  Pase                             ¿Teléfono celular sin servicio de internet?  Pase                                        Pase             Pase                                   Pase                   Pase                    Pase           Pase      Pase                          COSTA       Estrato D           Presencial     71.14809     1
3.0  2020  01   00164         0139   Urbano  0.0     URBANO  24    TUMBES     01    TUMBES                 01    TUMBES     007       1.0        1.0    Completa  2.0                                                                                                                             Si    Si     24.0    Si     No                                                                          No                                                                                                   Electricidad  Pase    Pase    Pase    Pase    Pase              Pase           Gas (balón GLP)?  Pase                                Pase     Pase     Pase     Pase     Pase                 ¿Red pública dentro de la vivienda?           Si     2.0                Si    4.0                       0.0                                         ¿Red pública de desagüe dentro de la vivienda?                                      No       1.0       Muy insatisfecho/a?  Si                                                                      USO/MANEJO DIRECTO POR PARTE DEL GENERADOR/A                          No                        ¿Equipo de sonido?  ¿Televisor a color?  ¿Cocina a gas?  ¿Refrigeradora o congeladora?  ¿Lavadora de ropa?  Pase                ¿Licuadora?  ¿Plancha electrica?  ¿Computadora / Laptop / Tablet?  ¿Teléfono celular sin servicio de internet?  ¿Teléfono celular con servicio de internet  ¿Teléfono fijo?  ¿Conexión a TV por cable o satelital?  ¿Conexión a Internet?  Pase                    Pase           Pase      Pase                          COSTA       Estrato E más bajo  Presencial     49.38406     1
                00417         0101   Urbano  0.0     URBANO  20    PIURA      07    TALARA                 01    PARIÑAS    008       1.0        1.0    Completa  3.0                                                                          FONDO NACIONAL DE VIVIENDA                         Si    Si     24.0    No     No                                                                          No                                                                                                   Electricidad  Pase    Pase    Pase    Pase    Pase              Pase           Gas (balón GLP)?  Pase                                Pase     Pase     Pase     Pase     Pase                 ¿Red pública dentro de la vivienda?           Si     3.0                Si    8.0                       0.0                                         ¿Red pública de desagüe dentro de la vivienda?                                      Si       1.0      Satisfecho/a?         Si                                                                                                                                            No                        ¿Equipo de sonido?  ¿Televisor a color?  ¿Cocina a gas?  ¿Refrigeradora o congeladora?  Pase                Pase                ¿Licuadora?  ¿Plancha electrica?  Pase                             Pase                                         ¿Teléfono celular con servicio de internet  Pase             ¿Conexión a TV por cable o satelital?  Pase                   Pase                    Pase           Pase      Pase                          COSTA       Estrato B           Presencial     478.19340    1
                              0074   Urbano  0.0     URBANO  20    PIURA      07    TALARA                 01    PARIÑAS    006       1.0        1.0    Completa  1.0                                                                                                                             Si    Si     24.0    No     No                                                                          No                                                                                                   Electricidad  Pase    Pase    Pase    Pase    Pase              Pase           Pase              Pase                                Pase     Pase     Pase     Pase     NO COCINAN           ¿Red pública dentro de la vivienda?           Si     1.0                Si    7.0                       0.0                                         ¿Red pública de desagüe dentro de la vivienda?                                      No       1.0      Satisfecho/a?         No                                                                                                                                            No                        Pase                Pase                 Pase            Pase                           ¿Lavadora de ropa?  Pase                Pase         Pase                 Pase                             Pase                                         ¿Teléfono celular con servicio de internet  Pase             Pase                                   Pase                   Pase                    Pase           Pase      Pase                          COSTA       Estrato B           Presencial     478.19340    1
                              0057   Urbano  0.0     URBANO  20    PIURA      07    TALARA                 01    PARIÑAS    005       1.0        1.0    Completa  2.0                                                                          FONDO NACIONAL DE VIVIENDA                         Si    Si     24.0    No     No                                                                          No                                                                                                   Electricidad  Pase    Pase    Pase    Pase    Pase              Electricidad?  Gas (balón GLP)?  Pase                                Pase     Pase     Pase     Pase     Pase                 ¿Red pública dentro de la vivienda?           Si     2.0                Si    8.0                       0.0                                         ¿Red pública de desagüe dentro de la vivienda?                                      No       1.0      Insatisfecho/a?       Si                                                                                                                                            No                        ¿Equipo de sonido?  ¿Televisor a color?  ¿Cocina a gas?  ¿Refrigeradora o congeladora?  ¿Lavadora de ropa?  Pase                Pase         Pase                 Pase                             Pase                                         ¿Teléfono celular con servicio de internet  Pase             Pase                                   Pase                   Pase                    Pase           Pase      Pase                          COSTA       Estrato B           Presencial     478.19340    1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ..
1.0  2020  11   06067         0136   Urbano  0.0     URBANO  06    CAJAMARCA  01    CAJAMARCA              01    CAJAMARCA  006       1.0        1.0    Completa  1.0                                                                                                                             Si    Si     24.0    No     No                                                                          Si                                                                                                   Electricidad  Pase    Pase    Pase    Pase    Pase              Pase           Gas (balón GLP)?  Pase                                Pase     Pase     Pase     Pase     Pase                 ¿Red pública dentro de la vivienda?           Si     1.0                Si    12.0                      0.0                                         ¿Red pública de desagüe dentro de la vivienda?                                      Si       1.0      Insatisfecho/a?       Si                                                                                                                                            No                        Pase                Pase                 ¿Cocina a gas?  Pase                           Pase                Pase                Pase         ¿Plancha electrica?  Pase                             Pase                                         ¿Teléfono celular con servicio de internet  Pase             Pase                                   Pase                   Pase                    Pase           Pase      Pase                          SIERRA      Estrato D           Presencial     177.68617    1
                              0112   Urbano  0.0     URBANO  06    CAJAMARCA  01    CAJAMARCA              01    CAJAMARCA  005       1.0        1.0    Completa  4.0                                                                                                                             Si    Si     24.0    Si     No                                                                          No                                                                                                   Electricidad  Pase    Pase    Pase    Pase    Pase              Electricidad?  Pase              Gas natural (sistema de tuberías)?  Pase     Pase     Pase     Pase     Pase                 ¿Red pública dentro de la vivienda?           Si     4.0                Si    24.0                      0.0                                         ¿Red pública de desagüe dentro de la vivienda?                                      Si       1.0      Satisfecho/a?         Si                                                                                                                                            No                        ¿Equipo de sonido?  ¿Televisor a color?  ¿Cocina a gas?  ¿Refrigeradora o congeladora?  ¿Lavadora de ropa?  ¿Horno microondas?  ¿Licuadora?  ¿Plancha electrica?  ¿Computadora / Laptop / Tablet?  Pase                                         ¿Teléfono celular con servicio de internet  ¿Teléfono fijo?  ¿Conexión a TV por cable o satelital?  ¿Conexión a Internet?  ¿Automóvil, camioneta?  Pase           Pase      Pase                          SIERRA      Estrato D           Presencial     177.68617    1
                              0087   Urbano  0.0     URBANO  06    CAJAMARCA  01    CAJAMARCA              01    CAJAMARCA  004       1.0        1.0    Completa  1.0                                                                                                                             Si    Si     24.0    No     No                                                                          No                                                                                                   Electricidad  Pase    Pase    Pase    Pase    Pase              Pase           Gas (balón GLP)?  Pase                                Pase     Pase     Pase     Pase     Pase                 ¿Red pública dentro de la vivienda?           Si     1.0                Si    11.0                      0.0                                         ¿Red pública de desagüe dentro de la vivienda?                                      Si       1.0      Insatisfecho/a?       Si                                                                                                                                            No                        Pase                ¿Televisor a color?  ¿Cocina a gas?  ¿Refrigeradora o congeladora?  Pase                Pase                Pase         Pase                 Pase                             Pase                                         ¿Teléfono celular con servicio de internet  Pase             Pase                                   Pase                   Pase                    Pase           Pase      Pase                          SIERRA      Estrato D           Presencial     177.68617    1
                              0061   Urbano  0.0     URBANO  06    CAJAMARCA  01    CAJAMARCA              01    CAJAMARCA  003       1.0        1.0    Completa  2.0                                                                                                                             Si    Si     24.0    No     Si                                                                          No                                                                          RONDAS URBANAS           Electricidad  Pase    Pase    Pase    Pase    Pase              Pase           Gas (balón GLP)?  Pase                                Pase     Leña?    Pase     Pase     Pase                 ¿Red pública dentro de la vivienda?           Si     2.0                Si    24.0                      0.0                                         ¿Red pública de desagüe dentro de la vivienda?                                      Si       1.0      Satisfecho/a?         Si                                                                                                                                            No                        Pase                Pase                 ¿Cocina a gas?  Pase                           Pase                Pase                Pase         Pase                 Pase                             Pase                                         ¿Teléfono celular con servicio de internet  Pase             Pase                                   Pase                   Pase                    Pase           Pase      Pase                          SIERRA      Estrato D           Presencial     177.68617    1
5.0  2020  09   39372         0144   Urbano  0.0     URBANO  21    PUNO       10    SAN ANTONIO DE PUTINA  02    ANANEA     008       1.0        1.0    Completa  1.0                                                                                                                             Si    Si     24.0    No     No                                                                          No                                                                                                   Electricidad  Pase    Pase    Pase    Pase    Pase              Pase           Gas (balón GLP)?  Pase                                Pase     Pase     Pase     Pase     Pase                 ¿Red pública dentro de la vivienda?           No     1.0                Si    24.0                      0.0                                         Otro?                                           SERVICIO HIGIENICO PÚBLICO          No       1.0      Insatisfecho/a?       Si                                                                                                                                            No                        Pase                ¿Televisor a color?  ¿Cocina a gas?  Pase                           Pase                Pase                Pase         ¿Plancha electrica?  ¿Computadora / Laptop / Tablet?  ¿Teléfono celular sin servicio de internet?  ¿Teléfono celular con servicio de internet  Pase             Pase                                   Pase                   Pase                    ¿Motocicleta?  Pase      Pase                          SIERRA      Estrato E más bajo  No Presencial  234.55807    1
Length: 20346, dtype: int64

In [92]:
df_urban_no_dpl.ESTRATO

1                 Estrato D
2                 Estrato D
3                 Estrato D
6        Estrato E más bajo
7                 Estrato D
                ...
42148             Estrato D
42149             Estrato D
42150    Estrato E más bajo
42151    Estrato E más bajo
42152    Estrato E más bajo
Name: ESTRATO, Length: 24342, dtype: category
Categories (5, object): ['Estrato A más alto', 'Estrato B', 'Estrato C', 'Estrato D', 'Estrato E más bajo']

### 3.3.8. <a id='3.3.8'>Groupby</a>

In [93]:
df_urban_no_dpl.attrs['var_labels']

{'PER': 'PERIODO',
 'ANIO': 'AÑO',
 'MES': 'MES DE LA ENCUESTA',
 'CONGLOMERADO': 'N° de conglomerado',
 'NSELV': 'Nº de selección de la vivienda',
 'TSELV': 'Tipo de selección de la vivienda',
 'VIVREM': '¿Es una vivienda de reemplazo?',
 'NUMVIVREM': 'Anote el número de selección de la vivienda reemplazada',
 'AREA': 'AREA',
 'CCDD': 'Código de Departamento',
 'NOMBREDD': 'Nombre de Departamento',
 'CCPP': 'Código de Provincia',
 'NOMBREPP': 'Nombre de la Provincia',
 'CCDI': 'Código del Distrito',
 'NOMBREDI': 'Nombre del Distrito',
 'VIVIENDA': 'N° de Vivienda',
 'TOT_HOGAR': '¿Cuántos hogares ocupa esta vivienda?',
 'HOGAR': 'Hogar N°',
 'RESFIN': 'Resultado final del hogar',
 'P100_C': 'INFORMANTE N°',
 'P101': 'TIPO DE VIVIENDA',
 'P101_O': 'TIPO DE VIVIENDA: ESPECIFIQUE',
 'P102A': 'EN LA VIVIENDA, ¿EL MATERIAL DE CONSTRUCCIÓN PREDOMINANTE EN LAS PAREDES EXTERIORES ES DE:',
 'P102A_O': 'EN LA VIVIENDA, ¿EL MATERIAL DE CONSTRUCCIÓN PREDOMINANTE EN LAS PAREDES EXTERIORES ES DE: Otros materiales Especifique',
 'P103': 'EL MATERIAL PREDOMINANTE EN LOS PISOS DE LA VIVIENDA ES',
 'P103_O': 'EL MATERIAL PREDOMINANTE EN LOS PISOS DE LA VIVIENDA ES: ESPECIFIQUE',
 'P104B': 'EN LA VIVIENDA,  ¿EL MATERIAL DE CONSTRUCCIÓN PREDOMINANTE EN LOS TECHOS ES DE:',
 'P104B_O': 'EN LA VIVIENDA,  ¿EL MATERIAL DE CONSTRUCCIÓN PREDOMINANTE EN LOS TECHOS ES DE: Otro maaterial Especifique',
 'P105': '¿CUÁNTAS HABITACIONES EN TOTAL TIENE LA VIVIENDA, SIN CONTAR EL BAÑO, LA COCINA, LOS PASADIZOS, NI EL GARAJE?',
 'P106': 'LA VIVIENDA QUE OCUPA ES:',
 'P106_O': 'LA VIVIENDA QUE OCUPA ES: ESPECIFIQUE',
 'P106A': '¿DESDE QUE AÑO VIVEN EN ESTA VIVIENDA?',
 'P107': '¿LA VIVIENDA CUENTA CON ALGÙN DOCUMENTO QUE ACREDITE LA PROPIEDAD?',
 'P107A': '¿QUÉ TIPO DE DOCUMENTO ACREDITA EL DERECHO DE PROPIEDAD DE LA VIVIENDA?',
 'P107A_O': '¿QUÉ TIPO DE DOCUMENTO ACREDITA EL DERECHO DE PROPIEDAD DE LA VIVIENDA?_ESPECIFIQUE',
 'P107B': '¿QUÉ ENTIDAD O AUTORIDAD LE EMITIÓ EL/LA …...?',
 'P107B_O': '¿QUÉ ENTIDAD O AUTORIDAD LE EMITIÓ EL/LA …...?_ESPECIFIQUE',
 'P107C': '¿EL/LA ……ESTÁ A NOMBRE DE ALGÚN MIEMBRO DEL HOGAR DE ESTA VIVIENDA?',
 'P108': '¿EL/LA …… DE ESTA VIVIENDA ESTÀ REGISTRADO EN LOS REGISTROS PÚBLICOS?',
 'P108_1': '¿CUÁL ES EL PRINCIPAL MOTIVO POR EL CUAL NO REGISTRO EL/LA…?',
 'P108_1_O': '¿CUÁL ES EL PRINCIPAL MOTIVO POR EL CUAL NO REGISTRO EL/LA…?_ESPECIFIQUE',
 'P108A': 'LA CONSTRUCCIÓN DE ESTA VIVIENDA, ¿ESTÁ REGISTRADA EN LOS REGISTROS PÚBLICOS?',
 'P108B': '¿CUÁL ES EL PRINCIPAL MOTIVO POR EL CUAL NO REGISTRO LA CONSTRUCCIÓN?',
 'P108B_O': '¿CUÁL ES EL PRINCIPAL MOTIVO POR EL CUAL NO REGISTRO LA CONSTRUCCIÓN?_ESPECIFIQUE',
 'P109': '¿LA VIVIENDA TIENE ALUMBRADO ELÉCTRICO POR RED PÚBLICA?',
 'P110A': '¿LA VIVIENDA TIENE ACCESO AL SERVICIO DE LA ENERGÍA ELÉCTRICA POR RED PÚBLICA TODOS LOS DÍAS DE LA SEMANA?',
 'P110AA': '¿CUÁNTAS HORAS AL DÍA?',
 'P110AB': '¿CUÁNTOS DÍAS A LA SEMANA TIENE ESTE SERVICIO?',
 'P110AC': '¿CUÁNTAS HORAS AL DÍA?',
 'P111A': 'EL MES ANTERIOR……., LA VIVIENDA ¿HA TENIDO INTERRUPCIONES O CORTES EN LA ENERGÍA ELÉCTRICA?',
 'P111AA': '¿Cuántas interrupciones o cortes tuvo en el mes anterior…..?',
 'P111AB_HORAS': '¿Cuánto tiempo duró la última interrupción o corte?.....HORAS',
 'P111AB_MINUTOS': '¿Cuánto tiempo duró la última interrupción o corte?.....MINUTOS',
 'P112_1': 'EN LOS ÚLTIMOS 12 MESES ¿HAN SIDO VÍCTIMAS DE:..ROBO EN LA VIVIENDA',
 'P113_1': 'EN LOS ÚLTIMOS 12 MESES ¿CUÁNTAS VECES FUERON VÍCTIMAS DE…ROBO EN LA VIVIENDA:',
 'P113A_1': 'DE ESTAS ……… VECES ¿CUÁNTAS FUERON DENUNCIADAS?....ROBO EN LA VIVIENDA',
 'P113B_1_1': 'DE ESTAS ……¿CUÁNTAS FUERON DENUNCIADAS EN: La Comisaria (Policia Nacional del Peru)....ROBO EN LA VIVIENDA',
 'P113B_1_1_ENT': 'DE ESTAS ……¿CUÁNTAS FUERON DENUNCIADAS EN: La Comisaria (Policia Nacional del Peru)_Nro DE VECES....ROBO EN LA VIVIENDA',
 'P113B_1_2': 'DE ESTAS ……¿CUÁNTAS FUERON DENUNCIADAS EN:  El Ministerio Publico o Fiscalia?....ROBO EN LA VIVIENDA',
 'P113B_1_2_ENT': 'DE ESTAS ……¿CUÁNTAS FUERON DENUNCIADAS EN:  El Ministerio Publico o Fiscalia?_Nro DE VECES....ROBO EN LA VIVIENDA',
 'P113B_1_3': 'DE ESTAS ……¿CUÁNTAS FUERON DENUNCIADAS EN: Otro?....ROBO EN LA VIVIENDA',
 'P113B_1_3_ENT': 'DE ESTAS ……¿CUÁNTAS FUERON DENUNCIADAS EN: Otro?_Nro DE VECES....ROBO EN LA VIVIENDA',
 'P113B_1_3_O': 'DE ESTAS ……¿CUÁNTAS FUERON DENUNCIADAS EN: Otro?.....ROBO EN LA VIVIENDA_OTRO/ESPECIFIQUE',
 'P117_1': '¿DENUNCIÓ EL: ROBO EN LA VIVIENDA?',
 'P118_1': '¿DÓNDE REALIZÓ LA DENUNCIA DEL? ROBO EN LA VIVIENDA',
 'P118_1_O': '¿DONDE REALIZÓ LA DENUNCIA DEL? ROBO EN LA VIVIENDA_OTRO/ESPECIFIQUE',
 'P119_1': '¿QUÉ SUCEDIÓ CON SU DENUNCIA ? ROBO EN LA VIVIENDA',
 'P119_1_O': '¿QUÉ SUCEDIÓ CON SU DENUNCIA ?…ROBO EN LA VIVIENDA_OTRO/ESPECIFIQUE',
 'P121_1': '¿CUÁL FUE EL MOTIVO PRINCIPAL POR EL CUAL NO REALIZÓ LA DENUNCIA?…ROBO EN LA VIVIENDA',
 'P121_1_O': '¿CUÁL FUE EL MOTIVO PRINCIPAL POR EL CUAL NO REALIZÓ LA DENUNCIA?…ROBO EN LA VIVIENDA_OTRO/ESPECIFIQUE',
 'P115_1': 'EL DELINCUENTE / AGRESOR PORTABA ALGÚN ARMA (REVÓLVER, PISTOLA, PIEDRAS, PALOS, ETC.)…ROBO EN LA VIVIENDA',
 'P116_1_1': '¿QUÉ TIPO DE ARMA PORTABA? ROBO EN LA VIVIENDA Armas de fuego de mano (revólver, pistola u otro)',
 'P116_1_2': '¿QUÉ TIPO DE ARMA PORTABA? ROBO EN LA VIVIENDA Armas de fuego largo (escopeta, rifle, ametralladora)',
 'P116_1_3': '¿QUÉ TIPO DE ARMA PORTABA? ROBO EN LA VIVIENDA Arma blanca (cuchillo, objeto punzo cortante)',
 'P116_1_4': '¿QUÉ TIPO DE ARMA PORTABA? ROBO EN LA VIVIENDA Objetos contundentes (palos, piedras, etc.)',
 'P116_1_5': '¿QUÉ TIPO DE ARMA PORTABA? ROBO EN LA VIVIENDA Otro',
 'P116_1_5_O': '¿QUÉ TIPO DE ARMA PORTABA? ROBO EN LA VIVIENDA Otro _ESPECIFIQUE',
 'P121A_1': '¿EN QUÉ MES SUCEDIÓ EL ROBO EN LA VIVIENDA?',
 'P121B_1': '¿EL/LA  ROBO EN LA VIVIENDA OCURRIÓ UN:...',
 'P121C_1': '¿EL/LOS DELINCUENTE/S UTILIZARON ALGÚN MEDIO DE TRANSPORTE PARA MOVILIZARSE?',
 'P121D_1_1': '¿Qué MEDIO DE TRANSPORTE UTILIZÓ O UTILIZARÓN? Auto/camioneta',
 'P121D_1_2': '¿Qué MEDIO DE TRANSPORTE UTILIZÓ O UTILIZARÓN? Motocicleta',
 'P121D_1_3': '¿Qué MEDIO DE TRANSPORTE UTILIZÓ O UTILIZARÓN? Mototaxi/Mototriciclo',
 'P121D_1_4': '¿Qué MEDIO DE TRANSPORTE UTILIZÓ O UTILIZARÓN? Bicicleta',
 'P121D_1_5': '¿Qué MEDIO DE TRANSPORTE UTILIZÓ O UTILIZARÓN? Otro ',
 'P121D_1_5_O': '¿Qué MEDIO DE TRANSPORTE UTILIZÓ O UTILIZARÓN? Otro_Especifique',
 'P112_2': 'EN LOS ÚLTIMOS 12 MESES DE……A……., ¿HAN SIDO VÍCTIMAS DE: INTENTO DE ROBO EN LA VIVIENDA?',
 'P113_2': 'EN LOS ÚLTIMOS 12 MESES DE…….A………., ¿CUANTAS VECES FUERON VÍCTIMAS DE: INTENTO DE ROBO EN LA VIVIENDA?',
 'P113A_2': 'DE ESTAS ……… VECES ¿CUÁNTAS FUERON DENUNCIADAS? ...... INTENTO DE ROBO EN LA VIVIENDA',
 'P113B_2_1': 'DE ESTAS ……¿CUÁNTAS FUERON DENUNCIADAS EN: La Comisaria (Policia Nacional del Peru) ...... INTENTO DE ROBO EN LA VIVIENDA',
 'P113B_2_1_ENT': 'DE ESTAS ……¿CUÁNTAS FUERON DENUNCIADAS EN: La Comisaria (Policia Nacional del Peru)_Nro DE VECES ...... INTENTO DE ROBO EN LA VIVIENDA',
 'P113B_2_2': 'DE ESTAS ……¿CUÁNTAS FUERON DENUNCIADAS EN:  El Ministerio Publico o Fiscalia? ...... INTENTO DE ROBO EN LA VIVIENDA',
 'P113B_2_2_ENT': 'DE ESTAS ……¿CUÁNTAS FUERON DENUNCIADAS EN:  El Ministerio Publico o Fiscalia?_Nro DE VECES ...... INTENTO DE ROBO EN LA VIVIENDA',
 'P113B_2_3': 'DE ESTAS ……¿CUÁNTAS FUERON DENUNCIADAS EN: Otro? ...... INTENTO DE ROBO EN LA VIVIENDA',
 'P113B_2_3_ENT': 'DE ESTAS ……¿CUÁNTAS FUERON DENUNCIADAS EN: Otro?_Nro DE VECES ...... INTENTO DE ROBO EN LA VIVIENDA',
 'P113B_2_3_O': 'DE ESTAS ……¿CUÁNTAS FUERON DENUNCIADAS EN: Otro? ...... INTENTO DE ROBO EN LA VIVIENDA',
 'P117_2': 'DENUNCIÓ EL …INTENTO DE ROBO EN LA VIVIENDA',
 'P118_2': '¿DÓNDE REALIZO LA DENUNCIA ?…INTENTO DE ROBO EN LA VIVIENDA',
 'P118_2_O': '¿DÓNDE REALIZO LA DENUNCIA ?…INTENTO DE ROBO EN LA VIVIENDA_OTRO/ESPECIFIQUE',
 'P119_2': '¿QUÉ SUCEDIÓ CON SU DENUNCIA ?…INTENTO DE ROBO EN LA VIVIENDA',
 'P119_2_O': '¿QUÉ SUCEDIÓ CON SU DENUNCIA ?…INTENTO DE ROBO EN LA VIVIENDA OTRO/ESPECIFIQUE',
 'P121_2': '¿CUÁL FUE EL MOTIVO PRINCIPAL POR EL CUAL NO REALIZÓ LA DENUNCIA?…INTENTO DE ROBO EN LA VIVIENDA',
 'P121_2_O': '¿CUÁL FUE EL MOTIVO PRINCIPAL POR EL CUAL NO REALIZÓ LA DENUNCIA?…INTENTO DE ROBO EN LA VIVIENDA_OTRO/ESPECIFIQUE',
 'P115_2': 'EL DELINCUENTE / AGRESOR PORTABA ALGÚN ARMA (REVÓLVER, PISTOLA, PIEDRAS, PALOS, ETC.)…INTENTO DE ROBO EN LA VIVIENDA',
 'P116_2_1': '¿QUÉ TIPO DE ARMA PORTABA? INTENTO ROBO EN LA VIVIENDA Armas de fuego de mano (revólver, pistola u otro)',
 'P116_2_2': '¿QUÉ TIPO DE ARMA PORTABA? INTENTO ROBO EN LA VIVIENDA Armas de fuego largo (escopeta, rifle, ametralladora)',
 'P116_2_3': '¿QUÉ TIPO DE ARMA PORTABA? INTENTO ROBO EN LA VIVIENDA Arma blanca (cuchillo,objeto punzo cortante)',
 'P116_2_4': '¿QUÉ TIPO DE ARMA PORTABA? INTENTO ROBO EN LA VIVIENDA Objetos contundentes (palos, piedras, etc.) ',
 'P116_2_5': '¿QUÉ TIPO DE ARMA PORTABA? INTENTO ROBO EN LA VIVIENDA Otro',
 'P116_2_5_O': '¿QUÉ TIPO DE ARMA PORTABA? INTENTO ROBO EN LA VIVIENDA Otro _ESPECIFIQUE',
 'P121A_2': '¿EN QUÉ MES SUCEDIÓ EL ….?',
 'P121B_2': '¿EL/LA  INTENTO DE ROBO EN LA VIVIENDA OCURRIÓ UN:...',
 'P121C_2': '¿EL/LOS DELINCUENTE/S UTILIZARON ALGÚN MEDIO DE TRANSPORTE PARA MOVILIZARSE?',
 'P121D_2_1': '¿Qué MEDIO DE TRANSPORTE UTILIZÓ O UTILIZARÓN? Auto/camioneta',
 'P121D_2_2': '¿Qué MEDIO DE TRANSPORTE UTILIZÓ O UTILIZARÓN? Motocicleta',
 'P121D_2_3': '¿Qué MEDIO DE TRANSPORTE UTILIZÓ O UTILIZARÓN? Mototaxi/Mototriciclo',
 'P121D_2_4': '¿Qué MEDIO DE TRANSPORTE UTILIZÓ O UTILIZARÓN? Bicicleta',
 'P121D_2_5': '¿Qué MEDIO DE TRANSPORTE UTILIZÓ O UTILIZARÓN? Otro ',
 'P121D_2_5_O': '¿Qué MEDIO DE TRANSPORTE UTILIZÓ O UTILIZARÓN? Otro_Especifique',
 'P122A_1': 'EN SU ZONA O BARRIO, ¿SE HA ADOPTADO ALGUNA MEDIDA DE SEGURIDAD PARA PREVENIR LA DELINCUENCIA, COMO: Sistema de vigilancia a través de video camaras?',
 'P122A_2': 'EN SU ZONA O BARRIO, ¿SE HA ADOPTADO ALGUNA MEDIDA DE SEGURIDAD PARA PREVENIR LA DELINCUENCIA, COMO: Vigilante particular?',
 'P122A_3': 'EN SU ZONA O BARRIO, ¿SE HA ADOPTADO ALGUNA MEDIDA DE SEGURIDAD PARA PREVENIR LA DELINCUENCIA, COMO: Sistema de alarma comunitaria?',
 'P122A_4': 'EN SU ZONA O BARRIO, ¿SE HA ADOPTADO ALGUNA MEDIDA DE SEGURIDAD PARA PREVENIR LA DELINCUENCIA, COMO: Sistema de control de acceso a personas ajenas al lugar?',
 'P122A_5': 'EN SU ZONA O BARRIO, ¿SE HA ADOPTADO ALGUNA MEDIDA DE SEGURIDAD PARA PREVENIR LA DELINCUENCIA, COMO: Junta vecinal con fines de velar por la seguridad?',
 'P122A_6': 'EN SU ZONA O BARRIO, ¿SE HA ADOPTADO ALGUNA MEDIDA DE SEGURIDAD PARA PREVENIR LA DELINCUENCIA, COMO: Otra?',
 'P122A_6_O': 'EN SU ZONA O BARRIO, ¿SE HA ADOPTADO ALGUNA MEDIDA DE SEGURIDAD PARA PREVENIR LA DELINCUENCIA, COMO: Otra?/Especifique',
 'P122B_1': '¿DESDE QUE AÑO CUENTAN CON EL/LA: Sistema de vigilancia a traves de video camaras?',
 'P122B_2': '¿DESDE QUE AÑO CUENTAN CON EL/LA: Vigilante particular?',
 'P122B_3': '¿DESDE QUE AÑO CUENTAN CON EL/LA: Sistema de alarma comunitaria?',
 'P122B_4': '¿DESDE QUE AÑO CUENTAN CON EL/LA: Sistema de control de acceso a personas ajenas al lugar?',
 'P122B_5': '¿DESDE QUE AÑO CUENTAN CON EL/LA: Junta vecinal con fines de velar por la seguridad?',
 'P122B_6': '¿DESDE QUE AÑO CUENTAN CON EL/LA: Otra?',
 'P122C_1': '¿ESTA MEDIDA LA TOMÓ O SE INSTALÓ DURANTE LOS ÚLTIMOS 12 MESES DE………A ……….? Sistema de vigilancia a traves de video camaras?',
 'P122C_2': '¿ESTA MEDIDA LA TOMÓ O SE INSTALÓ DURANTE LOS ÚLTIMOS 12 MESES DE………A ……….? Vigilante particular?',
 'P122C_3': '¿ESTA MEDIDA LA TOMÓ O SE INSTALÓ DURANTE LOS ÚLTIMOS 12 MESES DE………A ……….? Sistema de alarma comunitaria?',
 'P122C_4': '¿ESTA MEDIDA LA TOMÓ O SE INSTALÓ DURANTE LOS ÚLTIMOS 12 MESES DE………A ……….? Sistema de control de acceso a personas ajenas al lugar?',
 'P122C_5': '¿ESTA MEDIDA LA TOMÓ O SE INSTALÓ DURANTE LOS ÚLTIMOS 12 MESES DE………A ……….? Junta vecinal con fines de velar por la seguridad?',
 'P122C_6': '¿ESTA MEDIDA LA TOMÓ O SE INSTALÓ DURANTE LOS ÚLTIMOS 12 MESES DE………A ……….? Otra?',
 'P122D_1': 'ACTUALMENTE, ¿HAN ADOPTADO ALGUNA MEDIDA DE SEGURIDAD PARA PREVENIR EL ROBO EN SU VIVIENDA COMO: Evitar dejar la casa sola?',
 'P122D_2': 'ACTUALMENTE, ¿HAN ADOPTADO ALGUNA MEDIDA DE SEGURIDAD PARA PREVENIR EL ROBO EN SU VIVIENDA COMO: Colocar o adicionar cerrojos?',
 'P122D_3': 'ACTUALMENTE, ¿HAN ADOPTADO ALGUNA MEDIDA DE SEGURIDAD PARA PREVENIR EL ROBO EN SU VIVIENDA COMO: Colocar o adicionar cerraduras y/o candados?',
 'P122D_4': 'ACTUALMENTE, ¿HAN ADOPTADO ALGUNA MEDIDA DE SEGURIDAD PARA PREVENIR EL ROBO EN SU VIVIENDA COMO: Cambiar cerraduras y/o candados?',
 'P122D_5': 'ACTUALMENTE, ¿HAN ADOPTADO ALGUNA MEDIDA DE SEGURIDAD PARA PREVENIR EL ROBO EN SU VIVIENDA COMO: Tener perro guardián?',
 'P122D_6': 'ACTUALMENTE, ¿HAN ADOPTADO ALGUNA MEDIDA DE SEGURIDAD PARA PREVENIR EL ROBO EN SU VIVIENDA COMO: Poner puerta de rejas?',
 'P122D_7': 'ACTUALMENTE, ¿HAN ADOPTADO ALGUNA MEDIDA DE SEGURIDAD PARA PREVENIR EL ROBO EN SU VIVIENDA COMO: Instalar rejas en las ventanas?',
 'P122D_8': 'ACTUALMENTE, ¿HAN ADOPTADO ALGUNA MEDIDA DE SEGURIDAD PARA PREVENIR EL ROBO EN SU VIVIENDA COMO: Otro?',
 'P122D_O': 'ACTUALMENTE, ¿HAN ADOPTADO ALGUNA MEDIDA DE SEGURIDAD PARA PREVENIR EL ROBO EN SU VIVIENDA COMO: Otro?_Especifique',
 'P122E_1': '122E. ¿DESDE QUÉ AÑO ADOPTÓ ESTA MEDIDA?  Evitar dejar la casa sola?',
 'P122E_2': '122E. ¿DESDE QUÉ AÑO ADOPTÓ ESTA MEDIDA?  Colocar o adicionar cerrojos?',
 'P122E_3': '122E. ¿DESDE QUÉ AÑO ADOPTÓ ESTA MEDIDA?  Colocar o adicionar cerraduras y/o candados?',
 'P122E_4': '122E. ¿DESDE QUÉ AÑO ADOPTÓ ESTA MEDIDA?  Cambiar cerraduras y/o candados?',
 'P122E_5': '122E. ¿DESDE QUÉ AÑO ADOPTÓ ESTA MEDIDA?  Tener perro guardián?',
 'P122E_6': '122E. ¿DESDE QUÉ AÑO ADOPTÓ ESTA MEDIDA?  Poner puerta de rejas?',
 'P122E_7': '122E. ¿DESDE QUÉ AÑO ADOPTÓ ESTA MEDIDA?  Instalar rejas en las ventanas?',
 'P122E_8': '122E. ¿DESDE QUÉ AÑO ADOPTÓ ESTA MEDIDA?  Otro?',
 'P122F_1': '122F. ¿ESTA MEDIDA FUE ADOPTADA O SE INSTALÓ DURANTE LOS ÚLTIMOS 12 MESES DE………A ……….? Evitar dejar la casa sola?',
 'P122F_2': '122F. ¿ESTA MEDIDA FUE ADOPTADA O SE INSTALÓ DURANTE LOS ÚLTIMOS 12 MESES DE………A ……….? Colocar o adicionar cerrojos?',
 'P122F_3': '122F. ¿ESTA MEDIDA FUE ADOPTADA O SE INSTALÓ DURANTE LOS ÚLTIMOS 12 MESES DE………A ……….? Colocar o adicionar cerraduras y/o candados?',
 'P122F_4': '122F. ¿ESTA MEDIDA FUE ADOPTADA O SE INSTALÓ DURANTE LOS ÚLTIMOS 12 MESES DE………A ……….? Cambiar cerraduras y/o candados?',
 'P122F_5': '122F. ¿ESTA MEDIDA FUE ADOPTADA O SE INSTALÓ DURANTE LOS ÚLTIMOS 12 MESES DE………A ……….? Tener perro guardián?',
 'P122F_6': '122F. ¿ESTA MEDIDA FUE ADOPTADA O SE INSTALÓ DURANTE LOS ÚLTIMOS 12 MESES DE………A ……….? Poner puerta de rejas?',
 'P122F_7': '122F. ¿ESTA MEDIDA FUE ADOPTADA O SE INSTALÓ DURANTE LOS ÚLTIMOS 12 MESES DE………A ……….? Instalar rejas en las ventanas?',
 'P122F_8': '122F. ¿ESTA MEDIDA FUE ADOPTADA O SE INSTALÓ DURANTE LOS ÚLTIMOS 12 MESES DE………A ……….? Otro?',
 'P123': '¿EN SU CENTRO POBLADO EXISTE EL SERVICIO DE INTERNET EN CABINA PÚBLICA?',
 'P124': '¿EN SU CENTRO POBLADO EXISTEN INSTALACIONES PARA BRINDAR EL SERVICIO DE TELEFONÍA PÚBLICA?',
 'P125': '¿EN SU CENTRO POBLADO EXISTE SEÑAL DE TELEFONÍA CELULAR?',
 'P126': '¿TIENE QUE SALIR DE SU VIVIENDA PARA ENCONTRAR SEÑAL?',
 'P127_1': '¿CUAL ES EL TIPO DE ALUMBRADO QUE USA SU HOGAR:_ELECTRICIDAD',
 'P127_2': '¿CUAL ES EL TIPO DE ALUMBRADO QUE USA SU HOGAR:_PETROLEO GAS (Lámpara)',
 'P127_3': '¿CUAL ES EL TIPO DE ALUMBRADO QUE USA SU HOGAR:_VELA',
 'P127_4': '¿CUAL ES EL TIPO DE ALUMBRADO QUE USA SU HOGAR:_GENERADOR',
 'P127_5': '¿CUAL ES EL TIPO DE ALUMBRADO QUE USA SU HOGAR:_PANEL SOLAR',
 'P127_6': '¿CUAL ES EL TIPO DE ALUMBRADO QUE USA SU HOGAR:_OTRO',
 'P127_6_O': '¿CUAL ES EL TIPO DE ALUMBRADO QUE USA SU HOGAR:_OTRO/ESPECIFIQUE',
 'P128A_1': 'EN SU HOGAR, ¿LA ENERGÍA O COMBUSTIBLE QUE UTILIZA PARA COCINAR LOS ALIMENTOS ES: (Circule uno o más códigos) Electricidad?',
 'P128A_2': 'EN SU HOGAR, ¿LA ENERGÍA O COMBUSTIBLE QUE UTILIZA PARA COCINAR LOS ALIMENTOS ES: (Circule uno o más códigos) Gas (balón GLP)?',
 'P128A_3': 'EN SU HOGAR, ¿LA ENERGÍA O COMBUSTIBLE QUE UTILIZA PARA COCINAR LOS ALIMENTOS ES: (Circule uno o más códigos) .Gas natural (sistema de tuberías)?',
 'P128A_4': 'EN SU HOGAR, ¿LA ENERGÍA O COMBUSTIBLE QUE UTILIZA PARA COCINAR LOS ALIMENTOS ES: (Circule uno o más códigos) .Carbón?',
 'P128A_5': 'EN SU HOGAR, ¿LA ENERGÍA O COMBUSTIBLE QUE UTILIZA PARA COCINAR LOS ALIMENTOS ES: (Circule uno o más códigos) 5.Leña?',
 'P128A_6': 'EN SU HOGAR, ¿LA ENERGÍA O COMBUSTIBLE QUE UTILIZA PARA COCINAR LOS ALIMENTOS ES: (Circule uno o más códigos) .Bosta, estiércol?',
 'P128A_7': 'EN SU HOGAR, ¿LA ENERGÍA O COMBUSTIBLE QUE UTILIZA PARA COCINAR LOS ALIMENTOS ES: (Circule uno o más códigos) .Otro (residuos agrícolas, etc)?',
 'P128A_8': 'EN SU HOGAR, ¿LA ENERGÍA O COMBUSTIBLE QUE UTILIZA PARA COCINAR LOS ALIMENTOS ES: (Circule uno o más códigos) NO COCINAN',
 'P128A_O': 'EN SU HOGAR, ¿LA ENERGÍA O COMBUSTIBLE QUE UTILIZA PARA COCINAR LOS ALIMENTOS ES: OTRO/ESPECIFIQUE',
 'P129G': 'EL AGUA QUE UTILIZAN EN EL HOGAR, ¿PROCEDE PRINCIPALMENTE DE: ',
 'P129G_O': 'EL AGUA QUE UTILIZAN EN EL HOGAR, ¿PROCEDE PRINCIPALMENTE DE: Otro Especifique',
 'P129B': '¿EL AGUA ES POTABLE?',
 'P129C': 'RESULTADO OBTENIDO EN LA EVALUACIÓN DE LOS NIVELES DE CLORO RESIDUAL LIBRE EN LA MUESTRA DE AGUA DEL HOGAR',
 'P100_C_2': 'INFORMANTE DE LA PRUEBA DEL AGUA',
 'P129D_ENT': 'RESULTADO OBTENIDO EN LA EVALUACIÓN DE LOS NIVELES DE CLORO RESIDUAL LIBRE EN LA MUESTRA DE AGUA DEL HOGAR_Enteros',
 'P129D_DEC': 'RESULTADO OBTENIDO EN LA EVALUACIÓN DE LOS NIVELES DE CLORO RESIDUAL LIBRE EN LA MUESTRA DE AGUA DEL HOGAR_Decimales',
 'P129D_1': 'RESULTADO OBTENIDO EN LA EVALUACIÓN DE LOS NIVELES DE CLORO RESIDUAL LIBRE EN LA MUESTRA DE AGUA DEL HOGAR_No se realizo la prueba',
 'P129E': 'LA MUESTRA DE AGUA FUE EXTRAÍDA POR:',
 'P129F': 'LA MUESTRA DEL AGUA SE EXTRAJO DEL:',
 'P129F_O': 'LA MUESTRA DEL AGUA SE EXTRAJO DEL:Otros',
 'P129_DIA': 'RESULTADO OBTENIDO EN LA EVALUACIÓN DE LOS NIVELES DE CLORO RESIDUAL LIBRE EN LA MUESTRA DE AGUA DEL HOGAR_Dia',
 'P129_MES': 'RESULTADO OBTENIDO EN LA EVALUACIÓN DE LOS NIVELES DE CLORO RESIDUAL LIBRE EN LA MUESTRA DE AGUA DEL HOGAR_Mes',
 'P129_ANIO': 'RESULTADO OBTENIDO EN LA EVALUACIÓN DE LOS NIVELES DE CLORO RESIDUAL LIBRE EN LA MUESTRA DE AGUA DEL HOGAR_Anio',
 'P129_HORA_INI': 'RESULTADO OBTENIDO EN LA EVALUACIÓN DE LOS NIVELES DE CLORO RESIDUAL LIBRE EN LA MUESTRA DE AGUA DEL HOGAR_Hora_Inicio',
 'P129_MIN_INI': 'RESULTADO OBTENIDO EN LA EVALUACIÓN DE LOS NIVELES DE CLORO RESIDUAL LIBRE EN LA MUESTRA DE AGUA DEL HOGAR_Minuto_Inicio',
 'P130': '¿EL HOGAR TIENE EL SERVICIO DE AGUA TODOS LOS DÍAS DE LA SEMANA?',
 'P130A': '¿CUÁNTAS HORAS AL DÍA?',
 'P130B': '¿CUÁNTOS DÍAS A LA SEMANA TIENE ESTE SERVICIO?',
 'P130C': '¿CUÁNTAS HORAS AL DÍA?',
 'P131_1': '¿EN SU HOGAR EL AGUA LO UTILIZA PARA: Cocinar?',
 'P131_2': '¿EN SU HOGAR EL AGUA LO UTILIZA PARA: Aseo personal?',
 'P131_3': '¿EN SU HOGAR EL AGUA LO UTILIZA PARA: Lavar la ropa?',
 'P131_4': '¿EN SU HOGAR EL AGUA LO UTILIZA PARA: Regar el huerto o chacra?',
 'P131_5': '¿EN SU HOGAR EL AGUA LO UTILIZA PARA: Dar de beber a los animales domésticos?',
 'P131_6': '¿EN SU HOGAR EL AGUA LO UTILIZA PARA: Dar de beber a los animales de crianza?',
 'P131_7': '¿EN SU HOGAR EL AGUA LO UTILIZA PARA: Otro?',
 'P131_7_O': '¿EN SU HOGAR EL AGUA LO UTILIZA PARA: Otro_Especifique?',
 'P131A': 'EN LOS ÚLTIMOS 12 MESES DE………A ………. , ¿SU HOGAR REALIZÓ ALGÚN PAGO POR LA OPERACIÓN Y MANTENIMIENTO DEL SERVICIO DE AGUA?',
 'P131B': 'LA FRECUENCIA DE PAGO POR LA OPERACIÓN Y MANTENIMIENTO DEL SERVICIO DE AGUA ES:',
 'P131B_O': 'LA FRECUENCIA DE PAGO POR LA OPERACIÓN Y MANTENIMIENTO DEL SERVICIO DE AGUA ES:Especifique?',
 'P131C_A': '¿CUÁNTO PAGA EL HOGAR………………..POR LA OPERACIÓN Y MANTENIMIENTO DEL SERVICIO DE AGUA?_SOLES',

In [94]:
# from yes to 1 and 0 to no
df_urban_no_dpl.P172D.replace(('Si', 'No'), (1, 0), inplace=True)
df_urban_no_dpl.P172D

1        1
2        1
3        1
6        1
7        1
        ..
42148    1
42149    1
42150    0
42151    1
42152    0
Name: P172D, Length: 24342, dtype: category
Categories (2, int64): [0, 1]

In [95]:
df_urban_no_dpl.P172D.value_counts()

0    13254
1    11088
Name: P172D, dtype: int64

In [96]:
df_urban_no_dpl.groupby( [ 'CCDD' ,'CCPP' , 'CCDI', 'P172D' ] )[['P172D']].sum()

<ipython-input-96-6b501f7bb432>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_urban_no_dpl.groupby( [ 'CCDD' ,'CCPP' , 'CCDI', 'P172D' ] )[['P172D']].sum()

Empty DataFrame
Columns: []
Index: [(01, 01, 01, 0), (01, 01, 01, 1), (01, 01, 02, 0), (01, 01, 02, 1), (01, 01, 03, 0), (01, 01, 03, 1), (01, 01, 04, 0), (01, 01, 04, 1), (01, 01, 05, 0), (01, 01, 05, 1), (01, 01, 06, 0), (01, 01, 06, 1), (01, 01, 07, 0), (01, 01, 07, 1), (01, 01, 08, 0), (01, 01, 08, 1), (01, 01, 09, 0), (01, 01, 09, 1), (01, 01, 10, 0), (01, 01, 10, 1), (01, 01, 11, 0), (01, 01, 11, 1), (01, 01, 12, 0), (01, 01, 12, 1), (01, 01, 13, 0), (01, 01, 13, 1), (01, 01, 14, 0), (01, 01, 14, 1), (01, 01, 15, 0), (01, 01, 15, 1), (01, 01, 16, 0), (01, 01, 16, 1), (01, 01, 17, 0), (01, 01, 17, 1), (01, 01, 18, 0), (01, 01, 18, 1), (01, 01, 19, 0), (01, 01, 19, 1), (01, 01, 20, 0), (01, 01, 20, 1), (01, 01, 21, 0), (01, 01, 21, 1), (01, 01, 22, 0), (01, 01, 22, 1), (01, 01, 23, 0), (01, 01, 23, 1), (01, 01, 24, 0), (01, 01, 24, 1), (01, 01, 25, 0), (01, 01, 25, 1), (01, 01, 26, 0), (01, 01, 26, 1), (01, 01, 28, 0), (01, 01, 28, 1), (01, 01, 29, 0), (01, 01, 29, 1), (01, 01, 30, 0), (01, 01, 30, 1), (01, 01, 31, 0), (01, 01, 31, 1), (01, 01, 32, 0), (01, 01, 32, 1), (01, 01, 33, 0), (01, 01, 33, 1), (01, 01, 34, 0), (01, 01, 34, 1), (01, 01, 35, 0), (01, 01, 35, 1), (01, 01, 36, 0), (01, 01, 36, 1), (01, 01, 37, 0), (01, 01, 37, 1), (01, 01, 39, 0), (01, 01, 39, 1), (01, 01, 40, 0), (01, 01, 40, 1), (01, 01, 41, 0), (01, 01, 41, 1), (01, 01, 42, 0), (01, 01, 42, 1), (01, 01, 43, 0), (01, 01, 43, 1), (01, 01, 99, 0), (01, 01, 99, 1), (01, 02, 01, 0), (01, 02, 01, 1), (01, 02, 02, 0), (01, 02, 02, 1), (01, 02, 03, 0), (01, 02, 03, 1), (01, 02, 04, 0), (01, 02, 04, 1), (01, 02, 05, 0), (01, 02, 05, 1), (01, 02, 06, 0), (01, 02, 06, 1), (01, 02, 07, 0), (01, 02, 07, 1), (01, 02, 08, 0), (01, 02, 08, 1), ...]

[33600 rows x 0 columns]

In [97]:
df_urban_no_dpl.groupby( [ 'CCDD' ,'CCPP' , 'CCDI' ] )[['P172D']].mean()

<ipython-input-97-c6dc87d3d338>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_urban_no_dpl.groupby( [ 'CCDD' ,'CCPP' , 'CCDI' ] )[['P172D']].mean()

Empty DataFrame
Columns: []
Index: [(01, 01, 01), (01, 01, 09), (01, 02, 01), (01, 02, 02), (01, 02, 03), (01, 02, 05), (01, 02, 06), (01, 03, 06), (01, 03, 07), (01, 03, 12), (01, 04, 01), (01, 04, 03), (01, 05, 01), (01, 05, 02), (01, 05, 09), (01, 06, 01), (01, 07, 01), (01, 07, 02), (01, 07, 03), (01, 07, 06), (02, 01, 01), (02, 01, 05), (02, 05, 01), (02, 06, 01), (02, 07, 01), (02, 08, 01), (02, 08, 04), (02, 10, 01), (02, 11, 01), (02, 12, 01), (02, 17, 02), (02, 18, 01), (02, 18, 03), (02, 18, 06), (02, 18, 07), (02, 18, 08), (02, 18, 09), (02, 20, 01), (02, 20, 03), (03, 01, 01), (03, 01, 04), (03, 01, 09), (03, 02, 01), (03, 02, 04), (03, 02, 13), (03, 02, 15), (03, 02, 16), (03, 02, 20), (03, 04, 01), (03, 05, 01), (03, 05, 04), (03, 06, 01), (03, 06, 02), (03, 06, 04), (04, 01, 01), (04, 01, 02), (04, 01, 03), (04, 01, 04), (04, 01, 05), (04, 01, 07), (04, 01, 08), (04, 01, 09), (04, 01, 10), (04, 01, 12), (04, 01, 16), (04, 01, 17), (04, 01, 22), (04, 01, 23), (04, 01, 24), (04, 01, 26), (04, 01, 28), (04, 01, 29), (04, 02, 01), (04, 02, 04), (04, 02, 06), (04, 02, 08), (04, 03, 01), (04, 03, 02), (04, 03, 07), (04, 05, 20), (04, 07, 01), (04, 07, 02), (04, 07, 03), (05, 01, 01), (05, 01, 04), (05, 01, 10), (05, 01, 15), (05, 01, 16), (05, 02, 02), (05, 02, 03), (05, 03, 01), (05, 04, 01), (05, 04, 08), (05, 05, 01), (05, 05, 03), (05, 05, 07), (05, 05, 08), (05, 05, 09), (05, 06, 01), (05, 06, 02), ...]

[550 rows x 0 columns]

In [98]:
df_urban_no_dpl.groupby( [ 'CCDD' ,'CCPP' , 'CCDI' ], as_index = False )[['P172D']].mean()

<ipython-input-98-419bfc818594>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_urban_no_dpl.groupby( [ 'CCDD' ,'CCPP' , 'CCDI' ], as_index = False )[['P172D']].mean()

    CCDD CCPP CCDI
0     01   01   01
1     01   01   09
2     01   02   01
3     01   02   02
4     01   02   03
..   ...  ...  ...
545   25   02   02
546   25   03   01
547   25   03   02
548   25   03   04
549   25   03   05

[550 rows x 3 columns]

#### [Agg](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.agg.html)
Aggregate using one or more operations over the specified axis.

In [99]:
df_urban_no_dpl['P172D'] = df_urban_no_dpl['P172D'].astype( float )

In [100]:
df_urban_no_dpl.groupby( [ 'CCDD' ,'CCPP' , 'CCDI' ], as_index = False ).agg( { "P172D": "mean" } )

    CCDD CCPP CCDI     P172D
0     01   01   01  0.674074
1     01   01   09  0.750000
2     01   02   01  0.648148
3     01   02   02  0.125000
4     01   02   03  0.714286
..   ...  ...  ...       ...
545   25   02   02  0.000000
546   25   03   01  0.061728
547   25   03   02  0.216216
548   25   03   04  0.000000
549   25   03   05  0.142857

[550 rows x 4 columns]

In [101]:
import numpy as np

In [102]:
df3_rec = df_urban_no_dpl.groupby( [ 'CCDD' ,'CCPP' , 'CCDI' ] , 
                                as_index = False 
                               ).agg( 
                                    recycle_median = ( 'P172D', np.median ), 
                                    recycle_mean = ( 'P172D', np.mean ) 
                                )
df3_rec

    CCDD CCPP CCDI  recycle_median  recycle_mean
0     01   01   01             1.0      0.674074
1     01   01   09             1.0      0.750000
2     01   02   01             1.0      0.648148
3     01   02   02             0.0      0.125000
4     01   02   03             1.0      0.714286
..   ...  ...  ...             ...           ...
545   25   02   02             0.0      0.000000
546   25   03   01             0.0      0.061728
547   25   03   02             0.0      0.216216
548   25   03   04             0.0      0.000000
549   25   03   05             0.0      0.142857

[550 rows x 5 columns]

### 3.3.9. <a id='3.3.9'>Reshape</a>

#####  From Wide to Long

In [103]:
df3_rec.head()

  CCDD CCPP CCDI  recycle_median  recycle_mean
0   01   01   01             1.0      0.674074
1   01   01   09             1.0      0.750000
2   01   02   01             1.0      0.648148
3   01   02   02             0.0      0.125000
4   01   02   03             1.0      0.714286

In [104]:
df3_rec_stack = df3_rec.set_index(  [ 'CCDD' ,'CCPP' , 'CCDI' ]  ).stack().reset_index().rename( {"level_3" : "STATS", 
                                                                                0 : "VALUES" }, axis = 1 )
df3_rec_stack.head()

  CCDD CCPP CCDI           STATS    VALUES
0   01   01   01  recycle_median  1.000000
1   01   01   01    recycle_mean  0.674074
2   01   01   09  recycle_median  1.000000
3   01   01   09    recycle_mean  0.750000
4   01   02   01  recycle_median  1.000000

In [105]:
df3_rec_melt = df3_rec.melt( 
                    id_vars = [ 'CCDD' ,'CCPP' , 'CCDI' ] ,
                    var_name = 'STATS', 
                    value_name = 'VALUES'
                 )
df3_rec_melt

     CCDD CCPP CCDI           STATS    VALUES
0      01   01   01  recycle_median  1.000000
1      01   01   09  recycle_median  1.000000
2      01   02   01  recycle_median  1.000000
3      01   02   02  recycle_median  0.000000
4      01   02   03  recycle_median  1.000000
...   ...  ...  ...             ...       ...
1095   25   02   02    recycle_mean  0.000000
1096   25   03   01    recycle_mean  0.061728
1097   25   03   02    recycle_mean  0.216216
1098   25   03   04    recycle_mean  0.000000
1099   25   03   05    recycle_mean  0.142857

[1100 rows x 5 columns]

##### From Long to Wide

In [106]:
df3_rec_stack.set_index(  [ 'CCDD' ,'CCPP' , 'CCDI' , "STATS" ]  ).unstack().head()

                     VALUES
STATS          recycle_mean recycle_median
CCDD CCPP CCDI
01   01   01       0.674074            1.0
          09       0.750000            1.0
     02   01       0.648148            1.0
          02       0.125000            0.0
          03       0.714286            1.0

In [107]:
df4 = df3_rec_stack.set_index(  [ 'CCDD' ,'CCPP' , 'CCDI' , "STATS" ]   ).unstack().rename_axis( [None, None], axis = 1 )


df4.columns = df3_rec_stack.STATS.unique()

df4.reset_index().head()

  CCDD CCPP CCDI  recycle_median  recycle_mean
0   01   01   01        0.674074           1.0
1   01   01   09        0.750000           1.0
2   01   02   01        0.648148           1.0
3   01   02   02        0.125000           0.0
4   01   02   03        0.714286           1.0

In [108]:
df_l_w = df3_rec_stack.pivot( index = [ 'CCDD' ,'CCPP' , 'CCDI' ], 
                         columns = 'STATS' ,
                         values = 'VALUES' 
                        ).rename_axis( [None], axis = 1 ).reset_index()
df_l_w.head()

  CCDD CCPP CCDI  recycle_mean  recycle_median
0   01   01   01      0.674074             1.0
1   01   01   09      0.750000             1.0
2   01   02   01      0.648148             1.0
3   01   02   02      0.125000             0.0
4   01   02   03      0.714286             1.0

### 3.3.10. <a id='3.3.10'>[Merge](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.merge.html)</a>

In [109]:
df_urban_merge = df_urban_no_dpl.merge( df_l_w , on = [ 'CCDD' ,'CCPP' , 'CCDI' ] , how = "left" , validate = "m:1" ).head()

In [110]:
df_urban_merge.head()

,PER,ANIO,MES,CONGLOMERADO,NSELV,TSELV,VIVREM,AREA,CCDD,NOMBREDD,...,P184A_17,P184A_18,P187_9_O,P189_8_O,REGIONNATU,ESTRATO,MOD_ENC,FACTOR,recycle_mean,recycle_median
0,2.0,2020,09,03981,0120,Urbano,0.0,URBANO,14,LAMBAYEQUE,...,Pase,Pase,,,COSTA,Estrato D,Presencial,245.10805,0.478723,0.0
1,2.0,2020,09,03981,0189,Urbano,0.0,URBANO,14,LAMBAYEQUE,...,Pase,Pase,,,COSTA,Estrato D,Presencial,245.10805,0.478723,0.0
2,2.0,2020,09,03981,0189,Urbano,0.0,URBANO,14,LAMBAYEQUE,...,Pase,Pase,,,COSTA,Estrato D,Presencial,245.10805,0.478723,0.0
3,2.0,2020,09,06703,0037,Urbano,0.0,URBANO,01,AMAZONAS,...,Pase,Pase,,,SELVA,Estrato E más bajo,No Presencial,79.14997,0.420455,0.0
4,2.0,2020,09,03981,0057,Urbano,0.0,URBANO,14,LAMBAYEQUE,...,Pase,Pase,,,COSTA,Estrato D,Presencial,245.10805,0.478723,0.0

In [111]:
# See all your DataFrames
%whos DataFrame

Variable               Type         Data/Info
---------------------------------------------
cars                   DataFrame        brands  model  passen<...>   kia  truck           8
cars_subset            DataFrame        brands  model  passen<...>   kia  sedan           5
data2                  DataFrame       a  b  c\n0  1  2  3\n1  4  5  6\n2  7  8  9
dep1                   DataFrame          dep  year  pop\n0  <...>2.9\n5    Puno  2003  3.2
dep1_sort              DataFrame          dep  year  pop\n5  <...>1.7\n0    Lima  2000  1.5
df3_rec                DataFrame        CCDD CCPP CCDI  recyc<...>n\n[550 rows x 5 columns]
df3_rec_melt           DataFrame         CCDD CCPP CCDI      <...>\n[1100 rows x 5 columns]
df3_rec_stack          DataFrame         CCDD CCPP CCDI      <...>\n[1100 rows x 5 columns]
df4                    DataFrame                    recycle_m<...>n\n[550 rows x 2 columns]
df_l_w                 DataFrame        CCDD CCPP CCDI  recyc<...>n\n[550 rows x 5 columns]
df_urban               DataFrame           PER  ANIO MES CONG<...>24347 rows x 120 columns]
df_urban_main          DataFrame           PER  ANIO MES CONG<...>27154 rows x 491 columns]
df_urban_merge         DataFrame       PER  ANIO MES CONGLOME<...>n\n[5 rows x 122 columns]
df_urban_no_dpl        DataFrame           PER  ANIO MES CONG<...>24342 rows x 120 columns]
enapres2020_1          DataFrame           PER  ANIO MES CONG<...>42153 rows x 491 columns]
gradesA1               DataFrame      Students  Math  English<...>       15   17  16.333333
gradesA1_1             DataFrame      Students  Math  English<...>4  Rosalyn    17       15
gradesA2               DataFrame        Students  Math  Engli<...>  Leo    10       20    5
grades_total           DataFrame        Students  Math  Engli<...> Leo    10       20   5.0
grades_total_NA        DataFrame        Students  Math  Engli<...> Leo    10       20   5.0
grades_total_fill_na   DataFrame        Students  Math  Engli<...>    10       20       5.0
new_data               DataFrame           PER  ANIO MES CONG<...>24347 rows x 491 columns]