# If, Loops y While Loops

- <a href='1'>Condición If</a>
     - <a href='#1.1'>La estructura del código </a> 
     - <a href='#1.2'>Operadores identidad </a> 
- <a href='#2'> Loops </a> 
     - <a href='#2.1'>En NumPy </a> 
     - <a href='#2.2'> Range </a> 
     - <a href='#2.3'> En lista </a> 
     - <a href='#4.2.4.'> 4.2.4. For loop using range</a>
     - <a href='#4.2.5.'> 4.2.5. Nested For Loop</a>
     - <a href='#4.2.6.'> 4.2.6. Iterations over Pandas</a>
- <a href='#4.3.'> 4.3. Pass, Continue, Break, Try</a>
     - <a href='#4.3.1.'>4.3.1. Pass</a>
     - <a href='#4.3.2.'>4.3.2. Continue</a>
     - <a href='#4.3.3.'>4.3.3. Break</a>
     - <a href='#4.3.4.'>4.3.4. Try </a>
     
- <a href='#4.4.'>4.4. While Loop </a>
     - <a href='#4.4.1.'>4.4.1. Structure </a>
- <a href='#4.5.'>4.5. References </a>

In [ ]:
# Importar paquetes necesarios:
import numpy as np
import pandas as pd

# <a id='1'> Condifición If </a>

## <a id='1.1'> 1. La estructura del código</a>

La función **if** evalúa condiciones: 
- Igual: a == b
- No igual: a != b
- Menor que: a < b
- Menor o igual que: a <= b
- Mayor que: a > b
- Mayor o igual que: a >= b

Si se cumple la condición, sigue. Si no, se saltea.

In [ ]:
# Ejemplo: El resultado es un valor booleano.
A = 20
B = 30
resultado = A > B
resultado

False

In [5]:
# Cuando la condicionante sea verdad, se ejecutarán las instrucciones dentro del bloque if.
# Si no es verdad, no se ejecuta nada.
Economía = 2014
Sociología = 2019

In [ ]:
# No se ejecuta nada porque no se cumple la condición.
# Todo lo que esté dentro del bloque if (tiene tabulación) no se ejecutará.
if Economía > Sociología:
    print("Se ingresó primero a Economía")
    print("Aunque no se terminó la carrera")

In [ ]:
# Puntaje de las universidades peruanas en rankings
PUCP = 1022
UNMSM = 813

In [8]:
# Usamos 'else' para explicitar qué va a ocurrir si la condición no se cumple.
if UNMSM > PUCP:
    print("UNMSM es mejor que PUCP")
else:
    print("PUCP es la mejor universidad del Perú")

PUCP es la mejor universidad del Perú

* La función **if** mide la veracidad de una expresión lógica. El resultado es ser un **<font color='red'>boolean</font>**. En otras palarbas, el output es **<font color='red'>True</font>** or **<font color='red'>False</font>**.

## <a id='1.2'> 2. Operadores identidad </a> 

Estos operadores nos ayudan a comparar si las variables hacen referencia al mismo objeto
Tenemos **<font color = 'red' >is</font>** e **<font color = 'red' > is not</font>** como operadores identidad.

In [10]:
C = None
C

In [11]:
if C is None:
    print( 'Ohh C is None :(')

Ohh C is None :(

In [12]:
if C is not float:
    print( 'C is not a float')

C is not a float

* Diferencia entre los operadores **<font color = 'red' > ==</font>** e **<font color = 'red' > is</font>**:

  * **<font color = 'red' > ==</font>** compara los valores de ambos operandos y verifica su igualdad
  * **<font color = 'red' > is</font>** comprueba si ambos operandos hacen referencia al mismo objeto (es decir, si están presentes en la misma ubicación de memoria).

In [16]:
a = 5
b = 5

In [17]:
a is b

True

In [21]:
a = np.arange(0, 4)
b = np.array( [0, 1 , 2 , 3 ] )

In [22]:
a

array([0, 1, 2, 3])

In [23]:
b

array([0, 1, 2, 3])

In [24]:
a == b

array([ True,  True,  True,  True])

In [25]:
a is b

False

# <a id='2'> Loops </a> 

* Su premisa principa es acelerar un proceso que consideramos repetitivo. 
* Un bucle for se utiliza para iterar sobre una secuencia. Ejecuta un bloque de código un número definido de veces.

## <a id='2.1'> 1. In NumPy </a>

In [3]:
import numpy as np

In [ ]:
# Elevemos al cuadrado manualmente cada elemento de la lista:
sequence_ages1 = [ 26, 35, 42, 32, 41]

In [27]:
al_1 = 26**2
al_2 = 35**2
al_3 = 42**2
al_4 = 30**2
al_5 = 41**2

print(al_1)
print(al_2)
print(al_3)
print(al_4)
print(al_5)

676
1225
1764
900
1681

In [ ]:
# Ahora usemos un loop para elevar al cuadrado:
# Es mucho más rápido.
for i in sequence_ages1:
    print(i**2)

676
1225
1764
1024
1681

* Se puede aplicar a cualquier tipo de secuencia.
* Ahora, veremos un vector.

In [29]:
# Vector:
sequence_ages2 = np.array( [15, 20, 25, 30 , 35 , 40 , 50 ] )
sequence_ages2

array([15, 20, 25, 30, 35, 40, 50])

In [34]:
# Restar 10 a cada elemento:
# Podemos usar cualquier letra o letras como iterador: i, age, etc.
# Es mejor usar un iterador relacionado a lo que se hace
for age in sequence_ages2:
    print(age - 10)

5
10
15
20
25
30
40

In [35]:
# Multiplicamos *2
for age in sequence_ages2:
    print(age*2)

30
40
50
60
70
80
100

## <a id='2.2'>2. Range </a>
* Tener en cuenta que Python no toma el último valor del range(n)

* Para crear secuencias, Loop y Range es lo mismo

In [39]:
# El 'for' es el loop (la repetición)
# El 'range(5)' genera la secuencia secreta: 0, 1, 2, 3, 4
for i in range(5):
    print(i)

0
1
2
3
4

* Diferencias del for con el range: 
  * El loop (como el for) es el "motor" o la acción de repetir un bloque de código.
  * El range() es una función nativa de Python (técnicamente, un tipo de secuencia) que genera una lista de números. Actúa como el "combustible" o la "pista" que le dice al loop cuántas vueltas tiene que dar.

* El range por sí solo no repite ninguna acción, solo crea una "colección" de números lista para ser usada.
* El bucle for no necesita un range para funcionar. Su trabajo es simplemente recorrer cualquier cosa que tenga varios elementos (como una lista de textos).
* Normalmente los usamos juntos cuando queremos repetir un bloque de código una cantidad exacta de veces, pero sin tener que escribir una lista a mano.
* En conclusión: range() es el objeto que contiene los números, y el bucle for es la instrucción que ejecuta una acción repetitiva.

In [ ]:
# Solo Range: 
# No repite nada, solo dice lo que es: 
mis_numeros = range(5)
print(mis_numeros)

range(0, 5)

In [41]:
# Solo for:
# El bucle 'for' es la acción de recorrer la lista
nombres = ["Ulises", "Flor de María", "Genaro", "María"]
for persona in nombres:
    print("Hola", persona)

Hola Ulises
Hola Flor de María
Hola Genaro
Hola María

In [42]:
# Juntamos Range y for:
# El 'for' hace el trabajo de repetir.
# El 'range(5)' le da los 5 "boletos" (0, 1, 2, 3, 4) para que sepa cuántas veces hacerlo.
for numero in range(5):
    print("Ejecutando vuelta número:", numero)

Ejecutando vuelta número: 0
Ejecutando vuelta número: 1
Ejecutando vuelta número: 2
Ejecutando vuelta número: 3
Ejecutando vuelta número: 4

## <a id='2.3'>3. En lista </a>

In [44]:
# Aquí vamos a sumar los elementos de las listas anidadas.
class_age = [ [11, 12, 11] , [15, 16, 16] , [17, 17, 18] ]

# Iteramos sobre la lista anidada y sumamos los elementos de cada lista.
i = 0
for age in class_age:
    print( "La suma de los primeros elementos ES", class_age[0][i] + class_age[1][i] + class_age[2][i])
    i = i+1

La suma de los primeros elementos ES 43
La suma de los primeros elementos ES 45
La suma de los primeros elementos ES 45

In [26]:
ages = [ 21, 23, 25, 24, 20]

for age in ages:
    print( type(age) )

<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>

## <a id='2.4'>4. En Dictionario </a>

In [54]:
class_1 = { "students" : ['Miguel', 'Anthony', 'Paul', 'Rodrigo', 'Jason'] , 
           "age" : [20, 18, 15, 20, 22] }

In [55]:
class_1.keys()

dict_keys(['students', 'age'])

In [149]:
type(class_1.keys())

dict_keys

In [ ]:
# Paso 1:
class_1["students"]

['Miguel', 'Anthony', 'Paul', 'Rodrigo', 'Jason']

In [ ]:
# Paso 2:
class_1["age"]

[20, 18, 15, 20, 22]

In [159]:
# class_1_list = ['students', 'age']

In [58]:
# class_1["age"]

In [61]:
for est in class_1["students"]:
    print(est)

Miguel
Anthony
Paul
Rodrigo
Jason

In [63]:
for val in class_1["age"]:
    print (val)

20
18
15
20
22

In [75]:
class_1.keys()

dict_keys(['students', 'age'])

In [83]:
for key in class_1.keys():
    print(key)

students
age

### 4.2.4 <a id = '4.2.4.'>  For loop using range </a>

In [ ]:
[0, 1, 2, 3, 4]

In [88]:
for x in range(0, 5):
    print(x*4)

0
4
8
12
16

In [91]:
students[1]

'Anthony'

In [ ]:
[0,1,2,3,4,5]
range(0,5)

In [94]:
# Class
students = ['Miguel', 'Anthony', 'Paul', 'Rodrigo', 'Jason', 'Yajaira']

# Ages
ages = [20, 18, 15, 20, 22, 25]

for index in range(0, 6):
    print( f'{students[index]} is {ages[index]} years old'  )

Miguel is 20 years old
Anthony is 18 years old
Paul is 15 years old
Rodrigo is 20 years old
Jason is 22 years old
Yajaira is 25 years old

In [95]:
len(students)

6

In [99]:
# Class
students = ['Miguel', 'Anthony', 'Paul', 'Rodrigo', 'Jason', 'Yajaira', "maria"]

# Ages
ages = [20, 18, 15, 20, 22, 25, 40]

# len

for index in range(0, len(students)):
    print( f'{students[index]} is {ages[index]} years old'  )

Miguel is 20 years old
Anthony is 18 years old
Paul is 15 years old
Rodrigo is 20 years old
Jason is 22 years old
Yajaira is 25 years old
maria is 40 years old

In [93]:
# Class
students = ['Miguel', 'Anthony', 'Paul', 'Rodrigo', 'Jason', 'Yajaira']

# Ages
ages = [20, 18, 15, 20, 22, 25]

for index in range (0, len (students)):
     print ( f' { students[index] } is { ages[index] } years old.' )

 Miguel is 20 years old.
 Anthony is 18 years old.
 Paul is 15 years old.
 Rodrigo is 20 years old.
 Jason is 22 years old.
 Yajaira is 25 years old.

In [208]:
for i, element in enumerate( students ):
    print ( f'{ students[i] } is { ages[i] } years old.' )

Miguel is 20 years old.
Anthony is 18 years old.
Paul is 15 years old.
Rodrigo is 20 years old.
Jason is 22 years old.
Yajaira is 25 years old.

In [ ]:
for index in range (0, len (students)):
     print ( f'{ students[index] } is { ages[index] } years old.' )

In [199]:
len(students)

5

In [202]:
for index in range ( 0, len(students) ):
     print (f'{ students[ index ] } is { ages[ index ] } years old.')

Miguel is 20 years old.
Anthony is 18 years old.
Paul is 15 years old.
Rodrigo is 20 years old.
Jason is 22 years old.
Yajaira is 25 years old.

### 4.2.5 <a id='4.2.5.'>  Nested For Loop </a>

A for loop inside of another for loop.

In [100]:
age_class = [ [11, 12, 11] , [15, 16, 16] , [17, 17, 18]]
age_class

[[11, 12, 11], [15, 16, 16], [17, 17, 18]]

In [104]:
for room in age_class:
    print(room)
    
    for age in room:
        print(age*4)

[11, 12, 11]
44
48
44
[15, 16, 16]
60
64
64
[17, 17, 18]
68
68
72

In [36]:
for classs in age_class:
    print( classs )
    
    for age in classs:
        print( age )

[11, 12, 11]
11
12
11
[15, 16, 16]
15
16
16
[17, 17, 18]
17
17
18

In [105]:
# sequence
students = [ 'Justin' , 'Pogba', 'Paul', 'Carrillo', 'Xavi' ]

# age
gr_age = [ 20, 18, 15, 20, 22]

In [107]:
list(zip(students, gr_age))

[('Justin', 20), ('Pogba', 18), ('Paul', 15), ('Carrillo', 20), ('Xavi', 22)]

In [108]:
for stud, age in zip(students, gr_age):
    print(f' { stud } is { age } ')

 Justin is 20
 Pogba is 18
 Paul is 15
 Carrillo is 20
 Xavi is 22

In [37]:
# Loops
for student, age in zip( students , gr_age ):
    print(f'{ student } is { age }')

Justin is 20
Pogba is 18
Paul is 15
Carrillo is 20
Xavi is 22

In [38]:
## Diferent dimmensions
# sequence
students = [ 'Justin' , 'Pogba', 'Paul', 'Carrillo', 'Xavi' ]

# Edades
gr_age = [ 20, 18, 15, 20 ]

for student, age in zip( students , gr_age ):
    print(f'{ student } is { age }')

Justin is 20
Pogba is 18
Paul is 15
Carrillo is 20

In [109]:
class_age = [ [11, 12, 11] , [15, 16, 16] , [17, 17, 18] ]

i = 0
for age in class_age:
    print( "la suma de los primeros elementos", class_age[0][i] + class_age[1][i] + class_age[2][i])
    i = i+1

la suma de los primeros elementos 43
la suma de los primeros elementos 45
la suma de los primeros elementos 45

In [114]:
list( zip(class_age[0],class_age[1], class_age[2] ) )

for x, y, z in zip(class_age[0],class_age[1], class_age[2] ):
    print(x+y+ z)
    print(x*y*z, "\n")

43
2805

45
3264

45
3168

### 4.2.6. <a id = '4.2.6.'> Iterations over Pandas</a>

[Marine fishing extraction by destination and main species (thousands of tons)](https://estadisticas.bcrp.gob.pe/estadisticas/series/anuales/extraccion-pesquera-maritima-por-destino-y-principales-especies-miles-de-toneladas)

In [209]:
extraction_fish = pd.read_csv( r"..\_data\production_fish.csv" )

In [210]:
extraction_fish.columns

Index(['year', 'Consumo Industrial - Anchoveta',
       'Consumo Humano - Congelado - Concha de abanico',
       'Consumo Humano - Congelado - Langostino',
       'Consumo Humano - Congelado - Merluza',
       'Consumo Humano - Congelado - Calamar gigante',
       'Consumo Humano - Conservas - Atún',
       'Consumo Humano - Conservas - Caballa',
       'Consumo Humano - Conservas - Jurel',
       'Consumo Humano - Conservas - Sardina',
       'Consumo Humano - Fresco - Concha de abanico',
       'Consumo Humano - Fresco - Jurel', 'Consumo Humano - Fresco - Liza',
       'Consumo Humano - Fresco - Tollo', 'total_production'],
      dtype='object')

In [211]:
for index, row in extraction_fish.iloc[ :, 1:-2 ].iterrows():
    extraction_fish.at[ index, 'Max_min'] = row.max() - row.min()

In [212]:
extraction_fish.head()

,year,Consumo Industrial - Anchoveta,Consumo Humano - Congelado - Concha de abanico,Consumo Humano - Congelado - Langostino,Consumo Humano - Congelado - Merluza,Consumo Humano - Congelado - Calamar gigante,Consumo Humano - Conservas - Atún,Consumo Humano - Conservas - Caballa,Consumo Humano - Conservas - Jurel,Consumo Humano - Conservas - Sardina,Consumo Humano - Fresco - Concha de abanico,Consumo Humano - Fresco - Jurel,Consumo Humano - Fresco - Liza,Consumo Humano - Fresco - Tollo,total_production,Max_min
0,2005,8628.396,13.537000,9.021000,23.279000,235.630000,9.877000,25.711000,20.481000,0.16500,1.843080,56.167940,5.875600,0.430000,9030.413620,8628.23100
1,2006,5891.838,14.714000,11.295000,25.189000,365.729000,11.336000,58.245000,122.904000,0.04800,4.048000,136.827000,3.166000,1.584000,6646.923000,5891.79000
2,2007,6084.713,19.937000,13.548000,28.358488,379.556594,3.713293,26.248739,82.910307,0.00102,4.822991,134.887316,9.317622,2.834958,6790.849328,6084.71198
3,2008,6159.387,18.790000,12.817000,26.348398,484.162082,3.283711,47.694121,58.864202,0.00000,0.828187,80.092885,14.514054,2.933360,6909.715000,6159.38700
4,2009,5828.636,24.634372,11.877399,36.774763,355.106589,2.017061,51.355908,14.289041,0.00000,1.843072,47.079175,17.311344,4.057886,6394.982610,5828.63600

#### Exercise - Rename Columns

In [213]:
extraction_fish.head(3)

col_names = extraction_fish.columns.to_list()[ 1:-1 ]

for col in col_names:
    extraction_fish[ f'%_{col}' ]  = extraction_fish[ f'{col}' ] * 100 / extraction_fish[ 'total_production' ]

extraction_fish.head()

,year,Consumo Industrial - Anchoveta,Consumo Humano - Congelado - Concha de abanico,Consumo Humano - Congelado - Langostino,Consumo Humano - Congelado - Merluza,Consumo Humano - Congelado - Calamar gigante,Consumo Humano - Conservas - Atún,Consumo Humano - Conservas - Caballa,Consumo Humano - Conservas - Jurel,Consumo Humano - Conservas - Sardina,...,%_Consumo Humano - Congelado - Calamar gigante,%_Consumo Humano - Conservas - Atún,%_Consumo Humano - Conservas - Caballa,%_Consumo Humano - Conservas - Jurel,%_Consumo Humano - Conservas - Sardina,%_Consumo Humano - Fresco - Concha de abanico,%_Consumo Humano - Fresco - Jurel,%_Consumo Humano - Fresco - Liza,%_Consumo Humano - Fresco - Tollo,%_total_production
0,2005,8628.396,13.537000,9.021000,23.279000,235.630000,9.877000,25.711000,20.481000,0.16500,...,2.609294,0.109375,0.284716,0.226800,0.001827,0.020410,0.621986,0.065065,0.004762,100.0
1,2006,5891.838,14.714000,11.295000,25.189000,365.729000,11.336000,58.245000,122.904000,0.04800,...,5.502230,0.170545,0.876270,1.849036,0.000722,0.060900,2.058501,0.047631,0.023831,100.0
2,2007,6084.713,19.937000,13.548000,28.358488,379.556594,3.713293,26.248739,82.910307,0.00102,...,5.589236,0.054681,0.386531,1.220912,0.000015,0.071022,1.986310,0.137208,0.041747,100.0
3,2008,6159.387,18.790000,12.817000,26.348398,484.162082,3.283711,47.694121,58.864202,0.00000,...,7.006976,0.047523,0.690247,0.851905,0.000000,0.011986,1.159134,0.210053,0.042453,100.0
4,2009,5828.636,24.634372,11.877399,36.774763,355.106589,2.017061,51.355908,14.289041,0.00000,...,5.552894,0.031541,0.803066,0.223441,0.000000,0.028821,0.736189,0.270702,0.063454,100.0

## 4.3. <a id = '4.3.'> Pass, Continue, Break, Try</a>

|Function|Description|
|---|---|
| `Pass`| Allows you to handle the condition <br> without the loop being impacted in any way|
| `Continue`| The current iteration of the loop will be disrupted, <br> but the program will return to the top of the loop|
| `Break`| The loop will exit|
| `Try`| This command lets you test a block of code for errors.|
| `Exception`| An exception is an event, which occurs during <br> the execution of a program that disrupts the normal <br> flow of the program's instructions. <br> It allows you to raise a message to help the user.|


### 4.3.1 <a id = '4.3.1.'> Pass</a>

In [1]:
# for number in range(10):
#     print('Number is ' + str(number))

In [2]:
# a = 2
# if a == 1:
#     print(a)

In [3]:
prime = [2 , 3, 5, 7]

In [ ]:
# 0,1,2,3,4,5,6,7,8,9

In [6]:
for number in range(10):
    
    print('Number is ' + str(number))

Number is 0
Number is 1
Number is 2
Number is 3
Number is 4
Number is 5
Number is 6
Number is 7
Number is 8
Number is 9

In [9]:
2 in prime

True

In [11]:
# This is looking for prime numbers
for number in range(10):
    
    print('Number is ' + str(number))
    
    if (number in prime):
        # comment
        # pass
        print("This is a prime number")

    elif number == 3:
        #number = number + 1
        print( f'This number is {number}' )

    else:
        #number = number + 2
        print('This is not a prime number' , '\n')

print('Out of loop')

Number is 0
This is not a prime number

Number is 1
This is not a prime number

Number is 2
This is a prime number
Number is 3
This is a prime number
Number is 4
This is not a prime number

Number is 5
This is a prime number
Number is 6
This is not a prime number

Number is 7
This is a prime number
Number is 8
This is not a prime number

Number is 9
This is not a prime number

Out of loop

In [14]:
# This is looking for prime numbers
for number in range(10):
    
    print('Number is ' + str(number))
    
    if (number in prime):
        # comment
        pass
        print("This is a prime number")

    elif number == 3:
        #number = number + 1
        print( f'This number is {number}' )

    else:
        #number = number + 2
        print('This is not a prime number' , '\n')

print('Out of loop')

Number is 0
This is not a prime number

Number is 1
This is not a prime number

Number is 2
This is a prime number
Number is 3
This is a prime number
Number is 4
This is not a prime number

Number is 5
This is a prime number
Number is 6
This is not a prime number

Number is 7
This is a prime number
Number is 8
This is not a prime number

Number is 9
This is not a prime number

Out of loop

### 4.3.2. <a id = '4.3.2.'>Continue</a>

In [15]:
for number in range(10):
    print('Number is ' + str(number))
    
    if number == 5:
        # comment
        continue

    elif number == 3:
        #number = number + 1
        print( f'This number is {number}' )

    else:
        #number = number + 2
        print('Different number than 3 y 5' , '\n')
       
print('Out of loop')

Number is 0
Different number than 3 y 5

Number is 1
Different number than 3 y 5

Number is 2
Different number than 3 y 5

Number is 3
This number is 3
Number is 4
Different number than 3 y 5

Number is 5
Number is 6
Different number than 3 y 5

Number is 7
Different number than 3 y 5

Number is 8
Different number than 3 y 5

Number is 9
Different number than 3 y 5

Out of loop

In [21]:
21%2 == False

False

In [24]:
# find the even numbers
for i in range(10):
    
    if i % 2 == False:
        pass
    
    else:
        continue
    
    print("alex")
    print(i)

alex
0
alex
2
alex
4
alex
6
alex
8

### 4.3.3. <a id = '4.3.3.'>Break</a>

In [75]:
num_obs = 10

In [78]:
for number in range(num_obs):
    
    print('Number is ' + str(number))
    
    if number == 5:
        # comment
        print( f'This number is {number}' )

    elif number == 4:
        #number = number + 1
        print('This is the output of break.')
        print("The remaining iterations are:", num_obs - number)
        break
        
    else:
        #number = number + 2
        print('Different number =! 3, 5', "\n")
    

print('Out of loop')

Number is 0
Different number =! 3, 5

Number is 1
Different number =! 3, 5

Number is 2
Different number =! 3, 5

Number is 3
Different number =! 3, 5

Number is 4
This is the output of break.
The remaining iterations are: 6
Out of loop

In [47]:
for number in range(10):
    if number == 5:
        # comment
        raise Exception('This is the output of exception.')

    elif number == 3:
        #number = number + 1
        print( f'This number is {number}' )

    else:
        #number = number + 2
        print('Different number')

    print('Number is ' + str(number))

print('Out of loop')

Different number
Number is 0
Different number
Number is 1
Different number
Number is 2
This number is 3
Number is 3
Different number
Number is 4

Exception: This is the output of exception.

In [31]:
for i in range(5):
    if i == 3:
        print(i)
        pass  # Do nothing when i is 3
    print("this is the number=", i)

this is the number= 0
this is the number= 1
this is the number= 2
3
this is the number= 3
this is the number= 4

In [28]:
for i in range(5):
    if i == 3:
        continue  # Skip the rest of the code in the loop for this iteration
    print(i)

0
1
2
4

In [29]:
for i in range(5):
    if i == 3:
        break  # break in 3
    print(i)

0
1
2

### 4.3.4. <a id = '4.3.4.'> Try </a>

|Function|Description|
|---|---|
|`except`| Run a code if an error occurs.|
|`else`| The code will be executed whether there is no error.|
|`finally`| The code will be executed <br> does no matter whether or not the try raises an exception.|

`except`: Run a code if an error occurs.

In [32]:
x = 'Hola'

In [37]:
print(x + 4)

TypeError: can only concatenate str (not "int") to str

In [38]:
alex

NameError: name 'alex' is not defined

In [41]:
try:
    print(x+4)
    
except TypeError:
    print("An error tipo = TypeError")
    
except NameError:
    print("Variable x is not defined")
    
except:
    print("Something else went wrong")

An error tipo = TypeError

In [45]:
name = "John"

print(name)

John

In [46]:
try:
    print(namme)
    
except TypeError:
    # print(5+5)
    print("An error tipo TypeError")
    
except NameError:
    print("the correct label of the variable is name" )
    print("Variable x is not defined")
    
except:
    print("Something else went wrong")

the correct label of the variable is name
Variable x is not defined

In [250]:
try:
    print(namme)
    
# except TypeError:
#     print(5+5)
#     print("An error tipo TypeError")
    
# except NameError:
#     print("the correct label of the variable is name" )
#     print("Variable x is not defined")
    
except:
    print("There is an error")

There is an error

`else`: The code will be executed whether there is no error.

In [61]:
x = "10"

In [62]:
try:
    x + 4
    
except:
    print("Something went wrong")
    #print( 5 + 4)

else:
    print("Nothing went wrong")
    
    try:
        print( x + "2")    
    except:
        print("error 2")

Something went wrong

In [71]:
x = "10"

In [72]:
try:
    a = x + 4
    
except:
    print("Something went wrong")
    a = int(x) + 4 
    #print( 5 + 4)

else:
     print( f'the sum is {x}')

Something went wrong

`finally`: The code will be executed does no matter whether or not the try raises an exception.

In [68]:
x = 10

In [69]:
try:
    #print(x + 4)
    a = x + 4 
    
except:
    print("Something went wrong")
    a = int(x) + 4 
     
finally:
    print( f'the sum is {x}')

the sum is 10

In [67]:
s = 16
if s:
    print(s)

16

# <a id='4'> While Loop </a>
* While loop se utiliza para repetir código mientras la condición sea verdadera. Cuando la expresión lógica es falsa, el código terminará su ejecución.
* Diferencias con Loop:
  * Mientras que el Loop acaba cuando se llega al último elemento
  * El WhileLoop se acaba cuando el stament no se cumpla más, por eso el corazón de su estructura es un **break code**: algo que pueda romper el código.

## <a id='4.4.1.'> 1. Estructura </a>

while <font color='green'>condition</font>: <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;code 1<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font color='red'>break code</font><br><br>

* El operador break se utiliza para interrumpir y salir inmediatamente de un bucle (como un while o un for), sin importar si la condición principal del bucle sigue siendo verdadera.
* Es indispensable su presencia, de lo contrario seguirá operando hasta el infinito.

In [ ]:
i = 1

while i < 6 : 
    print ("Soy un estudiante de kinder porque mi edad es", i)
    
    # break code
    # Mientras la condición sea verdadera, se ejecutará el bloque de código dentro del while
    # Específicamente, la "i" debe iterar hasta 5, dado que i+1 es 6. Cuando llegue ese momento, se detiene (rompe) el código.
    i = i + 1

Soy un estudiante de kinder porque mi edad es 1
Soy un estudiante de kinder porque mi edad es 2
Soy un estudiante de kinder porque mi edad es 3
Soy un estudiante de kinder porque mi edad es 4
Soy un estudiante de kinder porque mi edad es 5

* El While Loop es más usado cuando hay web scraping y no se conoce el fin de las páginas a revisar.
* Si sé que hay 5 páginas, uso un Loop solamente.

In [100]:
i = 1

while i < 10 :
    
    print(i+10)
    
    # Break code 
    i = i + 5

11
16

#### Excersice
1. Print $2^n$, but the result is less than 10,000.

In [23]:
x = 2

while x < 10000:
    print(x)
    
    #break code
    x = 2*x
    print("now i is ", x)

2
now i is  4
4
now i is  8
8
now i is  16
16
now i is  32
32
now i is  64
64
now i is  128
128
now i is  256
256
now i is  512
512
now i is  1024
1024
now i is  2048
2048
now i is  4096
4096
now i is  8192
8192
now i is  16384

3. Print all elements of an array.

In [4]:
import numpy as np

edad = np.array([ 3, 6, 7, 10, 15, 17, 18, 31, 26, 88 , 100, 120, 110])
i = 0

while i < edad.size:
    
    print(edad[i])
    i += 1

3
6
7
10
15
17
18
31
26
88
100
120
110