# Funciones y Clases

In [1]:
import pickle
import pandas as pd
import numpy as np

- <a href='##1.'>Funciones</a>
     - <a href='##5.1.1.'>5.1.1. The Importance of Python Functions </a> 
     - <a href='##5.1.2.'>5.1.2. Basic structure of a function </a> 
     - <a href='##5.1.3.'>5.1.3. Function without `return` function </a> 
     - <a href='##5.1.5.'>5.1.5. Multiple objects for return </a> 
     - <a href='##5.1.5.'>5.1.5. If condition with return </a>
     - <a href='##5.1.6.'>5.1.6. Default values to parameters </a> 
     - <a href='##5.1.7.'>5.1.7. Specify the type of a parameter and the type of the return type of a function </a> 
     - <a href='##5.1.8.'>5.1.8. Local variables VS Global variables </a> 
     - <a href='##5.1.9.'>5.1.9. Args </a> 
     - <a href='##5.1.10.'>5.1.10. Kwargs </a> 
- <a href='##5.2.'>5.2. Class </a> 
     - <a href='##5.2.1.'>5.2.1. The Importance of Python Classes </a> 
     - <a href='##5.2.2.'> 5.2.2. Defining a class </a> 
     - <a href='##5.2.3.'> 5.2.3. Attributes </a> 
     - <a href='##5.2.5.'> 5.2.5. Method </a>
     - <a href='##5.2.6.'> 5.2.6. \_\_init\_\_() </a>
     - <a href='##5.2.7.'> 5.2.7. Self </a>
- <a href='##5.3.'>5.3. References </a>

#  <a id='#1'>Funciones</a>

## <a id = '#1.1.'> 1. Importancia de las funciones en Python </a>

Una función es como una **caja** porque recibe un input y arroja un output. Nosotros especificamos lo que se quiere crear. Características de las funciones:
* **Abstracción y Reutilización:** Replica el código que usarás una y otra vez.
* **Modularidad:** Las funciones permiten que los procesos complejos se dividan en pasos más pequeños.
* **Separación de Espacios de Nombres (Namespace):** Permite utilizar variables dentro de una función de Python incluso si tienen el mismo nombre que otras variables definidas en diferentes funciones o en el programa principal.

## <a id='1.2.'> 2. Basic structure of a function </a> 
* Una función requiere **parámetros**, **código** y la instrucción **return** function. La palabra clave **def** introduce la definición de función en Python.
* Esta es la estructura básica de una función:

    <font size="4">
def name_function<font color='green'>( parameter1, parameter2 )</font>: <br> <br>
&nbsp;&nbsp;&nbsp;&nbsp;Code<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;<font color='green'>return</font> final_output<br>
</font>

In [1]:
# Siempre importamos numpy
import numpy as np

In [ ]:
def mult (x, y):
    prod = x*y # Lo que está dentro de la caja

    return prod

In [ ]:
age_list = [35, 40, 28, 21]
# Calcular el número de elementos: len
len(age_list)

# Sé que son 4 elementos, pero al hacer este loop me mostrará valores del 0 al 3:
for i in range ( len (age_list) ):
    print(i)

0
1
2
3

In [ ]:
# Función que calcula el cuadrado de cada número de una lista dada, como age_list
def power(x):
  return [num**2 for num in x]

# Asigna 'age_list' como el parámetro 'x' de la función e imprime el resultado
print(power(age_list))

[1225, 1600, 784, 441]

## <a id='#1.3.'>3. Función sin `return` </a> 
Cuando definimos una función sin la instrucción `return`, la función generada no retoma ninguna salida.

In [ ]:
# Con return
x2 = 5
y2 = 10

In [ ]:
# Empiezas con un def (input) y terminas con un return (output)
# No se termina con un print a diferencia de R
def calculator_square( x, y ):
    
    x2 = x * x
    y2 = y * y
    
    result = x2 * y2   
    return result

In [13]:
calculator_square( x2, y2 )

2500

In [15]:
# Sin return
x2 = 5
y2 = 10

In [21]:
def calculator_square( x, y ):
    
    x2 = x * x
    y2 = y * y
    
    result = x2 * y2   
    # return result

In [22]:
return2 = calculator_square( 4, 7 )
return2

* Si bien calcula, no hay un output sin `return`.

### <a id='#1.5.'>5. Múltiples objetos de retorno</a> 
* El output de una función puede tener varios objetos. Por defecto, se almacenan en una **tupla**.
* La tupla se almacena en paréntesis.

In [ ]:
def calculator_square( x, y ):
    
    x2 = x * x
    y2 = y * y
    
    result = x2 * y2   
    
    # 3 objetos: resultado y los cuadrados de los objetos iniciales
    return result, x2, y2

In [ ]:
# Defino que x = 3, y = 4 más directamente
calculator_square(3, 4)

(144, 9, 16)

In [ ]:
# Ahora, x = 5, y = 6
result4 = calculator_square(5, 6)
result4

(900, 25, 36)

In [27]:
type(result4)

tuple

## <a id='#1.6.'>6. Valores por defecto para parámetros </a>

Podemos definir valores de los parámetros

In [ ]:
# Defino el valor por default (y)
def calculator_base_10(x, y = 10):
    result = x*y
    return result

In [ ]:
# Ahora solo es necesario colocar x
# Podemos colocar cualquier número, se multiplicará con el que está por default (10):
calculator_base_10(5)

50

* Imaginemos que quiero unir textos con la unión de apellidos

In [39]:
def student_school (x, y, c="Colegio Nacional"):
    student = x + " " + y + " " + "estudia en el " + c
    return student

In [42]:
# c es el valor por default. Se puede cambiar, pero por defecto viene "Colegio Nacional"
student_school ("Ricardo", "Luis")
# student_school ("Ricardo", "Luis", c="Trilce")

'Ricardo Luis estudia en el Colegio Nacional'

## Ejercicio

In [44]:
import pandas as pd

In [ ]:
# Base de datos de GitHub Innovation
# Observo la cantidad de programadores por tópicos por país

url = "https://raw.githubusercontent.com/github/innovationgraph/refs/heads/main/data/topics.csv"
topics_data = pd.read_csv(url)
topics_data

       num_pushers                   topic iso2_code  year  quarter
0             7206                  python        EU  2020        1
1             6739                  python        US  2020        1
2             5231              javascript        EU  2020        1
3             5025              javascript        US  2020        1
4             3874                    java        EU  2020        1
...            ...                     ...       ...   ...      ...
82586          101                      vr        US  2026        1
82587          101  monte-carlo-simulation        US  2026        1
82588          101    modelcontextprotocol        US  2026        1
82589          101                  python        UZ  2026        1
82590          101                     erp        VN  2026        1

[82591 rows x 5 columns]

In [51]:
# Quiero saber en cuántos países se discuten tópicos exclusivos de Deep Learning:
# Defino una función

def count_unique_countries_for_topic(df, target_topic="machine-learning"):

    # Filtra las filas donde el tópico sea igual al que queremos buscar:
    filtered_df = df[df['topic'] == target_topic]
    
    # Obtengo cuántos iso2_code (países únicos) únicos hay:
    unique_countries = filtered_df['iso2_code'].nunique()
    
    return unique_countries

In [53]:
count_unique_countries_for_topic(df = topics_data, target_topic = "machine-learning")

43

In [54]:
# Ahora queremos los top 5 países por número de programadores (num_pushers)
def top_countries_by_topic(df, target_topic="machine-learning", top_n=5):

    # Filtro por tópico:
    filtered_df = df[df['topic'].str.lower() == target_topic.lower()]
    
    # Agrupamos por país y sumamos los números de publicadores por país:
    country_pushers = filtered_df.groupby('iso2_code')['num_pushers'].sum()
    
    # Orden descendiente:
    top_countries = country_pushers.sort_values(ascending=False).head(top_n)
    return top_countries

In [ ]:
# Podemos cambiar el tópico a voluntad
top_countries_by_topic(topics_data, "machine-learning")

iso2_code
US    84231
EU    53593
IN    47074
DE    19047
GB    14635
Name: num_pushers, dtype: int64

### <a id='#5.1.7.'>5.1.7. Specify the type of a parameter and the type of the return type of a function </a> 

It is important to note that Python won't raise a TypeError if you pass a float into x, the reason for this is one of the main points in Python's design philosophy: "We're all consenting adults here", which means you are expected to be aware of what you can pass to a function and what you can't. If you really want to write code that throws TypeErrors you can use the isinstance function to check that the passed argument is of the proper type or a subclass of it like this:

In [88]:
def calculator_base_5( x : int, y : float ) -> float:
    
    result = x * y
    
    return result

In [96]:
x2**"Trea"

TypeError: unsupported operand type(s) for ** or pow(): 'int' and 'str'

In [91]:
calculator_base_5( 10.0, 15 )

150.0

In [97]:
def calculator_base_5( x : int, y : float ) -> float:
    
    if not isinstance( x , int ):
        raise TypeError( "X variable is not int type.")
        
    if not isinstance( y, float ):
        raise TypeError( "Y variable is not float type.")

    result = x * y
    
    
    return result

In [103]:
calculator_base_5( 5, 3.8)

19.0

In [26]:
calculator_base_5( 4.5, 3)

TypeError: X variable is not int type.

In [27]:
calculator_base_5( 4, 3 )

TypeError: Y variable is not float type.

In [28]:
calculator_base_5( 4, 3.8 )

15.2

### <a id='#5.1.8.'>5.1.8. Local variables VS Global variables </a> 

|Variables|Definition|
|---|---|
|Global Variables| Variables declared outside a function.|
|Local Variables | Variables declared inside a function.|

The parameters and the variables created inside a function are local variables. They take values when the function is executed; however, they do not exist outside the function since they belong to a different namespace. A namespace is a system that has a unique name for every object in Python. When a Python function is called, a new namespace is created for that function, one that is distinct from all other namespaces that already exist. That is the reason we can use various functions with parameters and variables with the same name. Additionally, it explains why the variables generated inside a function do not exist outside the defined function namespace.

#### Example

In [29]:
pwd

'C:\\Users\\Alexander\\Documents\\GitHub\\Diplomado_PUCP\\Lecture_5'

In [30]:
%run "function_1.ipynb"

In [31]:
def lower_case( string1  ):
    
    str_result = string1.lower()
    
    return str_result

In [32]:
lower_case( "ADRIANA")

'adriana'

In [33]:
str_result

NameError: name 'str_result' is not defined

In [34]:
result2 = lower_case( "DIPLOMA")
result2

'diploma'

Now, we try to call the variable `str_result`.

In [35]:
str_result

NameError: name 'str_result' is not defined

We can see that `str_result` is not defined. It does not exist in the main space. It was defined in the namespace of **lower_case**. In concluion, `str_result` is a local variable. <br>
`result2` is a global variable.

### <a id='#5.1.9.'>5.1.9. Args </a> 

The special syntax **\*args** in function definitions in python is used to pass a variable number of arguments to a function. The object **\*args** is a **tuple** that contains all the arguments. When you build your code, you should consider **\*args** as a **tuple**.

In [36]:
def calculator( *args ):
    
    print( f"args is a {type( args )}" )
    # Get the first value
    result = args[ 0 ]
    
    # Keep the rest of values
    args1 = args[ 1: ]
    
    # multiply all elements
    for element in args1:
        result = result * element
    
    return result

In this example, the values `8, 9, 50 and 40` are storing in a list.

In [37]:
calculator( 8, 9, 50, 40, 10, 17 )

args is a <class 'tuple'>

24480000

We can use **\*args** with a different name (e.g., **\*list_vars** ). We should keep the asterisk (**\***).

In [132]:
def calculator( *list_vars ):
    
    print( f"args is a { type( list_vars ) }" )
    # Get the first value
    result = list_vars[ 0 ]
    
    # Keep the rest of values
    list_vars1 = list_vars[ 1: ]
    
    # multiply all elements
    for element in list_vars1:
        result = result * element
    
    return result

In [134]:
calculator( 8, 9, 50, 40, 23, 20, 12 )

args is a <class 'tuple'>

794880000

### <a id='#5.1.10.'>5.1.10. Kwargs </a> 

The special syntax **\*kwargs** in function definitions in python is used to pass a keyworded, variable-length argument list. We use the name kwargs with the double star. The reason is because the double star allows us to pass through keyword arguments (and any number of them).

In [142]:
def calculator( *list_vars, **kwargs):
    
    print( type( list_vars ) )
    print( type( kwargs ) )
    
    if ( kwargs[ 'function' ] == "Potencia" ) :
        
        # Get the first value
        result = potencia( list_vars )
    
    elif ( kwargs[ 'function' ] == "multiplication" ) :

        # Get the first value
        result = list_vars[ 0 ]

        # Keep the rest of values
        list_vars2 = list_vars[ 1: ]

        # multiply all elements
        for element in list_vars2:
            result = result * element
    else:
        raise ValueError( f"The function argument {kwargs[ 'function' ]} is not supported." )

    return result

In [140]:
calculator( 4, 5, 6, 7, 8, function = "addition" )

<class 'tuple'>
<class 'dict'>

30

In [141]:
calculator( 4, 5, 6, 7, 8, function = "division" )

<class 'tuple'>
<class 'dict'>

ValueError: The function argument division is not supported.

## Excersise
#### Importing a Dictionary

The `places_result` dictionary stores information from a Google API request that aims to geolocate all the National Identity Management Commission establishments in Nigeria. We want to store the results in a Pandas DataFrame. We want to keep the name of the establishment and its coordiantes.

In [150]:
dictionary_places = open( r"..\_data\places_result", "rb")
places_result = pickle.load( dictionary_places )

In [151]:
# It is a dictionary
type( places_result )

dict

In [152]:
# See all the establishments

i = 0
while True:
    try:
        i = i + 1
        print( places_result['results'][i]['name'] )
    except:
        break

National Identity Management Commission (Nimc)
National Identity Management Commission NIMC
National Identity Management Commission
National Identity Management Commission (Nimc)
National Identity Management Commission
National Identity Management Commission
National Identity Management Commission (Nimc)
National Identity Management Commission
National Identity Management Commission (Nimc)
National Identity Management Commission (Nimc)
National Identity Management Center
National Identity Management Commision (NIMC) Lagos
National Identity Management Commission
National Identity Management Commission (Nimc)
National Identity Management Commission Umuahia
National Identity Management Commission
National Identity Management Commission (Nimc)
National Identity Management Commission, Northwest Zonal Office
National Identity Management Commission Nimc

In [153]:
# We want to iterate over all the results to get the location of every point
places_result['results'][0]['geometry']['location']

{'lat': 9.065977, 'lng': 7.4549606}

`places_result` is a nested dictionary. It is composed of a list, dictionary, and a dictionary.

First, we are going to do it using a for loop. We are not going to use a function. After we get our expected results, we will define a function.

##### We can do it lists

In [154]:
from tqdm import tqdm

In [156]:
# Lists
latitudes = []
longitudes = []
institutions = []


# define all the results
results = places_result[ 'results' ]
# loop para guardar cada uno de los elementos
for row in tqdm( range( 0 , len( results ) ) ):
    
    # latitude
    lat = results[ row ]['geometry']['location']['lat']
    
    # Longitude
    lng = results[ row ]['geometry']['location']['lng']
    
    # nombre de la institution
    institution = results[ row ]['name']
    
    # Save results
    latitudes.append( lat )
    longitudes.append( lng )
    institutions.append( institution )
    
# Diccionario
final_result = { 'Institution': institutions, 'Latitud' : latitudes, 'Longitud' : longitudes }
# Dataframe
df_result = pd.DataFrame( final_result )
df_result

100%|██████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:00<?, ?it/s]

                                          Institution    Latitud  Longitud
0             National Identity Management Commission   9.065977  7.454961
1      National Identity Management Commission (Nimc)   8.450151  4.542503
2        National Identity Management Commission NIMC   8.505730  8.531775
3             National Identity Management Commission   9.058854  7.468078
4      National Identity Management Commission (Nimc)   9.895973  8.931434
5             National Identity Management Commission   9.892295  8.917566
6             National Identity Management Commission   9.857233  7.967972
7      National Identity Management Commission (Nimc)   7.711656  8.526523
8             National Identity Management Commission  11.989994  8.489165
9      National Identity Management Commission (Nimc)  10.310332  9.826602
10     National Identity Management Commission (Nimc)  10.592473  7.449456
11                National Identity Management Center   5.471781  7.008344
12  National Identity Management Commision (NIMC) ...   6.617086  3.357951
13            National Identity Management Commission   6.460106  7.579009
14     National Identity Management Commission (Nimc)   9.076770  7.493777
15    National Identity Management Commission Umuahia   5.502502  7.517956
16            National Identity Management Commission   4.822006  7.007972
17     National Identity Management Commission (Nimc)  11.988203  8.496804
18  National Identity Management Commission, North...  10.543617  7.460988
19       National Identity Management Commission Nimc   4.849608  7.052736

##### We can do it using iteration over rows of a DataFrame

In [157]:
df2 = pd.DataFrame( columns = ['Institution','Latitude','Longitud'] )

results = places_result['results']

for fila in tqdm(range( 0 , len( results ) )):
    
    df2.loc[fila] = [results[ fila ]['name'], \
                       results[ fila ]['geometry']['location']['lat'], \
                       results[ fila ]['geometry']['location']['lng']]
    
df2

100%|█████████████████████████████████████████████████████████████████████████████████| 20/20 [00:00<00:00, 466.35it/s]

                                          Institution   Latitude  Longitud
0             National Identity Management Commission   9.065977  7.454961
1      National Identity Management Commission (Nimc)   8.450151  4.542503
2        National Identity Management Commission NIMC   8.505730  8.531775
3             National Identity Management Commission   9.058854  7.468078
4      National Identity Management Commission (Nimc)   9.895973  8.931434
5             National Identity Management Commission   9.892295  8.917566
6             National Identity Management Commission   9.857233  7.967972
7      National Identity Management Commission (Nimc)   7.711656  8.526523
8             National Identity Management Commission  11.989994  8.489165
9      National Identity Management Commission (Nimc)  10.310332  9.826602
10     National Identity Management Commission (Nimc)  10.592473  7.449456
11                National Identity Management Center   5.471781  7.008344
12  National Identity Management Commision (NIMC) ...   6.617086  3.357951
13            National Identity Management Commission   6.460106  7.579009
14     National Identity Management Commission (Nimc)   9.076770  7.493777
15    National Identity Management Commission Umuahia   5.502502  7.517956
16            National Identity Management Commission   4.822006  7.007972
17     National Identity Management Commission (Nimc)  11.988203  8.496804
18  National Identity Management Commission, North...  10.543617  7.460988
19       National Identity Management Commission Nimc   4.849608  7.052736

In [160]:
def dict_output( dictionary , output = 'tuples'):
    
    # key results
    results = dictionary['results']
    
    # Lists
    latitudes = []
    longitudes = []
    inst = []
    
    # iterate over values and store in lists
    # we are going to use lists apporach
    for fila in range( 0 , len( results ) ):
        # latitude
        lat = results[ fila ]['geometry']['location']['lat']

        # Longitude
        lng = results[ fila ]['geometry']['location']['lng']

        # nombre de la institucion
        institucion = results[ fila ]['name']

        # Save results
        latitudes.append( lat )
        longitudes.append( lng )
        inst.append( institucion )
    
    # Store all values in 
    # dictionary
    results_dict = { 'Instituciones': institutions, 'Latitud' : latitudes, 'Longitud' : longitudes }
    
    # pandas
    results_pd = pd.DataFrame( results_dict )
    
    # tuple
    results_tuple = ( latitudes , longitudes , inst )
    
    # We can use return with if condition
    if output == 'dataframe':
        return results_pd
    
    elif output == 'dictionary':
        return results_dict
    
    elif output == 'tuple':
        return results_tuple
    
    else:
        raise Exception( f'''The output value ({output}) is wrong. \nYou can only use `tuple`, `dataframe`, or `dictionary` as argument variables.''' )

In [161]:
dict_output( places_result, output = "tuple" )

([9.065977,
  8.450151,
  8.50573,
  9.058854499999999,
  9.895973,
  9.892294699999999,
  9.8572331,
  7.711655800000001,
  11.9899944,
  10.310332,
  10.592473,
  5.4717813,
  6.617086,
  6.460105899999999,
  9.07677,
  5.5025021,
  4.822006,
  11.988203,
  10.5436173,
  4.8496083],
 [7.4549606,
  4.542503,
  8.531774799999999,
  7.468077600000001,
  8.931434,
  8.9175658,
  7.967971899999998,
  8.5265235,
  8.4891647,
  9.826602,
  7.449456,
  7.0083439,
  3.357951,
  7.579008999999999,
  7.493777,
  7.517955600000001,
  7.0079724,
  8.496804,
  7.4609879,
  7.0527365],
 ['National Identity Management Commission',
  'National Identity Management Commission (Nimc)',
  'National Identity Management Commission NIMC',
  'National Identity Management Commission',
  'National Identity Management Commission (Nimc)',
  'National Identity Management Commission',
  'National Identity Management Commission',
  'National Identity Management Commission (Nimc)',
  'National Identity Management Commission',
  'National Identity Management Commission (Nimc)',
  'National Identity Management Commission (Nimc)',
  'National Identity Management Center',
  'National Identity Management Commision (NIMC) Lagos',
  'National Identity Management Commission',
  'National Identity Management Commission (Nimc)',
  'National Identity Management Commission Umuahia',
  'National Identity Management Commission',
  'National Identity Management Commission (Nimc)',
  'National Identity Management Commission, Northwest Zonal Office',
  'National Identity Management Commission Nimc'])

In [162]:
dict_output( places_result, output = "dataframe" )

                                        Instituciones    Latitud  Longitud
0             National Identity Management Commission   9.065977  7.454961
1      National Identity Management Commission (Nimc)   8.450151  4.542503
2        National Identity Management Commission NIMC   8.505730  8.531775
3             National Identity Management Commission   9.058854  7.468078
4      National Identity Management Commission (Nimc)   9.895973  8.931434
5             National Identity Management Commission   9.892295  8.917566
6             National Identity Management Commission   9.857233  7.967972
7      National Identity Management Commission (Nimc)   7.711656  8.526523
8             National Identity Management Commission  11.989994  8.489165
9      National Identity Management Commission (Nimc)  10.310332  9.826602
10     National Identity Management Commission (Nimc)  10.592473  7.449456
11                National Identity Management Center   5.471781  7.008344
12  National Identity Management Commision (NIMC) ...   6.617086  3.357951
13            National Identity Management Commission   6.460106  7.579009
14     National Identity Management Commission (Nimc)   9.076770  7.493777
15    National Identity Management Commission Umuahia   5.502502  7.517956
16            National Identity Management Commission   4.822006  7.007972
17     National Identity Management Commission (Nimc)  11.988203  8.496804
18  National Identity Management Commission, North...  10.543617  7.460988
19       National Identity Management Commission Nimc   4.849608  7.052736

In [164]:
dict_output( places_result, output = "dictionary" )

{'Instituciones': ['National Identity Management Commission',
  'National Identity Management Commission (Nimc)',
  'National Identity Management Commission NIMC',
  'National Identity Management Commission',
  'National Identity Management Commission (Nimc)',
  'National Identity Management Commission',
  'National Identity Management Commission',
  'National Identity Management Commission (Nimc)',
  'National Identity Management Commission',
  'National Identity Management Commission (Nimc)',
  'National Identity Management Commission (Nimc)',
  'National Identity Management Center',
  'National Identity Management Commision (NIMC) Lagos',
  'National Identity Management Commission',
  'National Identity Management Commission (Nimc)',
  'National Identity Management Commission Umuahia',
  'National Identity Management Commission',
  'National Identity Management Commission (Nimc)',
  'National Identity Management Commission, Northwest Zonal Office',
  'National Identity Management Commission Nimc'],
 'Latitud': [9.065977,
  8.450151,
  8.50573,
  9.058854499999999,
  9.895973,
  9.892294699999999,
  9.8572331,
  7.711655800000001,
  11.9899944,
  10.310332,
  10.592473,
  5.4717813,
  6.617086,
  6.460105899999999,
  9.07677,
  5.5025021,
  4.822006,
  11.988203,
  10.5436173,
  4.8496083],
 'Longitud': [7.4549606,
  4.542503,
  8.531774799999999,
  7.468077600000001,
  8.931434,
  8.9175658,
  7.967971899999998,
  8.5265235,
  8.4891647,
  9.826602,
  7.449456,
  7.0083439,
  3.357951,
  7.579008999999999,
  7.493777,
  7.517955600000001,
  7.0079724,
  8.496804,
  7.4609879,
  7.0527365]}

In [165]:
dict_output( places_result, output = "list" )

Exception: The output value (list) is wrong.
You can only use `tuple`, `dataframe`, or `dictionary` as argument variables.

# <a id='2.'>Clase </a> 

* Permite generalizar lo que teníamos por función.
* Es prototipo definido por el usuario a partir del cual se crean los objetos. Las clases proporcionan un medio para agrupar datos y funcionalidad. 
* Crear una nueva clase crea un nuevo tipo de objeto, lo que permite fabricar nuevas instancias de ese tipo.

## <a id='#2.1.'>1. Importancia en Python </a> 

* **Las Clases son una forma de organizar tu código en piezas genéricas y reutilizables.** El concepto original se inspiró en sistemas biológicos independientes u organismos, que se distinguen de otros por su conjunto de características (atributos) y habilidades (métodos). 
* **Las clases son ideales cuando necesitas representar una colección de atributos y métodos que se utilizarán repetidamente en otros lugares.** Las funciones son excelentes cuando los datos son fundamentales para el trabajo que se está realizando. 
* Si estamos escribiendo funciones dentro de funciones, hay que considerar escribir una clase en su lugar. Si solo hay una función dentro de una clase, entonces es mejor quedarse con la función.
* Proporcionan una manera fácil de mantener los miembros de datos y los métodos juntos en un solo lugar, lo cual ayuda a mantener el programa más organizado.
* Su uso también proporciona otra funcionalidad de este paradigma de programación orientada a objetos, es decir, la herencia.
* Ayudan a sobrescribir cualquier operador estándar.
* Agrupar funciones relacionadas y mantenerlas en un solo lugar (dentro de una clase) proporciona una estructura limpia al código, lo que aumenta la legibilidad del programa.

## <a id='#2.2.'>2. Estructura </a>

<font size="4">
<font color='green'>class</font> class_name:<br> <br>
&nbsp;&nbsp;&nbsp;&nbsp;    """Description""" <br><br>
&nbsp;&nbsp;&nbsp;&nbsp;<font color='red'>def __init__</font><font color  = 'blue'>( <font color='red'>self</font>, parameter1, parameter2 )</font>:<br><br>
</font>

## <a id='#2.3.'>3. Atributos </a> 
* Características asociadas a un objeto que está almacenada en la memoria en Python. 
* Pensamos en los atributos como en una característica, un valor o un número. Por ejemplo: `numpy` o `np`
    * `np.size`: Atributo de tamaño.
    * `np.shape`: Atributo de forma.

* Cada librería tiene sus atributos. Toda librería es una clase.

In [2]:
# import numpy as np 

A = np.arange( 8, 25 , 2)
A

array([ 8, 10, 12, 14, 16, 18, 20, 22, 24])

In [3]:
A.size

9

In [ ]:
# Dimensión: 9x1
A.shape

(9,)

In [ ]:
# Ejemplo con el objeto llamado ulises:
## height es un atributo
# ulises.height

## <a id='#2.4.'>4. Métodos </a>
* Es una función que pertenece a un objeto específico y que está diseñada para ejecutar una acción, interactuar con los datos de ese objeto o modificarlos. Desglozando:
    * **Función:** Contiene un bloque de código estructurado que ejecuta una tarea.
    * **Pertenece a un objeto:** A diferencia de las funciones globales e independientes como `print()`, `len()` o `dir()` que vienen por defecto en Python, un método vive dentro de un tipo de dato específico como `df.dropna()`, que está diseñado específicamente para interactuar con un DataFrame mediante un punto.
    * **Se ejecuta con paréntesis ():** Al igual que cualquier función, los paréntesis son el gatillo que le dice a Python que ejecute la acción.

In [ ]:
# Función arrange: Ejecuta una acción.
# Se considera función porque le pertecene a la librería NumPy y no al objeto A.
# En realidad, arrange se encarga de crear al objeto A.
A = np.arange( 8, 25 )
A

array([ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [8]:
# Atributo shape: Característica.
# No es una función porque no ejecuta ninguna operación en sí.
# Solo pedimos al objeto A que muestre una característica o valor que ya tiene almacenada por defecto (sus dimensiones, que en este caso es un arreglo de 17 elementos).
A.shape

(17,)

In [ ]:
# Método mean: Ejecuta una acción.
# Tomo información del objeto para hacer un cálculo
# Es una afunción, tiene paréntesis y le damos una orden al objeto A para ejecute una acción específica sobre sí mismo: calcular su mínimo valor.
A.mean()

16.0

In [ ]:
# Función mean
# Porque le pertece a la librería NumPy
np.mean(A)

16.0

Complementando,
* Las funciones hacen cálculos en base al objeto, sean funciones de las librerías (`arange`) o ligadas al objeto (`mean`).
* Los métodos son funciones específicas ligadas a un objeto, y para ser ejecutadas necesitan usar paréntesis y un punto: `A.mean()`, por ejemplo.

In [ ]:
# Vamos a ver métodos y atributos
dir(A)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__buffer__',
 '__class__',
 '__class_getitem__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rlshift__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__rpow__',
 '__rrshift__',
 '__rshift__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__setitem__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__xor__',
 'all',
 'any',
 'argmax',
 'argmin',
 'argpartition',
 'argsort',
 'astype',
 'base',
 'byteswap',
 'choose',
 'clip',
 'compress',
 'conj',
 'conjugate',
 'copy',
 'ctypes',
 'cumprod',
 'cumsum',
 'data',
 'diagonal',
 'dot',
 'dtype',
 'dump',
 'dumps',
 'fill',
 'flags',
 'flat',
 'flatten',
 'getfield',
 'imag',
 'item',
 'itemset',
 'itemsize',
 'max',
 'mean',
 'min',
 'nbytes',
 'ndim',
 'newbyteorder',
 'nonzero',
 'partition',
 'prod',
 'ptp',
 'put',
 'ravel',
 'real',
 'repeat',
 'reshape',
 'resize',
 'round',
 'searchsorted',
 'setfield',
 'setflags',
 'shape',
 'size',
 'sort',
 'squeeze',
 'std',
 'strides',
 'sum',
 'swapaxes',
 'take',
 'tobytes',
 'tofile',
 'tolist',
 'tostring',
 'trace',
 'transpose',
 'var',
 'view']

|Name| Definition|
|---|---|
|attribute|A variable stored in an instance or class.|
|method|A function stored in an instance or class.|

## <a id='#2.5.'> 5. Clases</a>

* Es la plantilla teórica o el molde que define qué forma tendrá un objeto, qué información almacenará (atributos) y qué operaciones podrá realizar con ella (métodos).

* Es pura planificación; no es un dato real que puedas analizar todavía. Si vas a analizar microdatos de una encuesta nacional de hogares, la Clase es el manual metodológico o el cuestionario en blanco. Establece que existirá un "Hogar", que ese hogar tendrá una "región" y unos "ingresos", pero no contiene las respuestas de ninguna familia específica.

##  <a id='#2.6.'> 6. \_\_init\_\_() </a>

En las clases de Python, el método “__init__” está reservado. Se llama automáticamente cuando creas un objeto usando una clase y se utiliza para inicializar las variables de dicha clase. Es equivalente a un constructor. 

* Al igual que cualquier otro método, el método init comienza con la palabra clave “def”.
* **“self”** es el primer parámetro en este método, al igual que en cualquier otro método, aunque en el caso de init, **“self”** se refiere a un objeto recién creado, a diferencia de otros métodos donde se refiere al objeto o instancia actual asociado con ese método en particular.
* Se pueden agregar parámetros adicionales.

## <a id='#2.7.'> 7. self</a>
* **self** es el mecanismo interno de Python que permite que un objeto diga 'yo' o 'mi' para acceder a sus propios datos y acciones sin confundirse con el resto
* Tres reglas clave para recordarlo:
    * No es una palabra reservada del sistema: Es una convención estricta de la comunidad de Python. Podrías llamarlo de otra forma, pero nadie lo hace.
    * Siempre va primero: En cualquier método dentro de una clase (incluido el constructor __init__), self tiene que ser obligatoriamente el primer parámetro dentro del paréntesis.
    * Es invisible al usarlo: Cuando tú, como usuario, llamas a un método (ej. mi_encuesta.calcular_estrato()), no escribes self adentro de los paréntesis. Python lo envía "por debajo de la mesa" de forma automática.

**Conectando Clases, __int__ y self:**
* Imaginemos que estamos administrando el trabajo de campo y recibo cuestionarios físicos que hay que digitalizar:
    * La Clase es el diseño de la base de datos (qué columnas tendrá).
    * __init__ es el momento exacto en que abres una nueva fila en blanco en tu base de datos para ingresar una nueva encuesta.
    * self es el cursor parpadeando en esa fila específica, listo para recibir los datos y asegurarse de que no se escriban en la fila de arriba ni en la de abajo.

* La secuencia lógica es la siguiente:
    * Cuando le dices a Python que cree un nuevo objeto a partir de tu Clase, el lenguaje necesita construirlo y llenarlo con sus primeros datos.
    * Para construirlo, Python llama automáticamente al método constructor: __init__.
    * Pero __init__ es solo una función ejecutándose; necesita saber a quién le va a asignar los datos. Por eso, Python genera el objeto vacío y se lo entrega a __init__ bajo el nombre de self.

## <a id='#2.8.'>8. Juntando las definiciones en casos prácticos</a>

* Cuando defines una **Clase** en Python, no estás procesando datos reales todavía. Simplemente le estás entregando un "manual de instrucciones" a la computadora. Le avisas al sistema: "A partir de ahora, existirá una nueva estructura de datos con estas reglas", y Python guarda ese diseño en su memoria general a la espera de que lo uses.

* La verdadera acción comienza con el **__init__**. Este es un método inicializador que entra a trabajar en el milisegundo exacto en que decides crear un caso o registro nuevo basándote en el manual de tu Clase. Python lo ejecuta de forma automática para darle nacimiento a ese registro.

* En el momento en que el **__init__** arranca, Python separa un bloque de memoria RAM exclusivamente para ese nuevo caso. Aquí es donde entra el **self**. El **self** es, literalmente, la dirección técnica o el "link" a ese bloque de memoria. Es un ancla que le dice a la computadora: "los datos que voy a recibir ahora no los dejes sueltos en el sistema, guárdalos exactamente en este espacio privado".

* Gracias a que tienes esa dirección de memoria asegurada por el self, puedes crear y guardar los **Atributos**. Por ejemplo, cuando ingresas la edad de un informante, Python viaja por el self hasta ese bloque de memoria reservado y anota el número de forma permanente. Si no usaras el self, la computadora olvidaría el dato apenas termine de procesar la creación del registro.

* Finalmente, tienes los **Métodos**. Estas son funciones que viven anidadas dentro de la **Clase** y que comparten el mismo **self**. Al tener esa "llave" de acceso a la memoria, los **Métodos** pueden entrar al espacio privado del registro, leer los atributos que guardaste (como la edad) y ejecutar acciones lógicas sobre ellos, como cambiar el estado de validación o lanzar una alerta si el dato no es consistente.

En el ejemplo, **MyFirstClass** usa self para definir atributos y métodos:

In [10]:
class MyFirstCar:
    
    # Llamos a la función int que nos permitirá generar los atributos:
    # self va por estructura, diciendo tipo que los datos se le asignarán así misma
    def __init__(self, model, year):

        # El atributo llamado modelo_car va a tomar el valor de modelo cuando coloquemos algún valor de modelo (model). Lo mismo con year_manu
        self.model_car = model
        self.year_manu = year

# Hasta aquí, la clase MyFirstCar tiene dos atributos: model_car y year_manu

In [ ]:
# Creo el objeto con los atributos que le especifico:
# También es válido: mycar = MyFirstCar(model = "Lexus", year = "2025")
mycar = MyFirstCar("Lexus", "2025")

In [ ]:
# Ahora llamo al atributo: solo con punto sin paréntesis
mycar.model_car

'Lexus'

In [ ]:
# Igual aquí: llamo al atributo recién creado
mycar.year_manu

'2025'

In [140]:
student1 = MyFirstClass( name = "Miguel", age = 24)
student1.print_name_1()
student1.print_age_1()

I am Miguel.
I am  24 years old

In [ ]:
student_0 = MyFirstClass( name = "Jose" , age = 22, school = "Saco Oliveros" )

In [35]:
class MyFirstClass:
    
    def __init__( self, name, age ):
        self.name = name
        self.age = age
    
    # best way to define a method
    def print_name_1( self ):
        print( f'I am { self.name }.' )
    
    # wrong way to define a method 
    def print_name_2():
        print( f'This is my { name }.' )
    
    
    # the worst way to call a parameter
    # we need to define them as attributes
    def print_name_3( self ):
        print( f'This is my { name }.' )

In [155]:
class MyFirstClass:
    
    def __init__( self, name, age, school ):
        self.name = name
        self.age = age
        self.school = school
    
    # how to define a method
    def print_name_1( self ):
        print( f'I am { self.name }.' )
    
    # other method
    def person_age( self ):
        print( f' I am { self.name } , I am { self.age } old. ' )
    
    # method
    def person_school( self ):
        print( f' I am {self.name} , I studied at {self.school}. ' )
      
    # # wrong way to define a method 
    def print_name_2():
        print( f'This is my { name }.' )
    
    # the worst way to call a parameter
    # we need to define them as attributes
    # def print_name_3( self ):
    #     print( f'This is my { name }.' )

In [156]:
student2 = MyFirstClass( name = "Jose" , age = 31, school = "Agustiniano" )

In [157]:
dir(student2)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'age',
 'name',
 'person_age',
 'person_school',
 'print_name_1',
 'print_name_2',
 'school']

In [153]:
student2.person_school()

 I am Jose , I studied at Agustiniano.

In [154]:
student2.print_name_2()

TypeError: print_name_2() takes 0 positional arguments but 1 was given

In [237]:
student_0 = MyFirstClass( name = "Jose" , age = 22, school = "Saco Oliveros" )

In [234]:
student_0.person_school()

 I am Jose , I study at Saco Oliveros.

In [238]:
student_0.print_name_3()

NameError: name 'name' is not defined

In [224]:
student_0.print_name_1()

I am Jose.

When we create an object using a class, we have an instance of this class.

In [36]:
student1 = MyFirstClass( name = "Jose" , age = 22 )

Attributes

In [26]:
student1.age

22

In [27]:
student1.name

'Jose'

Methods

In [28]:
# Calling like an attribute
student1.print_name_1

In [32]:
# Calling like as a method
student1.print_name_1()

I am Jose.

When we do not use the **self** keyword, the class do not recognize `print_name_2` function as a method.

In [33]:
student1.print_name_2()

TypeError: print_name_2() takes 0 positional arguments but 1 was given

When we do not use the **self** keyword, the class does not recognize `name` variable. We need to define it as an `attribute`. Classes are not the same as functions. In functions, the parameters are identified in the namespace, but in classes, they do not.

In [37]:
student1.print_name_3()

NameError: name 'name' is not defined

# <a id='#5.3.'>5.3. References </a>  

- [Functions](https://www.datacamp.com/community/tutorials/functions-python-tutorial?utm_source=adwords_ppc&utm_medium=cpc&utm_campaignid=1455363063&utm_adgroupid=65083631748&utm_device=c&utm_keyword=&utm_matchtype=&utm_network=g&utm_adpostion=&utm_creative=332602034358&utm_targetid=dsa-473406571355&utm_loc_interest_ms=&utm_loc_physical_ms=9060932&gclid=CjwKCAiAqIKNBhAIEiwAu_ZLDp9lkv0t5drR4g_hjgXp0DBU3XoRLPEeQT9wGMhCyiZd09kjsAXKaRoCFmUQAvD_BwE)
- [Functions](https://www.w3schools.com/python/python_functions.asp)
- [Args and Kwargs](https://book.pythontips.com/en/latest/args_and_kwargs.html)

- [Clases](https://www.geeksforgeeks.org/namespaces-and-scope-in-python/#:~:text=A%20namespace%20is%20a%20system,form%20of%20a%20Python%20dictionary.&text=Its%20Name%20(which%20means%20name,talks%20something%20related%20to%20scope)

- [Clases](https://www.geeksforgeeks.org/python-classes-and-objects/)

- [Clases Advantages](https://intellipaat.com/blog/tutorial/python-tutorial/python-classes-and-objects/#_Advantages_of_class)

- [Self](https://www.geeksforgeeks.org/self-in-python-class/)

- [FU](https://realpython.com/defining-your-own-python-function/#functions-in-python)

- https://stackoverflow.com/questions/46312470/difference-between-methods-and-attributes-in-python

- https://stackoverflow.com/questions/2489669/how-do-python-functions-handle-the-types-of-parameters-that-you-pass-in